.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
nonmatching jtbl_80011848

dlabel jtbl_80011848
    /* 2048 80011848 8CB00580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B08C
    /* 204C 8001184C DCB10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 2050 80011850 DCB10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 2054 80011854 DCB10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 2058 80011858 DCB10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 205C 8001185C B0B00580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B0B0
    /* 2060 80011860 38B10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B138
    /* 2064 80011864 84B10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B184
    /* 2068 80011868 C0B10580 */ .word .LDreamSys__InstanceEffectsOnJournal_8005B1C0
enddlabel jtbl_80011848


.section .text
/* Generated by spimdisasm 1.41.0 */

nonmatching DreamSys__InstanceEffectsOnJournal, 0x1B8

glabel DreamSys__InstanceEffectsOnJournal
    /* 4B83C 8005B03C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 4B840 8005B040 1000B0AF */  sw         $s0, 0x10($sp)
    /* 4B844 8005B044 21808000 */  addu       $s0, $a0, $zero
    /* 4B848 8005B048 1800BFAF */  sw         $ra, 0x18($sp)
    /* 4B84C 8005B04C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 4B850 8005B050 4400028E */  lw         $v0, 0x44($s0)
    /* 4B854 8005B054 00000000 */  nop
    /* 4B858 8005B058 60004014 */  bnez       $v0, .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B85C 8005B05C 2188A000 */   addu      $s1, $a1, $zero
    /* 4B860 8005B060 FCFFC324 */  addiu      $v1, $a2, -0x4
    /* 4B864 8005B064 0900622C */  sltiu      $v0, $v1, 0x9
    /* 4B868 8005B068 5C004010 */  beqz       $v0, .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B86C 8005B06C 80100300 */   sll       $v0, $v1, 2
    /* 4B870 8005B070 0180013C */  lui        $at, %hi(jtbl_80011848)
    /* 4B874 8005B074 48182124 */  addiu      $at, $at, %lo(jtbl_80011848)
    /* 4B878 8005B078 21082200 */  addu       $at, $at, $v0
    /* 4B87C 8005B07C 0000228C */  lw         $v0, 0x0($at)
    /* 4B880 8005B080 00000000 */  nop
    /* 4B884 8005B084 08004000 */  jr         $v0
    /* 4B888 8005B088 00000000 */   nop
  .LDreamSys__InstanceEffectsOnJournal_8005B08C:
    /* 4B88C 8005B08C 21202002 */  addu       $a0, $s1, $zero
    /* 4B890 8005B090 0000828C */  lw         $v0, 0x0($a0)
    /* 4B894 8005B094 00000000 */  nop
    /* 4B898 8005B098 3800428C */  lw         $v0, 0x38($v0)
    /* 4B89C 8005B09C 00000000 */  nop
    /* 4B8A0 8005B0A0 09F84000 */  jalr       $v0
    /* 4B8A4 8005B0A4 21280002 */   addu      $a1, $s0, $zero
    /* 4B8A8 8005B0A8 776C0108 */  j          .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B8AC 8005B0AC 00000000 */   nop
  .LDreamSys__InstanceEffectsOnJournal_8005B0B0:
    /* 4B8B0 8005B0B0 6800028E */  lw         $v0, 0x68($s0)
    /* 4B8B4 8005B0B4 00000000 */  nop
    /* 4B8B8 8005B0B8 48004014 */  bnez       $v0, .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B8BC 8005B0BC 00000000 */   nop
    /* 4B8C0 8005B0C0 0000228E */  lw         $v0, 0x0($s1)
    /* 4B8C4 8005B0C4 00000000 */  nop
    /* 4B8C8 8005B0C8 4C01428C */  lw         $v0, 0x14C($v0)
    /* 4B8CC 8005B0CC 00000000 */  nop
    /* 4B8D0 8005B0D0 09F84000 */  jalr       $v0
    /* 4B8D4 8005B0D4 21202002 */   addu      $a0, $s1, $zero
    /* 4B8D8 8005B0D8 0000038E */  lw         $v1, 0x0($s0)
    /* 4B8DC 8005B0DC 21200002 */  addu       $a0, $s0, $zero
    /* 4B8E0 8005B0E0 F801638C */  lw         $v1, 0x1F8($v1)
    /* 4B8E4 8005B0E4 00000000 */  nop
    /* 4B8E8 8005B0E8 09F86000 */  jalr       $v1
    /* 4B8EC 8005B0EC 21284000 */   addu      $a1, $v0, $zero
    /* 4B8F0 8005B0F0 0000228E */  lw         $v0, 0x0($s1)
    /* 4B8F4 8005B0F4 00000000 */  nop
    /* 4B8F8 8005B0F8 5001428C */  lw         $v0, 0x150($v0)
    /* 4B8FC 8005B0FC 00000000 */  nop
    /* 4B900 8005B100 09F84000 */  jalr       $v0
    /* 4B904 8005B104 21202002 */   addu      $a0, $s1, $zero
    /* 4B908 8005B108 21200002 */  addu       $a0, $s0, $zero
    /* 4B90C 8005B10C 21280000 */  addu       $a1, $zero, $zero
    /* 4B910 8005B110 8C01838C */  lw         $v1, 0x18C($a0)
    /* 4B914 8005B114 0000868C */  lw         $a2, 0x0($a0)
    /* 4B918 8005B118 21104300 */  addu       $v0, $v0, $v1
    /* 4B91C 8005B11C 8C0182AC */  sw         $v0, 0x18C($a0)
    /* 4B920 8005B120 1802C28C */  lw         $v0, 0x218($a2)
    /* 4B924 8005B124 00000000 */  nop
    /* 4B928 8005B128 09F84000 */  jalr       $v0
    /* 4B92C 8005B12C 10000634 */   ori       $a2, $zero, 0x10
    /* 4B930 8005B130 776C0108 */  j          .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B934 8005B134 00000000 */   nop
  .LDreamSys__InstanceEffectsOnJournal_8005B138:
    /* 4B938 8005B138 0000228E */  lw         $v0, 0x0($s1)
    /* 4B93C 8005B13C 21202002 */  addu       $a0, $s1, $zero
    /* 4B940 8005B140 5401428C */  lw         $v0, 0x154($v0)
    /* 4B944 8005B144 6401118E */  lw         $s1, 0x164($s0)
    /* 4B948 8005B148 09F84000 */  jalr       $v0
    /* 4B94C 8005B14C 00000000 */   nop
    /* 4B950 8005B150 0000038E */  lw         $v1, 0x0($s0)
    /* 4B954 8005B154 23100200 */  negu       $v0, $v0
    /* 4B958 8005B158 640102AE */  sw         $v0, 0x164($s0)
    /* 4B95C 8005B15C C401628C */  lw         $v0, 0x1C4($v1)
    /* 4B960 8005B160 00000000 */  nop
    /* 4B964 8005B164 09F84000 */  jalr       $v0
    /* 4B968 8005B168 21200002 */   addu      $a0, $s0, $zero
    /* 4B96C 8005B16C 6401028E */  lw         $v0, 0x164($s0)
    /* 4B970 8005B170 00000000 */  nop
    /* 4B974 8005B174 19004104 */  bgez       $v0, .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B978 8005B178 00000000 */   nop
    /* 4B97C 8005B17C 776C0108 */  j          .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B980 8005B180 640111AE */   sw        $s1, 0x164($s0)
  .LDreamSys__InstanceEffectsOnJournal_8005B184:
    /* 4B984 8005B184 6800028E */  lw         $v0, 0x68($s0)
    /* 4B988 8005B188 00000000 */  nop
    /* 4B98C 8005B18C 13004014 */  bnez       $v0, .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B990 8005B190 FFFF0224 */   addiu     $v0, $zero, -0x1
    /* 4B994 8005B194 3401038E */  lw         $v1, 0x134($s0)
    /* 4B998 8005B198 680102A6 */  sh         $v0, 0x168($s0)
    /* 4B99C 8005B19C 240003AE */  sw         $v1, 0x24($s0)
    /* 4B9A0 8005B1A0 0000228E */  lw         $v0, 0x0($s1)
    /* 4B9A4 8005B1A4 00000000 */  nop
    /* 4B9A8 8005B1A8 5801428C */  lw         $v0, 0x158($v0)
    /* 4B9AC 8005B1AC 00000000 */  nop
    /* 4B9B0 8005B1B0 09F84000 */  jalr       $v0
    /* 4B9B4 8005B1B4 21202002 */   addu      $a0, $s1, $zero
    /* 4B9B8 8005B1B8 776C0108 */  j          .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B9BC 8005B1BC 6A0102A6 */   sh        $v0, 0x16A($s0)
  .LDreamSys__InstanceEffectsOnJournal_8005B1C0:
    /* 4B9C0 8005B1C0 6800028E */  lw         $v0, 0x68($s0)
    /* 4B9C4 8005B1C4 00000000 */  nop
    /* 4B9C8 8005B1C8 04004014 */  bnez       $v0, .LDreamSys__InstanceEffectsOnJournal_8005B1DC
    /* 4B9CC 8005B1CC 00000000 */   nop
    /* 4B9D0 8005B1D0 3401028E */  lw         $v0, 0x134($s0)
    /* 4B9D4 8005B1D4 00000000 */  nop
    /* 4B9D8 8005B1D8 240002AE */  sw         $v0, 0x24($s0)
  .LDreamSys__InstanceEffectsOnJournal_8005B1DC:
    /* 4B9DC 8005B1DC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 4B9E0 8005B1E0 1400B18F */  lw         $s1, 0x14($sp)
    /* 4B9E4 8005B1E4 1000B08F */  lw         $s0, 0x10($sp)
    /* 4B9E8 8005B1E8 2000BD27 */  addiu      $sp, $sp, 0x20
    /* 4B9EC 8005B1EC 0800E003 */  jr         $ra
    /* 4B9F0 8005B1F0 00000000 */   nop
endlabel DreamSys__InstanceEffectsOnJournal
