.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 3
nonmatching jtbl_80010F64

dlabel jtbl_80010F64
    /* 1764 80010F64 9C760380 */ .word .L8003769C
    /* 1768 80010F68 64760380 */ .word .L80037664
    /* 176C 80010F6C 6C760380 */ .word .L8003766C
    /* 1770 80010F70 74760380 */ .word .L80037674
    /* 1774 80010F74 7C760380 */ .word .L8003767C
    /* 1778 80010F78 84760380 */ .word .L80037684
    /* 177C 80010F7C 8C760380 */ .word .L8003768C
    /* 1780 80010F80 94760380 */ .word .L80037694
enddlabel jtbl_80010F64

.align 3
nonmatching jtbl_80010F84

dlabel jtbl_80010F84
    /* 1784 80010F84 68770380 */ .word .L80037768
    /* 1788 80010F88 30770380 */ .word .L80037730
    /* 178C 80010F8C 38770380 */ .word .L80037738
    /* 1790 80010F90 40770380 */ .word .L80037740
    /* 1794 80010F94 48770380 */ .word .L80037748
    /* 1798 80010F98 50770380 */ .word .L80037750
    /* 179C 80010F9C 58770380 */ .word .L80037758
    /* 17A0 80010FA0 60770380 */ .word .L80037760
enddlabel jtbl_80010F84

.align 2
nonmatching D_80010FA4

dlabel D_80010FA4
    /* 17A4 80010FA4 */ .asciz "SPU:T/O [%s]\n"
    /* 5350553A542F4F205B25735D0A000000 */
.align 2
enddlabel D_80010FA4

.align 2
nonmatching D_80010FB4

dlabel D_80010FB4
    /* 17B4 80010FB4 */ .asciz "wait (reset)"
    /* 77616974202872657365742900000000 */
.align 2
enddlabel D_80010FB4

.align 2
nonmatching D_80010FC4

dlabel D_80010FC4
    /* 17C4 80010FC4 */ .asciz "wait (wrdy H -> L)"
    /* 776169742028777264792048202D3E204C290000 */
.align 2
enddlabel D_80010FC4

.align 2
nonmatching D_80010FD8

dlabel D_80010FD8
    /* 17D8 80010FD8 */ .asciz "wait (dmaf clear/W)"
    /* 776169742028646D616620636C6561722F572900 */
.align 2
enddlabel D_80010FD8

.align 2
nonmatching D_80010FEC

dlabel D_80010FEC
    /* 17EC 80010FEC */ .asciz "Seq Open error in WBgmHandleMonitorEvent"
    /* 536571204F70656E206572726F7220696E205742676D48616E646C654D6F6E69746F724576656E7400000000 */
.align 2
enddlabel D_80010FEC

.align 2
nonmatching D_80011018

dlabel D_80011018
    /* 1818 80011018 */ .asciz "This is not SEQ Data.\n"
    /* 54686973206973206E6F742053455120446174612E0A0000 */
.align 2
enddlabel D_80011018

.align 2
nonmatching D_80011030

dlabel D_80011030
    /* 1830 80011030 */ .asciz "This is an old SEQ Data Format.\n"
    /* 5468697320697320616E206F6C6420534551204461746120466F726D61742E0A00000000 */
.align 2
enddlabel D_80011030

.align 2
nonmatching D_80011054

dlabel D_80011054
    /* 1854 80011054 */ .asciz "Can't Open Sequence data any more\n\n"
    /* 43616E2774204F70656E2053657175656E6365206461746120616E79206D6F72650A0A00 */
.align 2
enddlabel D_80011054

.align 2
nonmatching D_80011078

dlabel D_80011078
    /* 1878 80011078 */ .asciz "CdInit: Init failed\n"
    /* 4364496E69743A20496E6974206661696C65640A00000000 */
.align 2
enddlabel D_80011078
