.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 3
nonmatching jtbl_80011290

dlabel jtbl_80011290
    /* 1A90 80011290 8C1E0480 */ .word .L80041E8C
    /* 1A94 80011294 A81E0480 */ .word .L80041EA8
    /* 1A98 80011298 B01E0480 */ .word .L80041EB0
    /* 1A9C 8001129C BC1E0480 */ .word .L80041EBC
    /* 1AA0 800112A0 C41E0480 */ .word .L80041EC4
enddlabel jtbl_80011290

.align 2
nonmatching D_800112A4

dlabel D_800112A4
    /* 1AA4 800112A4 */ .asciz "MDEC_rest:bad option(%d)\n"
    /* 4D4445435F726573743A626164206F7074696F6E282564290A000000 */
.align 2
enddlabel D_800112A4

.align 2
nonmatching D_800112C0

dlabel D_800112C0
    /* 1AC0 800112C0 */ .asciz "MDEC_in_sync"
    /* 4D4445435F696E5F73796E6300000000 */
.align 2
enddlabel D_800112C0

.align 2
nonmatching D_800112D0

dlabel D_800112D0
    /* 1AD0 800112D0 */ .asciz "MDEC_out_sync"
    /* 4D4445435F6F75745F73796E63000000 */
.align 2
enddlabel D_800112D0

.align 2
nonmatching D_800112E0

dlabel D_800112E0
    /* 1AE0 800112E0 */ .asciz "\t DMA=(%d,%d), ADDR=(0x%08x->0x%08x)\n"
    /* 0920444D413D2825642C2564292C20414444523D283078253038782D3E307825303878290A000000 */
.align 2
enddlabel D_800112E0

.align 2
nonmatching D_80011308

dlabel D_80011308
    /* 1B08 80011308 */ .asciz "\t FIFO=(%d,%d),BUSY=%d,DREQ=(%d,%d),RGB24=%d,STP=%d\n"
    /* 09204649464F3D2825642C2564292C425553593D25642C445245513D2825642C2564292C52474232343D25642C5354503D25640A00000000 */
.align 2
enddlabel D_80011308

.align 2
nonmatching D_80011340

dlabel D_80011340
    /* 1B40 80011340 */ .asciz "%s timeout:\n"
    /* 25732074696D656F75743A0A00000000 */
.align 2
enddlabel D_80011340

.align 2
nonmatching D_80011350

dlabel D_80011350
    /* 1B50 80011350 */ .asciz "MDEC_vlec: invalid VLC ID\n"
    /* 4D4445435F766C65633A20696E76616C696420564C432049440A0000 */
.align 2
enddlabel D_80011350

.align 2
nonmatching D_8001136C

dlabel D_8001136C
    /* 1B6C 8001136C */ .asciz "DMA STATUS ERROR %x\n"
    /* 444D4120535441545553204552524F522025780A00000000 */
.align 2
.align 2
    /* 1B84 80011384 */ .asciz "SND\\STANDERD"
    /* 534E445C5354414E4445524400000000 */
.align 2
.align 2
    /* 1B94 80011394 */ .asciz "SND\\LOVELY"
    /* 534E445C4C4F56454C590000 */
.align 2
.align 2
    /* 1BA0 800113A0 */ .asciz "SND\\HUMAN"
    /* 534E445C48554D414E000000 */
.align 2
.align 2
    /* 1BAC 800113AC */ .asciz "SND\\ETHNOVA"
    /* 534E445C4554484E4F564100 */
.align 2
.align 2
    /* 1BB8 800113B8 */ .asciz "SND\\ELECTRO"
    /* 534E445C454C454354524F00 */
.align 2
.align 2
    /* 1BC4 800113C4 */ .asciz "SND\\CARTOON"
    /* 534E445C434152544F4F4E00 */
.align 2
.align 2
    /* 1BD0 800113D0 */ .asciz "SND\\AMBIENT"
    /* 534E445C414D4249454E5400 */
.align 2
enddlabel D_8001136C

.align 2
nonmatching D_800113DC

dlabel D_800113DC
    /* 1BDC 800113DC */ .asciz "ETC\\ASMK.STR"
    /* 4554435C41534D4B2E53545200000000 */
.align 2
enddlabel D_800113DC

.align 2
nonmatching strEtcTim

dlabel strEtcTim
    /* 1BEC 800113EC */ .asciz "ETC\\ETC.TIM"
    /* 4554435C4554432E54494D00 */
.align 2
enddlabel strEtcTim

.align 2
nonmatching strDreamerTmd

dlabel strDreamerTmd
    /* 1BF8 800113F8 */ .asciz "ETC\\DREAMER.TMD"
    /* 4554435C445245414D45522E544D4400 */
.align 2
.align 2
    /* 1C08 80011408 */ .asciz ""
    /* 00000000 */
.align 2
enddlabel strDreamerTmd
