.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching gVtable_DreamScene

dlabel gVtable_DreamScene
    /* 76DC8 800865C8 30F20100 */ .word 0x0001F230
    /* 76DCC 800865CC B07E0180 */ .word BasicClass__Delete
    /* 76DD0 800865D0 84960480 */ .word DreamScene__Constructor
    /* 76DD4 800865D4 30980480 */ .word DreamScene__Destructor
    /* 76DD8 800865D8 987F0180 */ .word BasicClass__AdoptChild
    /* 76DDC 800865DC F07F0180 */ .word BasicClass__func_17ff0
    /* 76DE0 800865E0 40800180 */ .word BasicClass__func_18040
    /* 76DE4 800865E4 BC800180 */ .word BasicClass__NextChildA
    /* 76DE8 800865E8 FC800180 */ .word BasicClass__AddChildB
    /* 76DEC 800865EC 1C810180 */ .word BasicClass__RemoveChildB
    /* 76DF0 800865F0 3C810180 */ .word BasicClass__ClearChildrenB
    /* 76DF4 800865F4 6C810180 */ .word BasicClass__NextChildB
    /* 76DF8 800865F8 CC820180 */ .word BasicClass__func_182cc
    /* 76DFC 800865FC 50830180 */ .word BasicClass__Nop
    /* 76E00 80086600 58990480 */ .word DreamScene__Cleanup
    /* 76E04 80086604 00000000 */ .word 0x00000000
    /* 76E08 80086608 149A0480 */ .word DreamScene__ResetState
    /* 76E0C 8008660C 1C9A0480 */ .word DreamScene__Update
    /* 76E10 80086610 C09A0480 */ .word DreamScene__UpdateCamera
    /* 76E14 80086614 549B0480 */ .word DreamScene__BeginLoad
    /* 76E18 80086618 509C0480 */ .word DreamScene__EndLoad
    /* 76E1C 8008661C A89C0480 */ .word DreamScene__TryEnterWorld
    /* 76E20 80086620 5CA30480 */ .word SceneObj__Nop
    /* 76E24 80086624 64A30480 */ .word SceneObj__TickTimeout
    /* 76E28 80086628 ECA30480 */ .word SceneObj__SetState
    /* 76E2C 8008662C 38E50380 */ .word Effect__ResetAndPause
    /* 76E30 80086630 78E50380 */ .word Effect__ResetAndResume
    /* 76E34 80086634 58A40480 */ .word SceneObj__SetTimeout
    /* 76E38 80086638 78A40480 */ .word SceneObj__PlaySfx
    /* 76E3C 8008663C 00000000 */ .word 0x00000000
    /* 76E40 80086640 00000000 */ .word 0x00000000
    /* 76E44 80086644 A49E0480 */ .word DreamScene__Nop7C
    /* 76E48 80086648 AC9E0480 */ .word DreamScene__Nop80
    /* 76E4C 8008664C B49E0480 */ .word DreamScene__Method84
enddlabel gVtable_DreamScene

nonmatching D_80086650

dlabel D_80086650
    /* 76E50 80086650 00000000 */ .word 0x00000000
    /* 76E54 80086654 50FBFFFF */ .word 0xFFFFFB50
    /* 76E58 80086658 00000000 */ .word 0x00000000
enddlabel D_80086650

nonmatching D_8008665C

dlabel D_8008665C
    /* 76E5C 8008665C 00000000 */ .word 0x00000000
    /* 76E60 80086660 50FBFFFF */ .word 0xFFFFFB50
    /* 76E64 80086664 10270000 */ .word 0x00002710
enddlabel D_8008665C

nonmatching gVtable_SceneObj

dlabel gVtable_SceneObj
    /* 76E68 80086668 30020000 */ .word 0x00000230
    /* 76E6C 8008666C B07E0180 */ .word BasicClass__Delete
    /* 76E70 80086670 9CA10480 */ .word SceneObj__Constructor
    /* 76E74 80086674 28A20480 */ .word SceneObj__Destructor
    /* 76E78 80086678 987F0180 */ .word BasicClass__AdoptChild
    /* 76E7C 8008667C F07F0180 */ .word BasicClass__func_17ff0
    /* 76E80 80086680 40800180 */ .word BasicClass__func_18040
    /* 76E84 80086684 BC800180 */ .word BasicClass__NextChildA
    /* 76E88 80086688 FC800180 */ .word BasicClass__AddChildB
    /* 76E8C 8008668C 1C810180 */ .word BasicClass__RemoveChildB
    /* 76E90 80086690 3C810180 */ .word BasicClass__ClearChildrenB
    /* 76E94 80086694 6C810180 */ .word BasicClass__NextChildB
    /* 76E98 80086698 CC820180 */ .word BasicClass__func_182cc
    /* 76E9C 8008669C 50830180 */ .word BasicClass__Nop
    /* 76EA0 800866A0 30E00380 */ .word Effect__Destroy
    /* 76EA4 800866A4 00000000 */ .word 0x00000000
    /* 76EA8 800866A8 94A20480 */ .word SceneObj__ClearTimeout
    /* 76EAC 800866AC C4A20480 */ .word SceneObj__Process
    /* 76EB0 800866B0 24A30480 */ .word SceneObj__Method48
    /* 76EB4 800866B4 00000000 */ .word 0x00000000
    /* 76EB8 800866B8 00000000 */ .word 0x00000000
    /* 76EBC 800866BC 18E40380 */ .word Effect__HandleChildMsg
    /* 76EC0 800866C0 5CA30480 */ .word SceneObj__Nop
    /* 76EC4 800866C4 64A30480 */ .word SceneObj__TickTimeout
    /* 76EC8 800866C8 ECA30480 */ .word SceneObj__SetState
    /* 76ECC 800866CC 38E50380 */ .word Effect__ResetAndPause
    /* 76ED0 800866D0 78E50380 */ .word Effect__ResetAndResume
    /* 76ED4 800866D4 58A40480 */ .word SceneObj__SetTimeout
    /* 76ED8 800866D8 78A40480 */ .word SceneObj__PlaySfx
    /* 76EDC 800866DC 00000000 */ .word 0x00000000
    /* 76EE0 800866E0 00000000 */ .word 0x00000000
    /* 76EE4 800866E4 00000000 */ .word 0x00000000
enddlabel gVtable_SceneObj

nonmatching gVtable_StageRenderer

dlabel gVtable_StageRenderer
    /* 76EE8 800866E8 14010000 */ .word 0x00000114
    /* 76EEC 800866EC B07E0180 */ .word BasicClass__Delete
    /* 76EF0 800866F0 34A50480 */ .word StageRenderer__Constructor
    /* 76EF4 800866F4 C0A70480 */ .word StageRenderer__Destructor
    /* 76EF8 800866F8 48CC0180 */ .word SceneNode__HandleMessage
    /* 76EFC 800866FC B4CC0180 */ .word func_8001CCB4
    /* 76F00 80086700 20CD0180 */ .word SceneNode__Reset
    /* 76F04 80086704 BC800180 */ .word BasicClass__NextChildA
    /* 76F08 80086708 FC800180 */ .word BasicClass__AddChildB
    /* 76F0C 8008670C 1C810180 */ .word BasicClass__RemoveChildB
    /* 76F10 80086710 3C810180 */ .word BasicClass__ClearChildrenB
    /* 76F14 80086714 6C810180 */ .word BasicClass__NextChildB
    /* 76F18 80086718 CC820180 */ .word BasicClass__func_182cc
    /* 76F1C 8008671C 50830180 */ .word BasicClass__Nop
    /* 76F20 80086720 84A90480 */ .word StageRenderer__HandleEvent
    /* 76F24 80086724 00000000 */ .word 0x00000000
    /* 76F28 80086728 10AA0480 */ .word StageRenderer__PostInit
    /* 76F2C 8008672C B4CE0180 */ .word func_8001CEB4
    /* 76F30 80086730 08D00180 */ .word func_8001D008
    /* 76F34 80086734 ECD00180 */ .word SceneNode__AttachChild
    /* 76F38 80086738 A4D10180 */ .word SceneNode__DetachChild
    /* 76F3C 8008673C 04D20180 */ .word SceneNode__UpdateChildren
    /* 76F40 80086740 80D20180 */ .word SceneNode__FindChild
    /* 76F44 80086744 3CD30180 */ .word func_8001D33C
    /* 76F48 80086748 44D30180 */ .word SceneNode__SetInvisible
    /* 76F4C 8008674C 74D30180 */ .word SceneNode__SetAttrBit30
    /* 76F50 80086750 A0D30180 */ .word SceneNode__SetDrawMode
    /* 76F54 80086754 CCD30180 */ .word SceneNode__SetAttrBit6
    /* 76F58 80086758 F8D30180 */ .word SceneNode__SetAttrField3
    /* 76F5C 8008675C 24D40180 */ .word SceneNode__SetAttrField0
    /* 76F60 80086760 50D40180 */ .word SceneNode__SetAttrBit7
    /* 76F64 80086764 80D40180 */ .word SceneNode__SetAttrField9
    /* 76F68 80086768 ACD40180 */ .word SceneNode__SetAttrBit8
    /* 76F6C 8008676C DCD40180 */ .word func_8001D4DC
    /* 76F70 80086770 6CAA0480 */ .word StageRenderer__SetCallbackEntity
    /* 76F74 80086774 00D60180 */ .word func_8001D600
    /* 76F78 80086778 24D60180 */ .word SceneNode__LoadVerts
    /* 76F7C 8008677C A4D60180 */ .word func_8001D6A4
    /* 76F80 80086780 24AB0480 */ .word StageRenderer__FlushPending
    /* 76F84 80086784 88AB0480 */ .word StageRenderer__HandleCommand
    /* 76F88 80086788 14D70180 */ .word func_8001D714
    /* 76F8C 8008678C 50D90180 */ .word func_8001D950
    /* 76F90 80086790 28DA0180 */ .word func_8001DA28
    /* 76F94 80086794 F4DD0180 */ .word func_8001DDF4
    /* 76F98 80086798 9CE40180 */ .word func_8001E49C
    /* 76F9C 8008679C A4E40180 */ .word func_8001E4A4
    /* 76FA0 800867A0 28280480 */ .word func_80042828
    /* 76FA4 800867A4 3C280480 */ .word func_8004283C
    /* 76FA8 800867A8 D0AB0480 */ .word StageRenderer__MethodC0
    /* 76FAC 800867AC F8AC0480 */ .word StageRenderer__MethodC4
    /* 76FB0 800867B0 C4AD0480 */ .word StageRenderer__SetValues60
    /* 76FB4 800867B4 D0AD0480 */ .word StageRenderer__SetFieldE8
    /* 76FB8 800867B8 D8AD0480 */ .word StageRenderer__MethodD0
    /* 76FBC 800867BC 1CB30480 */ .word StageRenderer__GetField1C0
    /* 76FC0 800867C0 24B30480 */ .word StageRenderer__Nop
    /* 76FC4 800867C4 2CB30480 */ .word StageRenderer__SetTexturePageSize
    /* 76FC8 800867C8 44B30480 */ .word StageRenderer__SetTileScale
    /* 76FCC 800867CC 8CB30480 */ .word StageRenderer__MethodE4
    /* 76FD0 800867D0 18B40480 */ .word StageRenderer__GetTileAt
    /* 76FD4 800867D4 70B50480 */ .word StageRenderer__Activate
    /* 76FD8 800867D8 7CB50480 */ .word StageRenderer__Deactivate
    /* 76FDC 800867DC BCB50480 */ .word StageRenderer__MethodF4
    /* 76FE0 800867E0 00B70480 */ .word StageRenderer__UpdateChunks
    /* 76FE4 800867E4 3CBB0480 */ .word StageRenderer__RefreshChunkSet
    /* 76FE8 800867E8 14BD0480 */ .word StageRenderer__Method100
    /* 76FEC 800867EC 54BE0480 */ .word StageRenderer__LoadModel
    /* 76FF0 800867F0 ACC00480 */ .word StageRenderer__Method108
    /* 76FF4 800867F4 58C10480 */ .word StageRenderer__Method10C
    /* 76FF8 800867F8 C0C10480 */ .word StageRenderer__Method110
    /* 76FFC 800867FC F0C30480 */ .word StageRenderer__GetCallbackEntityTile
    /* 77000 80086800 34C40480 */ .word StageRenderer__FindSubRendererById
    /* 77004 80086804 70C40480 */ .word StageRenderer__Method11C
    /* 77008 80086808 88C50480 */ .word StageRenderer__FindSubRendererIndex
    /* 7700C 8008680C D0C50480 */ .word StageRenderer__FindActiveSubRenderer
    /* 77010 80086810 20C60480 */ .word StageRenderer__RefreshScroll
    /* 77014 80086814 A4AE0480 */ .word StageRenderer__SetupScroll
    /* 77018 80086818 A8CF0480 */ .word StageRenderer__GetField1CC
    /* 7701C 8008681C B0CF0480 */ .word StageRenderer__SetField1DC
    /* 77020 80086820 B8CF0480 */ .word StageRenderer__Method138
    /* 77024 80086824 28D00480 */ .word StageRenderer__TickCountdown
    /* 77028 80086828 88D00480 */ .word StageRenderer__CancelCountdown
enddlabel gVtable_StageRenderer

nonmatching D_8008682C

dlabel D_8008682C
    /* 7702C 8008682C 00000000 */ .word 0x00000000
    /* 77030 80086830 00000000 */ .word 0x00000000
    /* 77034 80086834 00000000 */ .word 0x00000000
enddlabel D_8008682C

nonmatching gStageBoundsTable

dlabel gStageBoundsTable
    /* 77038 80086838 0060FFFF */ .word 0xFFFF6000
    /* 7703C 8008683C 00000000 */ .word 0x00000000
    /* 77040 80086840 0010FFFF */ .word 0xFFFF1000
    /* 77044 80086844 00000000 */ .word 0x00000000
    /* 77048 80086848 00000000 */ .word 0x00000000
    /* 7704C 8008684C 0010FFFF */ .word 0xFFFF1000
    /* 77050 80086850 0010FFFF */ .word 0xFFFF1000
    /* 77054 80086854 00000000 */ .word 0x00000000
    /* 77058 80086858 00B0FFFF */ .word 0xFFFFB000
    /* 7705C 8008685C 00B0FFFF */ .word 0xFFFFB000
    /* 77060 80086860 00000000 */ .word 0x00000000
    /* 77064 80086864 00B0FFFF */ .word 0xFFFFB000
    /* 77068 80086868 00500000 */ .word 0x00005000
    /* 7706C 8008686C 00000000 */ .word 0x00000000
    /* 77070 80086870 00B0FFFF */ .word 0xFFFFB000
    /* 77074 80086874 0060FFFF */ .word 0xFFFF6000
    /* 77078 80086878 00000000 */ .word 0x00000000
    /* 7707C 8008687C 00500000 */ .word 0x00005000
    /* 77080 80086880 00000000 */ .word 0x00000000
    /* 77084 80086884 00000000 */ .word 0x00000000
    /* 77088 80086888 00500000 */ .word 0x00005000
enddlabel gStageBoundsTable

nonmatching D_8008688C

dlabel D_8008688C
    /* 7708C 8008688C 01000000 */ .word 0x00000001
    /* 77090 80086890 02000000 */ .word 0x00000002
    /* 77094 80086894 04000000 */ .word 0x00000004
    /* 77098 80086898 08000000 */ .word 0x00000008
    /* 7709C 8008689C 10000000 */ .word 0x00000010
    /* 770A0 800868A0 20000000 */ .word 0x00000020
    /* 770A4 800868A4 40000000 */ .word 0x00000040
enddlabel D_8008688C

nonmatching D_800868A8

dlabel D_800868A8
    /* 770A8 800868A8 FFFFFFFF */ .word 0xFFFFFFFF
    /* 770AC 800868AC FFFFFFFF */ .word 0xFFFFFFFF
    /* 770B0 800868B0 00000000 */ .word 0x00000000
    /* 770B4 800868B4 FFFFFFFF */ .word 0xFFFFFFFF
    /* 770B8 800868B8 00000000 */ .word 0x00000000
    /* 770BC 800868BC 01000000 */ .word 0x00000001
    /* 770C0 800868C0 00000000 */ .word 0x00000000
    /* 770C4 800868C4 FFFFFFFF */ .word 0xFFFFFFFF
    /* 770C8 800868C8 FFFFFFFF */ .word 0xFFFFFFFF
    /* 770CC 800868CC 00000000 */ .word 0x00000000
    /* 770D0 800868D0 00000000 */ .word 0x00000000
    /* 770D4 800868D4 00000000 */ .word 0x00000000
    /* 770D8 800868D8 00000000 */ .word 0x00000000
    /* 770DC 800868DC 01000000 */ .word 0x00000001
    /* 770E0 800868E0 01000000 */ .word 0x00000001
    /* 770E4 800868E4 01000000 */ .word 0x00000001
    /* 770E8 800868E8 FFFFFFFF */ .word 0xFFFFFFFF
    /* 770EC 800868EC 00000000 */ .word 0x00000000
    /* 770F0 800868F0 01000000 */ .word 0x00000001
    /* 770F4 800868F4 00000000 */ .word 0x00000000
    /* 770F8 800868F8 01000000 */ .word 0x00000001
enddlabel D_800868A8

nonmatching D_800868FC

dlabel D_800868FC
    /* 770FC 800868FC 01020300 */ .word 0x00030201
    /* 77100 80086900 04050600 */ .word 0x00060504
enddlabel D_800868FC

nonmatching D_80086904

dlabel D_80086904
    /* 77104 80086904 00010101 */ .word 0x01010100
    /* 77108 80086908 02010301 */ .word 0x01030102
    /* 7710C 8008690C 04010501 */ .word 0x01050104
    /* 77110 80086910 06010000 */ .word 0x00000106
enddlabel D_80086904

nonmatching D_80086914

dlabel D_80086914
    /* 77114 80086914 03000400 */ .word 0x00040003
    /* 77118 80086918 05000600 */ .word 0x00060005
    /* 7711C 8008691C 00010101 */ .word 0x01010100
    /* 77120 80086920 02010000 */ .word 0x00000102
enddlabel D_80086914

nonmatching D_80086924

dlabel D_80086924
    /* 77124 80086924 02000300 */ .word 0x00030002
    /* 77128 80086928 00010500 */ .word 0x00050100
    /* 7712C 8008692C 06000101 */ .word 0x01010006
    /* 77130 80086930 04010000 */ .word 0x00000104
enddlabel D_80086924

nonmatching D_80086934

dlabel D_80086934
    /* 77134 80086934 01000001 */ .word 0x01000001
    /* 77138 80086938 03000400 */ .word 0x00040003
    /* 7713C 8008693C 02010600 */ .word 0x00060102
    /* 77140 80086940 05010000 */ .word 0x00000105
enddlabel D_80086934

nonmatching D_80086944

dlabel D_80086944
    /* 77144 80086944 01010000 */ .word 0x00000101
    /* 77148 80086948 04010200 */ .word 0x00020104
    /* 7714C 8008694C 03000601 */ .word 0x01060003
    /* 77150 80086950 05000000 */ .word 0x00000005
enddlabel D_80086944

nonmatching D_80086954

dlabel D_80086954
    /* 77154 80086954 02010501 */ .word 0x01050102
    /* 77158 80086958 00000100 */ .word 0x00010000
    /* 7715C 8008695C 06010300 */ .word 0x00030106
    /* 77160 80086960 04000000 */ .word 0x00000004
enddlabel D_80086954

nonmatching D_80086964

dlabel D_80086964
    /* 77164 80086964 04010501 */ .word 0x01050104
    /* 77168 80086968 06010000 */ .word 0x00000106
    /* 7716C 8008696C 01000200 */ .word 0x00020001
    /* 77170 80086970 03000000 */ .word 0x00000003
enddlabel D_80086964

nonmatching D_80086974

dlabel D_80086974
    /* 77174 80086974 00000000 */ .word 0x00000000
    /* 77178 80086978 14690880 */ .word D_80086914
    /* 7717C 8008697C 24690880 */ .word D_80086924
    /* 77180 80086980 34690880 */ .word D_80086934
    /* 77184 80086984 44690880 */ .word D_80086944
    /* 77188 80086988 54690880 */ .word D_80086954
    /* 7718C 8008698C 64690880 */ .word D_80086964
enddlabel D_80086974

nonmatching D_80086990

dlabel D_80086990
    /* 77190 80086990 FFFFFFFF */ .word 0xFFFFFFFF
    /* 77194 80086994 00000000 */ .word 0x00000000
    /* 77198 80086998 14001400 */ .word 0x00140014
enddlabel D_80086990

nonmatching D_8008699C

dlabel D_8008699C
    /* 7719C 8008699C 00000100 */ .word 0x00010000
    /* 771A0 800869A0 01004000 */ .word 0x00400001
    /* 771A4 800869A4 00000100 */ .word 0x00010000
enddlabel D_8008699C

nonmatching D_800869A8

dlabel D_800869A8
    /* 771A8 800869A8 00000100 */ .word 0x00010000
    /* 771AC 800869AC 01000400 */ .word 0x00040001
    /* 771B0 800869B0 00000100 */ .word 0x00010000
enddlabel D_800869A8

nonmatching D_800869B4

dlabel D_800869B4
    /* 771B4 800869B4 00000100 */ .word 0x00010000
    /* 771B8 800869B8 FFFF4000 */ .word 0x0040FFFF
    /* 771BC 800869BC 00000100 */ .word 0x00010000
enddlabel D_800869B4

nonmatching D_800869C0

dlabel D_800869C0
    /* 771C0 800869C0 00000100 */ .word 0x00010000
    /* 771C4 800869C4 FFFF0400 */ .word 0x0004FFFF
    /* 771C8 800869C8 00000100 */ .word 0x00010000
enddlabel D_800869C0

nonmatching gVectorOne

dlabel gVectorOne
    /* 771CC 800869CC 01000100 */ .word 0x00010001
    /* 771D0 800869D0 01000100 */ .word 0x00010001
    /* 771D4 800869D4 01000100 */ .word 0x00010001
enddlabel gVectorOne

nonmatching gVtable_Camera

dlabel gVtable_Camera
    /* 771D8 800869D8 17000000 */ .word 0x00000017
    /* 771DC 800869DC B07E0180 */ .word BasicClass__Delete
    /* 771E0 800869E0 A4D20480 */ .word Camera__Constructor
    /* 771E4 800869E4 CCE60380 */ .word ModelObj__Destroy
    /* 771E8 800869E8 70E70380 */ .word ModelObj__HandleMessage
    /* 771EC 800869EC F4E70380 */ .word func_8003E7F4
    /* 771F0 800869F0 74E80380 */ .word ModelObj__ResetLinks
    /* 771F4 800869F4 BC800180 */ .word BasicClass__NextChildA
    /* 771F8 800869F8 FC800180 */ .word BasicClass__AddChildB
    /* 771FC 800869FC 1C810180 */ .word BasicClass__RemoveChildB
    /* 77200 80086A00 3C810180 */ .word BasicClass__ClearChildrenB
    /* 77204 80086A04 6C810180 */ .word BasicClass__NextChildB
    /* 77208 80086A08 CC820180 */ .word BasicClass__func_182cc
    /* 7720C 80086A0C 50830180 */ .word BasicClass__Nop
    /* 77210 80086A10 B8E80380 */ .word func_8003E8B8
    /* 77214 80086A14 00000000 */ .word 0x00000000
    /* 77218 80086A18 F8D20480 */ .word Camera__Nop
    /* 7721C 80086A1C 0CEA0380 */ .word func_8003EA0C
    /* 77220 80086A20 24EA0380 */ .word ModelObj__Set3C
    /* 77224 80086A24 2CEA0380 */ .word func_8003EA2C
    /* 77228 80086A28 48EA0380 */ .word func_8003EA48
    /* 7722C 80086A2C 64EA0380 */ .word ModelObj__Set40
    /* 77230 80086A30 6CEA0380 */ .word ModelObj__Null1
    /* 77234 80086A34 74EA0380 */ .word ModelObj__Null2
    /* 77238 80086A38 7CEA0380 */ .word ModelObj__Set54
    /* 7723C 80086A3C 84EA0380 */ .word ModelObj__SetColorA
    /* 77240 80086A40 A4EA0380 */ .word ModelObj__SetColorB
    /* 77244 80086A44 C4EA0380 */ .word ModelObj__Set60
    /* 77248 80086A48 CCEA0380 */ .word ModelObj__LookAt
    /* 7724C 80086A4C 84EB0380 */ .word ModelObj__ApplyStoredMsg
    /* 77250 80086A50 C4EB0380 */ .word ModelObj__SetPosition
    /* 77254 80086A54 F8EB0380 */ .word ModelObj__SetRotation
    /* 77258 80086A58 2CEC0380 */ .word ModelObj__SetAspect
    /* 7725C 80086A5C C0EC0380 */ .word ModelObj__Null3
    /* 77260 80086A60 C8EC0380 */ .word ModelObj__Null4
    /* 77264 80086A64 D0EC0380 */ .word ModelObj__CreateTexWindow
    /* 77268 80086A68 F4ED0380 */ .word ModelObj__FreeTexWindow
    /* 7726C 80086A6C 40EE0380 */ .word ModelObj__TickCounter90
    /* 77270 80086A70 88EE0380 */ .word ModelObj__OnMsg2CallA4
    /* 77274 80086A74 00D30480 */ .word Camera__ConditionalUpdate
    /* 77278 80086A78 64200180 */ .word func_80012064
    /* 7727C 80086A7C 4CF00380 */ .word ModelObj__Draw
    /* 77280 80086A80 A8F10380 */ .word ModelObj__SetTexture
    /* 77284 80086A84 30F20380 */ .word ModelObj__GetTexture
    /* 77288 80086A88 3CF20380 */ .word ModelObj__SetB4
    /* 7728C 80086A8C 44F20380 */ .word ModelObj__SetB8
    /* 77290 80086A90 5CD30480 */ .word Camera__NopB8
    /* 77294 80086A94 64D30480 */ .word Camera__NopBC
    /* 77298 80086A98 6CD30480 */ .word Camera__NopC0
    /* 7729C 80086A9C 74D30480 */ .word Camera__NopC4
enddlabel gVtable_Camera

.align 2
nonmatching gVtable_CoordSys

dlabel gVtable_CoordSys
    /* 772A0 80086AA0 */ .asciz "$"
    /* 24000000 */
.align 2
    /* 772A4 80086AA4 B07E0180 */ .word BasicClass__Delete
    /* 772A8 80086AA8 DCD30480 */ .word CoordSys__Constructor
    /* 772AC 80086AAC A4CB0180 */ .word SceneNode__Destructor
    /* 772B0 80086AB0 48CC0180 */ .word SceneNode__HandleMessage
    /* 772B4 80086AB4 B4CC0180 */ .word func_8001CCB4
    /* 772B8 80086AB8 20CD0180 */ .word SceneNode__Reset
    /* 772BC 80086ABC BC800180 */ .word BasicClass__NextChildA
    /* 772C0 80086AC0 FC800180 */ .word BasicClass__AddChildB
    /* 772C4 80086AC4 1C810180 */ .word BasicClass__RemoveChildB
    /* 772C8 80086AC8 3C810180 */ .word BasicClass__ClearChildrenB
    /* 772CC 80086ACC 6C810180 */ .word BasicClass__NextChildB
    /* 772D0 80086AD0 CC820180 */ .word BasicClass__func_182cc
    /* 772D4 80086AD4 50830180 */ .word BasicClass__Nop
    /* 772D8 80086AD8 60CD0180 */ .word SceneNode__DispatchMessage
    /* 772DC 80086ADC 00000000 */ .word 0x00000000
    /* 772E0 80086AE0 2CD40480 */ .word CoordSys__Nop
    /* 772E4 80086AE4 B4CE0180 */ .word func_8001CEB4
    /* 772E8 80086AE8 08D00180 */ .word func_8001D008
    /* 772EC 80086AEC ECD00180 */ .word SceneNode__AttachChild
    /* 772F0 80086AF0 A4D10180 */ .word SceneNode__DetachChild
    /* 772F4 80086AF4 04D20180 */ .word SceneNode__UpdateChildren
    /* 772F8 80086AF8 80D20180 */ .word SceneNode__FindChild
    /* 772FC 80086AFC 3CD30180 */ .word func_8001D33C
    /* 77300 80086B00 44D30180 */ .word SceneNode__SetInvisible
    /* 77304 80086B04 74D30180 */ .word SceneNode__SetAttrBit30
    /* 77308 80086B08 A0D30180 */ .word SceneNode__SetDrawMode
    /* 7730C 80086B0C CCD30180 */ .word SceneNode__SetAttrBit6
    /* 77310 80086B10 F8D30180 */ .word SceneNode__SetAttrField3
    /* 77314 80086B14 24D40180 */ .word SceneNode__SetAttrField0
    /* 77318 80086B18 50D40180 */ .word SceneNode__SetAttrBit7
    /* 7731C 80086B1C 80D40180 */ .word SceneNode__SetAttrField9
    /* 77320 80086B20 ACD40180 */ .word SceneNode__SetAttrBit8
    /* 77324 80086B24 DCD40180 */ .word func_8001D4DC
    /* 77328 80086B28 68D50180 */ .word func_8001D568
    /* 7732C 80086B2C 00D60180 */ .word func_8001D600
    /* 77330 80086B30 24D60180 */ .word SceneNode__LoadVerts
    /* 77334 80086B34 A4D60180 */ .word func_8001D6A4
    /* 77338 80086B38 ACD60180 */ .word func_8001D6AC
    /* 7733C 80086B3C 34D40480 */ .word CoordSys__HandleCommand
    /* 77340 80086B40 14D70180 */ .word func_8001D714
    /* 77344 80086B44 50D90180 */ .word func_8001D950
    /* 77348 80086B48 28DA0180 */ .word func_8001DA28
    /* 7734C 80086B4C F4DD0180 */ .word func_8001DDF4
    /* 77350 80086B50 9CE40180 */ .word func_8001E49C
    /* 77354 80086B54 A4E40180 */ .word func_8001E4A4
    /* 77358 80086B58 7CD40480 */ .word CoordSys__MethodC0
    /* 7735C 80086B5C 00D50480 */ .word Identity
enddlabel gVtable_CoordSys

nonmatching gVtable_TitleScreen

dlabel gVtable_TitleScreen
    /* 77360 80086B60 30F10100 */ .word 0x0001F130
    /* 77364 80086B64 B07E0180 */ .word BasicClass__Delete
    /* 77368 80086B68 78D50480 */ .word TitleScreen__Constructor
    /* 7736C 80086B6C 04D70480 */ .word TitleScreen__Destructor
    /* 77370 80086B70 987F0180 */ .word BasicClass__AdoptChild
    /* 77374 80086B74 F07F0180 */ .word BasicClass__func_17ff0
    /* 77378 80086B78 40800180 */ .word BasicClass__func_18040
    /* 7737C 80086B7C BC800180 */ .word BasicClass__NextChildA
    /* 77380 80086B80 FC800180 */ .word BasicClass__AddChildB
    /* 77384 80086B84 1C810180 */ .word BasicClass__RemoveChildB
    /* 77388 80086B88 3C810180 */ .word BasicClass__ClearChildrenB
    /* 7738C 80086B8C 6C810180 */ .word BasicClass__NextChildB
    /* 77390 80086B90 CC820180 */ .word BasicClass__func_182cc
    /* 77394 80086B94 50830180 */ .word BasicClass__Nop
    /* 77398 80086B98 88D70480 */ .word TitleScreen__HandleEvent
    /* 7739C 80086B9C 00000000 */ .word 0x00000000
    /* 773A0 80086BA0 14D80480 */ .word TitleScreen__LoadTitle
    /* 773A4 80086BA4 DCC10380 */ .word AnimEffect__StartGetState
    /* 773A8 80086BA8 80E20380 */ .word func_8003E280
    /* 773AC 80086BAC 38C20380 */ .word func_8003C238
    /* 773B0 80086BB0 98D80480 */ .word TitleScreen__InitRects
    /* 773B4 80086BB4 18E40380 */ .word Effect__HandleChildMsg
    /* 773B8 80086BB8 8CC40380 */ .word AnimEffect__HandleMessage
    /* 773BC 80086BBC 1CC50380 */ .word func_8003C51C
    /* 773C0 80086BC0 0CD90480 */ .word TitleScreen__SetState
    /* 773C4 80086BC4 38E50380 */ .word Effect__ResetAndPause
    /* 773C8 80086BC8 78E50380 */ .word Effect__ResetAndResume
    /* 773CC 80086BCC 94C70380 */ .word AnimEffect__SetFrameDuration
    /* 773D0 80086BD0 B4C70380 */ .word AnimEffect__SetScale
    /* 773D4 80086BD4 F4C70380 */ .word AnimEffect__TriggerAnimA
    /* 773D8 80086BD8 58C80380 */ .word AnimEffect__TriggerAnimB
    /* 773DC 80086BDC D0C80380 */ .word AnimEffect__TriggerAnimC
    /* 773E0 80086BE0 44C90380 */ .word AnimEffect__DoModeAction1
    /* 773E4 80086BE4 B0C90380 */ .word AnimEffect__DoModeAction2
    /* 773E8 80086BE8 00000000 */ .word 0x00000000
    /* 773EC 80086BEC 00000000 */ .word 0x00000000
    /* 773F0 80086BF0 D4D90480 */ .word TitleScreen__Method90
    /* 773F4 80086BF4 BCDA0480 */ .word TitleScreen__Method94
    /* 773F8 80086BF8 ECCA0380 */ .word AnimEffect__SetCallback
    /* 773FC 80086BFC F8CA0380 */ .word AnimEffect__SetModeA
    /* 77400 80086C00 30CB0380 */ .word AnimEffect__SetModeB
    /* 77404 80086C04 68CB0380 */ .word AnimEffect__SetColors
    /* 77408 80086C08 B8CB0380 */ .word AnimEffect__SetFadeSpeed
    /* 7740C 80086C0C C0CB0380 */ .word AnimEffect__RunCondition
    /* 77410 80086C10 2CCC0380 */ .word AnimEffect__FadeInStep
    /* 77414 80086C14 00000000 */ .word 0x00000000
    /* 77418 80086C18 00000000 */ .word 0x00000000
    /* 7741C 80086C1C 00000000 */ .word 0x00000000
    /* 77420 80086C20 DCCC0380 */ .word func_8003CCDC
    /* 77424 80086C24 48CD0380 */ .word AnimEffect__FadeOutStep
    /* 77428 80086C28 00000000 */ .word 0x00000000
    /* 7742C 80086C2C 00000000 */ .word 0x00000000
    /* 77430 80086C30 00000000 */ .word 0x00000000
    /* 77434 80086C34 E0CD0380 */ .word func_8003CDE0
    /* 77438 80086C38 18DB0480 */ .word TitleScreen__BuildMenu
    /* 7743C 80086C3C 08DC0480 */ .word TitleScreen__MethodDC
    /* 77440 80086C40 64DC0480 */ .word TitleScreen__MethodE0
    /* 77444 80086C44 D0DC0480 */ .word TitleScreen__MethodE4
    /* 77448 80086C48 B0D30380 */ .word func_8003D3B0
    /* 7744C 80086C4C 44D40380 */ .word func_8003D444
    /* 77450 80086C50 DCD40380 */ .word AnimEffect__SetFrame
    /* 77454 80086C54 C0D50380 */ .word AnimEffect__GetFrame
    /* 77458 80086C58 CCD50380 */ .word AnimEffect__AddFrameSet
    /* 7745C 80086C5C D4D60380 */ .word AnimEffect__FreeFrameSet
    /* 77460 80086C60 3CD70380 */ .word AnimEffect__RenderFrame
    /* 77464 80086C64 80D90380 */ .word AnimEffect__ForEachFrameSprite
    /* 77468 80086C68 10DA0380 */ .word func_8003DA10
    /* 7746C 80086C6C D4DA0380 */ .word func_8003DAD4
    /* 77470 80086C70 ACDC0380 */ .word AnimEffect__AdvanceFrame
    /* 77474 80086C74 C8DD0380 */ .word func_8003DDC8
    /* 77478 80086C78 30DE0380 */ .word func_8003DE30
    /* 7747C 80086C7C 9CDE0380 */ .word func_8003DE9C
    /* 77480 80086C80 A0DF0380 */ .word AnimEffect__GetFrameEntryId
    /* 77484 80086C84 08DE0480 */ .word TitleScreen__Method124
    /* 77488 80086C88 64DF0480 */ .word TitleScreen__OpenSaveMenu
    /* 7748C 80086C8C 54E00480 */ .word TitleScreen__CloseSaveMenu
    /* 77490 80086C90 E4E00480 */ .word TitleScreen__Method130
    /* 77494 80086C94 C4E10480 */ .word TitleScreen__Method134
    /* 77498 80086C98 30E20480 */ .word TitleScreen__Method138
enddlabel gVtable_TitleScreen

nonmatching D_80086C9C

dlabel D_80086C9C
    /* 7749C 80086C9C 88A90880 */ .word D_8008A988
    /* 774A0 80086CA0 84A90880 */ .word D_8008A984
    /* 774A4 80086CA4 00000000 */ .word 0x00000000
enddlabel D_80086C9C

nonmatching D_80086CA8

dlabel D_80086CA8
    /* 774A8 80086CA8 00000000 */ .word 0x00000000
    /* 774AC 80086CAC 00000000 */ .word 0x00000000
    /* 774B0 80086CB0 80800000 */ .word 0x00008080
    /* 774B4 80086CB4 00000000 */ .word 0x00000000
    /* 774B8 80086CB8 35000000 */ .word 0x00000035
    /* 774BC 80086CBC 39000000 */ .word 0x00000039
    /* 774C0 80086CC0 9C6C0880 */ .word D_80086C9C
enddlabel D_80086CA8

nonmatching D_80086CC4

dlabel D_80086CC4
    /* 774C4 80086CC4 00000000 */ .word 0x00000000
    /* 774C8 80086CC8 00000000 */ .word 0x00000000
    /* 774CC 80086CCC 00000000 */ .word 0x00000000
    /* 774D0 80086CD0 00000000 */ .word 0x00000000
    /* 774D4 80086CD4 00000000 */ .word 0x00000000
    /* 774D8 80086CD8 A86C0880 */ .word D_80086CA8
enddlabel D_80086CC4

nonmatching D_80086CDC

dlabel D_80086CDC
    /* 774DC 80086CDC 00000000 */ .word 0x00000000
    /* 774E0 80086CE0 01000000 */ .word 0x00000001
    /* 774E4 80086CE4 00000000 */ .word 0x00000000
    /* 774E8 80086CE8 00000000 */ .word 0x00000000
    /* 774EC 80086CEC 00000000 */ .word 0x00000000
    /* 774F0 80086CF0 00000000 */ .word 0x00000000
    /* 774F4 80086CF4 00000000 */ .word 0x00000000
enddlabel D_80086CDC

nonmatching D_80086CF8

dlabel D_80086CF8
    /* 774F8 80086CF8 ACA90880 */ .word D_8008A9AC
    /* 774FC 80086CFC 34140180 */ .word D_80011434
    /* 77500 80086D00 A4A90880 */ .word D_8008A9A4
    /* 77504 80086D04 9CA90880 */ .word D_8008A99C
    /* 77508 80086D08 94A90880 */ .word D_8008A994
    /* 7750C 80086D0C 8CA90880 */ .word D_8008A98C
    /* 77510 80086D10 00000000 */ .word 0x00000000
enddlabel D_80086CF8

nonmatching D_80086D14

dlabel D_80086D14
    /* 77514 80086D14 08000000 */ .word 0x00000008
    /* 77518 80086D18 FDFFFFFF */ .word 0xFFFFFFFD
    /* 7751C 80086D1C 08000000 */ .word 0x00000008
    /* 77520 80086D20 09000000 */ .word 0x00000009
    /* 77524 80086D24 08000000 */ .word 0x00000008
    /* 77528 80086D28 15000000 */ .word 0x00000015
    /* 7752C 80086D2C 08000000 */ .word 0x00000008
    /* 77530 80086D30 21000000 */ .word 0x00000021
    /* 77534 80086D34 08000000 */ .word 0x00000008
    /* 77538 80086D38 2D000000 */ .word 0x0000002D
    /* 7753C 80086D3C 08000000 */ .word 0x00000008
    /* 77540 80086D40 39000000 */ .word 0x00000039
enddlabel D_80086D14

nonmatching D_80086D44

dlabel D_80086D44
    /* 77544 80086D44 40140180 */ .word 0x80011440
    /* 77548 80086D48 00000000 */ .word 0x00000000
    /* 7754C 80086D4C 00000000 */ .word 0x00000000
    /* 77550 80086D50 00000000 */ .word 0x00000000
    /* 77554 80086D54 50505080 */ .word 0x80505050
    /* 77558 80086D58 80000000 */ .word 0x00000080
    /* 7755C 80086D5C DC6C0880 */ .word D_80086CDC
    /* 77560 80086D60 F86C0880 */ .word D_80086CF8
    /* 77564 80086D64 146D0880 */ .word D_80086D14
    /* 77568 80086D68 C46C0880 */ .word D_80086CC4
enddlabel D_80086D44

nonmatching D_80086D6C

dlabel D_80086D6C
    /* 7756C 80086D6C 0CAA0880 */ .word D_8008AA0C
    /* 77570 80086D70 08AA0880 */ .word D_8008AA08
    /* 77574 80086D74 04AA0880 */ .word D_8008AA04
    /* 77578 80086D78 00AA0880 */ .word D_8008AA00
    /* 7757C 80086D7C FCA90880 */ .word D_8008A9FC
    /* 77580 80086D80 F8A90880 */ .word D_8008A9F8
    /* 77584 80086D84 F4A90880 */ .word D_8008A9F4
    /* 77588 80086D88 F0A90880 */ .word D_8008A9F0
    /* 7758C 80086D8C ECA90880 */ .word D_8008A9EC
    /* 77590 80086D90 E8A90880 */ .word D_8008A9E8
    /* 77594 80086D94 E4A90880 */ .word D_8008A9E4
    /* 77598 80086D98 E0A90880 */ .word D_8008A9E0
    /* 7759C 80086D9C DCA90880 */ .word D_8008A9DC
    /* 775A0 80086DA0 D8A90880 */ .word D_8008A9D8
    /* 775A4 80086DA4 D4A90880 */ .word D_8008A9D4
    /* 775A8 80086DA8 00000000 */ .word 0x00000000
enddlabel D_80086D6C

nonmatching D_80086DAC

dlabel D_80086DAC
    /* 775AC 80086DAC 00000000 */ .word 0x00000000
    /* 775B0 80086DB0 40010000 */ .word 0x00000140
    /* 775B4 80086DB4 F0000000 */ .word 0x000000F0
    /* 775B8 80086DB8 0000F000 */ .word 0x00F00000
    /* 775BC 80086DBC 40010000 */ .word 0x00000140
    /* 775C0 80086DC0 F0000000 */ .word 0x000000F0
enddlabel D_80086DAC

nonmatching gVtable_TextPanel

dlabel gVtable_TextPanel
    /* 775C4 80086DC4 0B000000 */ .word 0x0000000B
    /* 775C8 80086DC8 B07E0180 */ .word BasicClass__Delete
    /* 775CC 80086DCC 4CE30480 */ .word TextPanel__Constructor
    /* 775D0 80086DD0 0CE40480 */ .word TextPanel__Destructor
    /* 775D4 80086DD4 44E40480 */ .word TextPanel__Method10
    /* 775D8 80086DD8 E8E40480 */ .word TextPanel__Method14
    /* 775DC 80086DDC 88E50480 */ .word TextPanel__Reset
    /* 775E0 80086DE0 BC800180 */ .word BasicClass__NextChildA
    /* 775E4 80086DE4 FC800180 */ .word BasicClass__AddChildB
    /* 775E8 80086DE8 1C810180 */ .word BasicClass__RemoveChildB
    /* 775EC 80086DEC 3C810180 */ .word BasicClass__ClearChildrenB
    /* 775F0 80086DF0 6C810180 */ .word BasicClass__NextChildB
    /* 775F4 80086DF4 CC820180 */ .word BasicClass__func_182cc
    /* 775F8 80086DF8 50830180 */ .word BasicClass__Nop
    /* 775FC 80086DFC 04FB0480 */ .word TextPanel__Method38
    /* 77600 80086E00 00000000 */ .word 0x00000000
    /* 77604 80086E04 D4E50480 */ .word TextPanel__SetLineCount
    /* 77608 80086E08 E4E50480 */ .word TextPanel__LoadFont
    /* 7760C 80086E0C 78E60480 */ .word TextPanel__InitDraw
    /* 77610 80086E10 B8E60480 */ .word TextPanel__Print
    /* 77614 80086E14 40E90480 */ .word TextPanel__SetText
    /* 77618 80086E18 ACE90480 */ .word TextPanel__AllocString
    /* 7761C 80086E1C DCEA0480 */ .word TextPanel__Method58
    /* 77620 80086E20 88EB0480 */ .word TextPanel__Method5C
    /* 77624 80086E24 5CEC0480 */ .word TextPanel__Method60
    /* 77628 80086E28 40ED0480 */ .word TextPanel__Method64
    /* 7762C 80086E2C A0EE0480 */ .word TextPanel__Method68
    /* 77630 80086E30 5CF50480 */ .word TextPanel__Method6C
    /* 77634 80086E34 DCF50480 */ .word TextPanel__Method70
    /* 77638 80086E38 38F60480 */ .word TextPanel__ReallocLines
    /* 7763C 80086E3C A4F80480 */ .word TextPanel__Method78
    /* 77640 80086E40 E4FB0480 */ .word TextPanel__Method7C
    /* 77644 80086E44 24FE0480 */ .word TextPanel__LoadFontFile
    /* 77648 80086E48 40FF0480 */ .word TextPanel__Method84
    /* 7764C 80086E4C 90FF0480 */ .word TextPanel__Method88
    /* 77650 80086E50 F4FF0480 */ .word TextPanel__PlaySfx
    /* 77654 80086E54 34000580 */ .word TextPanel__Method90
    /* 77658 80086E58 F0010580 */ .word TextPanel__Method94
    /* 7765C 80086E5C 80020580 */ .word TextPanel__Method98
    /* 77660 80086E60 40030580 */ .word TextPanel__AttachListMenu
    /* 77664 80086E64 10040580 */ .word TextPanel__DetachListMenu
    /* 77668 80086E68 D0040580 */ .word TextPanel__MenuAction
    /* 7766C 80086E6C A8050580 */ .word TextPanel__AttachGridMenu
    /* 77670 80086E70 70060580 */ .word TextPanel__DetachGridMenu
    /* 77674 80086E74 30070580 */ .word TextPanel__MethodB0
enddlabel gVtable_TextPanel

nonmatching D_80086E78

dlabel D_80086E78
    /* 77678 80086E78 04000000 */ .word 0x00000004
    /* 7767C 80086E7C 00800000 */ .word 0x00008000
enddlabel D_80086E78

nonmatching D_80086E80

dlabel D_80086E80
    /* 77680 80086E80 00010000 */ .word 0x00000100
    /* 77684 80086E84 00200000 */ .word 0x00002000
    /* 77688 80086E88 24150180 */ .word 0x80011524
    /* 7768C 80086E8C 8CAA0880 */ .word D_8008AA8C
    /* 77690 80086E90 84AA0880 */ .word D_8008AA84
    /* 77694 80086E94 7CAA0880 */ .word D_8008AA7C
    /* 77698 80086E98 74AA0880 */ .word D_8008AA74
    /* 7769C 80086E9C 6CAA0880 */ .word D_8008AA6C
    /* 776A0 80086EA0 64AA0880 */ .word D_8008AA64
    /* 776A4 80086EA4 18150180 */ .word 0x80011518
    /* 776A8 80086EA8 5CAA0880 */ .word D_8008AA5C
    /* 776AC 80086EAC 54AA0880 */ .word D_8008AA54
    /* 776B0 80086EB0 4CAA0880 */ .word D_8008AA4C
    /* 776B4 80086EB4 0C150180 */ .word 0x8001150C
    /* 776B8 80086EB8 44AA0880 */ .word D_8008AA44
    /* 776BC 80086EBC 3CAA0880 */ .word D_8008AA3C
    /* 776C0 80086EC0 34AA0880 */ .word D_8008AA34
enddlabel D_80086E80

nonmatching D_80086EC4

dlabel D_80086EC4
    /* 776C4 80086EC4 00000000 */ .word 0x00000000
    /* 776C8 80086EC8 A0000000 */ .word 0x000000A0
    /* 776CC 80086ECC 78000000 */ .word 0x00000078
enddlabel D_80086EC4

nonmatching gVtable_ListMenu

dlabel gVtable_ListMenu
    /* 776D0 80086ED0 10000000 */ .word 0x00000010
    /* 776D4 80086ED4 B07E0180 */ .word BasicClass__Delete
    /* 776D8 80086ED8 140C0580 */ .word ListMenu__Constructor
    /* 776DC 80086EDC E80C0580 */ .word ListMenu__Destructor
    /* 776E0 80086EE0 300D0580 */ .word ListMenu__Method10
    /* 776E4 80086EE4 B40D0580 */ .word ListMenu__Method14
    /* 776E8 80086EE8 340E0580 */ .word ListMenu__Reset
    /* 776EC 80086EEC BC800180 */ .word BasicClass__NextChildA
    /* 776F0 80086EF0 FC800180 */ .word BasicClass__AddChildB
    /* 776F4 80086EF4 1C810180 */ .word BasicClass__RemoveChildB
    /* 776F8 80086EF8 3C810180 */ .word BasicClass__ClearChildrenB
    /* 776FC 80086EFC 6C810180 */ .word BasicClass__NextChildB
    /* 77700 80086F00 CC820180 */ .word BasicClass__func_182cc
    /* 77704 80086F04 50830180 */ .word BasicClass__Nop
    /* 77708 80086F08 780E0580 */ .word ListMenu__Method38
    /* 7770C 80086F0C 00000000 */ .word 0x00000000
    /* 77710 80086F10 280F0580 */ .word ListMenu__Setup
    /* 77714 80086F14 980F0580 */ .word ListMenu__LoadResources
    /* 77718 80086F18 74110580 */ .word ListMenu__FreeResources
    /* 7771C 80086F1C 00120580 */ .word ListMenu__Open
    /* 77720 80086F20 70120580 */ .word ListMenu__Close
    /* 77724 80086F24 C8120580 */ .word ListMenu__Method54
    /* 77728 80086F28 70130580 */ .word ListMenu__AutoAdvance
    /* 7772C 80086F2C D0130580 */ .word ListMenu__Method5C
    /* 77730 80086F30 1C160580 */ .word ListMenu__PlaySfx
    /* 77734 80086F34 00000000 */ .word 0x00000000
    /* 77738 80086F38 00000000 */ .word 0x00000000
    /* 7773C 80086F3C 00000000 */ .word 0x00000000
    /* 77740 80086F40 00000000 */ .word 0x00000000
    /* 77744 80086F44 00000000 */ .word 0x00000000
    /* 77748 80086F48 00000000 */ .word 0x00000000
    /* 7774C 80086F4C 00000000 */ .word 0x00000000
    /* 77750 80086F50 00000000 */ .word 0x00000000
    /* 77754 80086F54 00000000 */ .word 0x00000000
    /* 77758 80086F58 5C160580 */ .word ListMenu__CursorDown
    /* 7775C 80086F5C C0160580 */ .word ListMenu__CursorUp
    /* 77760 80086F60 20170580 */ .word ListMenu__NextPage
    /* 77764 80086F64 84170580 */ .word ListMenu__PrevPage
    /* 77768 80086F68 EC170580 */ .word ListMenu__ToggleFlag
    /* 7776C 80086F6C 14180580 */ .word ListMenu__CursorHome
    /* 77770 80086F70 58180580 */ .word ListMenu__RefreshAll
    /* 77774 80086F74 F4180580 */ .word ListMenu__MethodA4
    /* 77778 80086F78 98190580 */ .word ListMenu__MethodA8
enddlabel gVtable_ListMenu

nonmatching D_80086F7C

dlabel D_80086F7C
    /* 7777C 80086F7C 00000000 */ .word 0x00000000
    /* 77780 80086F80 E0000000 */ .word 0x000000E0
    /* 77784 80086F84 78000000 */ .word 0x00000078
enddlabel D_80086F7C

.align 2
nonmatching gVtable_GridMenu

dlabel gVtable_GridMenu
    /* 77788 80086F88 */ .asciz " "
    /* 20000000 */
.align 2
    /* 7778C 80086F8C B07E0180 */ .word BasicClass__Delete
    /* 77790 80086F90 C81A0580 */ .word GridMenu__Constructor
    /* 77794 80086F94 841C0580 */ .word GridMenu__Destructor
    /* 77798 80086F98 1C1D0580 */ .word GridMenu__Method18
    /* 7779C 80086F9C A01D0580 */ .word GridMenu__Method1C
    /* 777A0 80086FA0 201E0580 */ .word GridMenu__Reset
    /* 777A4 80086FA4 BC800180 */ .word BasicClass__NextChildA
    /* 777A8 80086FA8 FC800180 */ .word BasicClass__AddChildB
    /* 777AC 80086FAC 1C810180 */ .word BasicClass__RemoveChildB
    /* 777B0 80086FB0 3C810180 */ .word BasicClass__ClearChildrenB
    /* 777B4 80086FB4 6C810180 */ .word BasicClass__NextChildB
    /* 777B8 80086FB8 CC820180 */ .word BasicClass__func_182cc
    /* 777BC 80086FBC 50830180 */ .word BasicClass__Nop
    /* 777C0 80086FC0 641E0580 */ .word GridMenu__Method40
    /* 777C4 80086FC4 00000000 */ .word 0x00000000
    /* 777C8 80086FC8 141F0580 */ .word GridMenu__ClearCursor
    /* 777CC 80086FCC 241F0580 */ .word GridMenu__LoadResources
    /* 777D0 80086FD0 A0200580 */ .word GridMenu__FreeResources
    /* 777D4 80086FD4 10210580 */ .word GridMenu__Open
    /* 777D8 80086FD8 7C210580 */ .word GridMenu__Close
    /* 777DC 80086FDC D4210580 */ .word GridMenu__Method5C
    /* 777E0 80086FE0 7C220580 */ .word GridMenu__AutoAdvance
    /* 777E4 80086FE4 DC220580 */ .word GridMenu__HandleInput
    /* 777E8 80086FE8 F0230580 */ .word GridMenu__PlaySfx
    /* 777EC 80086FEC 00000000 */ .word 0x00000000
    /* 777F0 80086FF0 00000000 */ .word 0x00000000
    /* 777F4 80086FF4 00000000 */ .word 0x00000000
    /* 777F8 80086FF8 00000000 */ .word 0x00000000
    /* 777FC 80086FFC 00000000 */ .word 0x00000000
    /* 77800 80087000 00000000 */ .word 0x00000000
    /* 77804 80087004 30240580 */ .word GridMenu__Method84
    /* 77808 80087008 98240580 */ .word GridMenu__CursorPrev
    /* 7780C 8008700C F8240580 */ .word GridMenu__Method8C
    /* 77810 80087010 98250580 */ .word GridMenu__Method90
    /* 77814 80087014 44260580 */ .word GridMenu__DoSelect
    /* 77818 80087018 8C270580 */ .word GridMenu__Method98
    /* 7781C 8008701C 1C280580 */ .word GridMenu__DoAction
    /* 77820 80087020 582A0580 */ .word GridMenu__MethodA0
    /* 77824 80087024 542B0580 */ .word GridMenu__GetField28
enddlabel gVtable_GridMenu

nonmatching D_80087028

dlabel D_80087028
    /* 77828 80087028 00000000 */ .word 0x00000000
    /* 7782C 8008702C 00010000 */ .word 0x00000100
    /* 77830 80087030 A0000000 */ .word 0x000000A0
enddlabel D_80087028

nonmatching gVtable_DreamWorld

dlabel gVtable_DreamWorld
    /* 77834 80087034 30F20200 */ .word 0x0002F230
    /* 77838 80087038 B07E0180 */ .word BasicClass__Delete
    /* 7783C 8008703C 102C0580 */ .word DreamWorld__Constructor
    /* 77840 80087040 D82C0580 */ .word DreamWorld__Destructor
    /* 77844 80087044 987F0180 */ .word BasicClass__AdoptChild
    /* 77848 80087048 F07F0180 */ .word BasicClass__func_17ff0
    /* 7784C 8008704C 40800180 */ .word BasicClass__func_18040
    /* 77850 80087050 BC800180 */ .word BasicClass__NextChildA
    /* 77854 80087054 FC800180 */ .word BasicClass__AddChildB
    /* 77858 80087058 1C810180 */ .word BasicClass__RemoveChildB
    /* 7785C 8008705C 3C810180 */ .word BasicClass__ClearChildrenB
    /* 77860 80087060 6C810180 */ .word BasicClass__NextChildB
    /* 77864 80087064 CC820180 */ .word BasicClass__func_182cc
    /* 77868 80087068 50830180 */ .word BasicClass__Nop
    /* 7786C 8008706C 102D0580 */ .word DreamWorld__Method38
    /* 77870 80087070 00000000 */ .word 0x00000000
    /* 77874 80087074 E02D0580 */ .word DreamWorld__Nop40
    /* 77878 80087078 E82D0580 */ .word DreamWorld__Start
    /* 7787C 8008707C BC2E0580 */ .word DreamWorld__Stop
    /* 77880 80087080 102F0580 */ .word DreamWorld__InitStage
    /* 77884 80087084 34310580 */ .word DreamWorld__Shutdown
    /* 77888 80087088 A0310580 */ .word DreamWorld__OnEvent
    /* 7788C 8008708C 58330580 */ .word DreamWorld__Method58
    /* 77890 80087090 F0330580 */ .word DreamWorld__Tick
    /* 77894 80087094 ECA30480 */ .word SceneObj__SetState
    /* 77898 80087098 38E50380 */ .word Effect__ResetAndPause
    /* 7789C 8008709C 78E50380 */ .word Effect__ResetAndResume
    /* 778A0 800870A0 58A40480 */ .word SceneObj__SetTimeout
    /* 778A4 800870A4 78A40480 */ .word SceneObj__PlaySfx
    /* 778A8 800870A8 58340580 */ .word DreamWorld__Method74
    /* 778AC 800870AC 00000000 */ .word 0x00000000
    /* 778B0 800870B0 C0340580 */ .word DreamWorld__Nop7C
    /* 778B4 800870B4 C8340580 */ .word DreamWorld__ProcessChunkChange
    /* 778B8 800870B8 B0360580 */ .word DreamWorld__UnloadStage
    /* 778BC 800870BC 64370580 */ .word DreamWorld__Method88
    /* 778C0 800870C0 3C390580 */ .word DreamWorld__UpdateSpawner
    /* 778C4 800870C4 84390580 */ .word DreamWorld__DispatchEvent
    /* 778C8 800870C8 CC3A0580 */ .word DreamWorld__Method94
    /* 778CC 800870CC E83B0580 */ .word DreamWorld__Method98
    /* 778D0 800870D0 943C0580 */ .word DreamWorld__BeginLinkSequence
    /* 778D4 800870D4 183D0580 */ .word DreamWorld__LinkTeleport
    /* 778D8 800870D8 9C3D0580 */ .word DreamWorld__EndLinkSequence
    /* 778DC 800870DC 003E0580 */ .word DreamWorld__MethodA8
    /* 778E0 800870E0 843E0580 */ .word DreamWorld__MethodAC
    /* 778E4 800870E4 843F0580 */ .word DreamWorld__MethodB0
    /* 778E8 800870E8 E8400580 */ .word DreamWorld__OnEvent7
    /* 778EC 800870EC 20410580 */ .word DreamWorld__MethodB8
    /* 778F0 800870F0 CC410580 */ .word DreamWorld__NopBC
    /* 778F4 800870F4 D4410580 */ .word DreamWorld__ArmLinkRequest
    /* 778F8 800870F8 00420580 */ .word DreamWorld__ClearLinkRequest
    /* 778FC 800870FC 08420580 */ .word DreamWorld__ExecLinkRequestD
    /* 77900 80087100 6C420580 */ .word DreamWorld__ExecLinkRequestC
    /* 77904 80087104 D0420580 */ .word DreamWorld__BeginLinkEffect
    /* 77908 80087108 FC430580 */ .word DreamWorld__EndLinkEffect
enddlabel gVtable_DreamWorld

nonmatching D_8008710C

dlabel D_8008710C
    /* 7790C 8008710C 341F0000 */ .word 0x00001F34
    /* 77910 80087110 34F20100 */ .word 0x0001F234
    /* 77914 80087114 00000000 */ .word 0x00000000
enddlabel D_8008710C

nonmatching D_80087118

dlabel D_80087118
    /* 77918 80087118 80000000 */ .word 0x00000080
    /* 7791C 8008711C 00040000 */ .word 0x00000400
    /* 77920 80087120 80000000 */ .word 0x00000080
    /* 77924 80087124 00010000 */ .word 0x00000100
    /* 77928 80087128 00010000 */ .word 0x00000100
    /* 7792C 8008712C 00010000 */ .word 0x00000100
    /* 77930 80087130 00000000 */ .word 0x00000000
    /* 77934 80087134 00010000 */ .word 0x00000100
    /* 77938 80087138 00010000 */ .word 0x00000100
    /* 7793C 8008713C 80000000 */ .word 0x00000080
    /* 77940 80087140 00000000 */ .word 0x00000000
    /* 77944 80087144 00000000 */ .word 0x00000000
    /* 77948 80087148 00040000 */ .word 0x00000400
    /* 7794C 8008714C 00040000 */ .word 0x00000400
enddlabel D_80087118

nonmatching D_80087150

dlabel D_80087150
    /* 77950 80087150 00000000 */ .word 0x00000000
    /* 77954 80087154 08000000 */ .word 0x00000008
    /* 77958 80087158 09000000 */ .word 0x00000009
enddlabel D_80087150

nonmatching D_8008715C

dlabel D_8008715C
    /* 7795C 8008715C 00000000 */ .word 0x00000000
    /* 77960 80087160 50FBFFFF */ .word 0xFFFFFB50
    /* 77964 80087164 00000000 */ .word 0x00000000
enddlabel D_8008715C

nonmatching D_80087168

dlabel D_80087168
    /* 77968 80087168 00000000 */ .word 0x00000000
    /* 7796C 8008716C 50FBFFFF */ .word 0xFFFFFB50
    /* 77970 80087170 10270000 */ .word 0x00002710
enddlabel D_80087168

nonmatching D_80087174

dlabel D_80087174
    /* 77974 80087174 00000100 */ .word 0x00010000
    /* 77978 80087178 00000100 */ .word 0x00010000
    /* 7797C 8008717C 00000100 */ .word 0x00010000
    /* 77980 80087180 00000100 */ .word 0x00010000
    /* 77984 80087184 3C000100 */ .word 0x0001003C
    /* 77988 80087188 00000100 */ .word 0x00010000
    /* 7798C 8008718C 00000100 */ .word 0x00010000
    /* 77990 80087190 78000100 */ .word 0x00010078
    /* 77994 80087194 00000100 */ .word 0x00010000
    /* 77998 80087198 00000100 */ .word 0x00010000
    /* 7799C 8008719C B4000100 */ .word 0x000100B4
    /* 779A0 800871A0 00000100 */ .word 0x00010000
    /* 779A4 800871A4 00000100 */ .word 0x00010000
    /* 779A8 800871A8 E6000100 */ .word 0x000100E6
    /* 779AC 800871AC 00000100 */ .word 0x00010000
    /* 779B0 800871B0 FBFF0100 */ .word 0x0001FFFB
    /* 779B4 800871B4 00000100 */ .word 0x00010000
    /* 779B8 800871B8 00000100 */ .word 0x00010000
    /* 779BC 800871BC FDFF0100 */ .word 0x0001FFFD
    /* 779C0 800871C0 B4000100 */ .word 0x000100B4
    /* 779C4 800871C4 00000100 */ .word 0x00010000
enddlabel D_80087174

nonmatching D_800871C8

dlabel D_800871C8
    /* 779C8 800871C8 07000100 */ .word 0x00010007
    /* 779CC 800871CC 01000100 */ .word 0x00010001
    /* 779D0 800871D0 07000100 */ .word 0x00010007
    /* 779D4 800871D4 06000100 */ .word 0x00010006
    /* 779D8 800871D8 01000100 */ .word 0x00010001
    /* 779DC 800871DC 07000100 */ .word 0x00010007
    /* 779E0 800871E0 07000100 */ .word 0x00010007
    /* 779E4 800871E4 01000100 */ .word 0x00010001
    /* 779E8 800871E8 06000100 */ .word 0x00010006
    /* 779EC 800871EC 07000100 */ .word 0x00010007
    /* 779F0 800871F0 01000100 */ .word 0x00010001
    /* 779F4 800871F4 02000100 */ .word 0x00010002
    /* 779F8 800871F8 02000100 */ .word 0x00010002
    /* 779FC 800871FC 01000100 */ .word 0x00010001
    /* 77A00 80087200 07000100 */ .word 0x00010007
enddlabel D_800871C8

nonmatching D_80087204

dlabel D_80087204
    /* 77A04 80087204 01000100 */ .word 0x00010001
    /* 77A08 80087208 01000100 */ .word 0x00010001
    /* 77A0C 8008720C 01000100 */ .word 0x00010001
    /* 77A10 80087210 02000100 */ .word 0x00010002
    /* 77A14 80087214 01000100 */ .word 0x00010001
    /* 77A18 80087218 02000100 */ .word 0x00010002
enddlabel D_80087204

nonmatching D_8008721C

dlabel D_8008721C
    /* 77A1C 8008721C FFE6B4FF */ .word 0xFFB4E6FF
    /* 77A20 80087220 B4B4FF00 */ .word 0x00FFB4B4
    /* 77A24 80087224 00000000 */ .word 0x00000000
enddlabel D_8008721C

nonmatching D_80087228

dlabel D_80087228
    /* 77A28 80087228 FF8000C8 */ .word 0xC80080FF
    /* 77A2C 8008722C C8FF8080 */ .word 0x8080FFC8
    /* 77A30 80087230 FF000000 */ .word 0x000000FF
enddlabel D_80087228

nonmatching D_80087234

dlabel D_80087234
    /* 77A34 80087234 3777943C */ .word 0x3C947737
    /* 77A38 80087238 7997417B */ .word 0x7B419779
    /* 77A3C 8008723C 9A467D9D */ .word 0x9D7D469A
    /* 77A40 80087240 4B7FA050 */ .word 0x50A07F4B
    /* 77A44 80087244 81A35583 */ .word 0x8355A381
    /* 77A48 80087248 A65A85A9 */ .word 0xA9855AA6
    /* 77A4C 8008724C 5F87AC64 */ .word 0x64AC875F
    /* 77A50 80087250 89AF698B */ .word 0x8B69AF89
    /* 77A54 80087254 B26E8DB5 */ .word 0xB58D6EB2
    /* 77A58 80087258 738FB878 */ .word 0x78B88F73
    /* 77A5C 8008725C 96BB7B98 */ .word 0x987BBB96
    /* 77A60 80087260 BE7E99C0 */ .word 0xC0997EBE
    /* 77A64 80087264 809AC182 */ .word 0x82C19A80
    /* 77A68 80087268 9BC20000 */ .word 0x0000C29B
enddlabel D_80087234

nonmatching D_8008726C

dlabel D_8008726C
    /* 77A6C 8008726C 3777943C */ .word 0x3C947737
    /* 77A70 80087270 7997417B */ .word 0x7B419779
    /* 77A74 80087274 9A467D9D */ .word 0x9D7D469A
    /* 77A78 80087278 4B7FA050 */ .word 0x50A07F4B
    /* 77A7C 8008727C 81A35A83 */ .word 0x835AA381
    /* 77A80 80087280 A66E85A9 */ .word 0xA9856EA6
    /* 77A84 80087284 8287AC96 */ .word 0x96AC8782
    /* 77A88 80087288 89AFAA8B */ .word 0x8BAAAF89
    /* 77A8C 8008728C B2BE8DB5 */ .word 0xB58DBEB2
    /* 77A90 80087290 D28FB8E6 */ .word 0xE6B88FD2
    /* 77A94 80087294 96BBEB98 */ .word 0x98EBBB96
    /* 77A98 80087298 BEF099C0 */ .word 0xC099F0BE
    /* 77A9C 8008729C F59AC1FA */ .word 0xFAC19AF5
    /* 77AA0 800872A0 9BC20000 */ .word 0x0000C29B
enddlabel D_8008726C

nonmatching D_800872A4

dlabel D_800872A4
    /* 77AA4 800872A4 32002C01 */ .word 0x012C0032
    /* 77AA8 800872A8 3C000000 */ .word 0x0000003C
    /* 77AAC 800872AC F401C4FF */ .word 0xFFC401F4
    /* 77AB0 800872B0 D4FE1400 */ .word 0x0014FED4
    /* 77AB4 800872B4 14000000 */ .word 0x00000014
enddlabel D_800872A4

nonmatching D_800872B8

dlabel D_800872B8
    /* 77AB8 800872B8 C8C8C8C8 */ .word 0xC8C8C8C8
    /* 77ABC 800872BC F0F0FFE6 */ .word 0xE6FFF0F0
    /* 77AC0 800872C0 E6000000 */ .word 0x000000E6
enddlabel D_800872B8

nonmatching gSpawnRecordTable

dlabel gSpawnRecordTable
    /* 77AC4 800872C4 00000040 */ .word 0x40000000
    /* 77AC8 800872C8 40408080 */ .word 0x80804040
    /* 77ACC 800872CC 80FFFFFF */ .word 0xFFFFFF80
    /* 77AD0 800872D0 40000008 */ .word 0x08000040
    /* 77AD4 800872D4 20082020 */ .word 0x20200820
    /* 77AD8 800872D8 08180808 */ .word 0x08081808
    /* 77ADC 800872DC 18180818 */ .word 0x18081818
    /* 77AE0 800872E0 18800808 */ .word 0x08088018
    /* 77AE4 800872E4 18FF0000 */ .word 0x0000FF18
    /* 77AE8 800872E8 648CB432 */ .word 0x32B48C64
    /* 77AEC 800872EC 7791829B */ .word 0x9B829177
    /* 77AF0 800872F0 C20064BE */ .word 0xBE6400C2
    /* 77AF4 800872F4 00321E46 */ .word 0x461E3200
    /* 77AF8 800872F8 3200FA9B */ .word 0x9BFA0032
    /* 77AFC 800872FC C200FF00 */ .word 0x00FF00C2
    /* 77B00 80087300 788CB478 */ .word 0x78B48C78
    /* 77B04 80087304 00B4B400 */ .word 0x00B4B400
    /* 77B08 80087308 78000000 */ .word 0x00000078
enddlabel gSpawnRecordTable

nonmatching gSpawnScaleTable

dlabel gSpawnScaleTable
    /* 77B0C 8008730C 00680000 */ .word 0x00006800
    /* 77B10 80087310 00500000 */ .word 0x00005000
    /* 77B14 80087314 00380000 */ .word 0x00003800
    /* 77B18 80087318 00200000 */ .word 0x00002000
    /* 77B1C 8008731C 00100000 */ .word 0x00001000
    /* 77B20 80087320 00080000 */ .word 0x00000800
enddlabel gSpawnScaleTable

nonmatching D_80087324

dlabel D_80087324
    /* 77B24 80087324 00030810 */ .word 0x10080300
enddlabel D_80087324

nonmatching D_80087328

dlabel D_80087328
    /* 77B28 80087328 00E8FFFF */ .word 0xFFFFE800
enddlabel D_80087328

nonmatching D_8008732C

dlabel D_8008732C
    /* 77B2C 8008732C 00D8FFFF */ .word 0xFFFFD800
enddlabel D_8008732C

nonmatching D_80087330

dlabel D_80087330
    /* 77B30 80087330 00C8FFFF */ .word 0xFFFFC800
    /* 77B34 80087334 00B0FFFF */ .word 0xFFFFB000
enddlabel D_80087330

nonmatching D_80087338

dlabel D_80087338
    /* 77B38 80087338 00020A0A */ .word 0x0A0A0200
    /* 77B3C 8008733C 00010E0D */ .word 0x0D0E0100
enddlabel D_80087338

nonmatching D_80087340

dlabel D_80087340
    /* 77B40 80087340 00010E0D */ .word 0x0D0E0100
    /* 77B44 80087344 00020E0D */ .word 0x0D0E0200
    /* 77B48 80087348 0001120D */ .word 0x0D120100
    /* 77B4C 8008734C 0002120D */ .word 0x0D120200
    /* 77B50 80087350 00010E0D */ .word 0x0D0E0100
    /* 77B54 80087354 00020E0D */ .word 0x0D0E0200
    /* 77B58 80087358 0002140C */ .word 0x0C140200
enddlabel D_80087340

nonmatching D_8008735C

dlabel D_8008735C
    /* 77B5C 8008735C 00030303 */ .word 0x03030300
    /* 77B60 80087360 00020303 */ .word 0x03030200
    /* 77B64 80087364 00010303 */ .word 0x03030100
    /* 77B68 80087368 00001515 */ .word 0x15150000
    /* 77B6C 8008736C 00011313 */ .word 0x13130100
    /* 77B70 80087370 00020202 */ .word 0x02020200
    /* 77B74 80087374 00030202 */ .word 0x02020300
    /* 77B78 80087378 00040202 */ .word 0x02020400
    /* 77B7C 8008737C 00031516 */ .word 0x16150300
    /* 77B80 80087380 00040101 */ .word 0x01010400
enddlabel D_8008735C

nonmatching D_80087384

dlabel D_80087384
    /* 77B84 80087384 00020300 */ .word 0x00030200
    /* 77B88 80087388 01020300 */ .word 0x00030201
    /* 77B8C 8008738C 02020300 */ .word 0x00030202
    /* 77B90 80087390 0002070A */ .word 0x0A070200
    /* 77B94 80087394 0102070A */ .word 0x0A070201
    /* 77B98 80087398 0202070A */ .word 0x0A070202
    /* 77B9C 8008739C 0002080A */ .word 0x0A080200
    /* 77BA0 800873A0 0102080A */ .word 0x0A080201
    /* 77BA4 800873A4 0202080A */ .word 0x0A080202
    /* 77BA8 800873A8 00020606 */ .word 0x06060200
    /* 77BAC 800873AC 00020505 */ .word 0x05050200
    /* 77BB0 800873B0 00010404 */ .word 0x04040100
enddlabel D_80087384

nonmatching D_800873B4

dlabel D_800873B4
    /* 77BB4 800873B4 00030000 */ .word 0x00000300
    /* 77BB8 800873B8 00030909 */ .word 0x09090300
    /* 77BBC 800873BC 00031611 */ .word 0x11160300
    /* 77BC0 800873C0 00031010 */ .word 0x10100300
    /* 77BC4 800873C4 00031111 */ .word 0x11110300
enddlabel D_800873B4

nonmatching D_800873C8

dlabel D_800873C8
    /* 77BC8 800873C8 40730880 */ .word D_80087340
    /* 77BCC 800873CC 5C730880 */ .word D_8008735C
    /* 77BD0 800873D0 84730880 */ .word D_80087384
    /* 77BD4 800873D4 B4730880 */ .word D_800873B4
enddlabel D_800873C8

nonmatching D_800873D8

dlabel D_800873D8
    /* 77BD8 800873D8 070A0C05 */ .word 0x050C0A07
enddlabel D_800873D8

nonmatching D_800873DC

dlabel D_800873DC
    /* 77BDC 800873DC 00010203 */ .word 0x03020100
    /* 77BE0 800873E0 01020300 */ .word 0x00030201
    /* 77BE4 800873E4 00000202 */ .word 0x02020000
    /* 77BE8 800873E8 01030100 */ .word 0x00010301
enddlabel D_800873DC

nonmatching D_800873EC

dlabel D_800873EC
    /* 77BEC 800873EC 00000000 */ .word 0x00000000
    /* 77BF0 800873F0 00000000 */ .word 0x00000000
    /* 77BF4 800873F4 00000000 */ .word 0x00000000
    /* 77BF8 800873F8 00000000 */ .word 0x00000000
    /* 77BFC 800873FC 00000000 */ .word 0x00000000
    /* 77C00 80087400 38730880 */ .word D_80087338
    /* 77C04 80087404 80AB0880 */ .word D_8008AB80
    /* 77C08 80087408 80AB0880 */ .word D_8008AB80
    /* 77C0C 8008740C 8CAB0880 */ .word D_8008AB8C
    /* 77C10 80087410 80AB0880 */ .word D_8008AB80
    /* 77C14 80087414 90AB0880 */ .word D_8008AB90
    /* 77C18 80087418 84AB0880 */ .word D_8008AB84
    /* 77C1C 8008741C 84AB0880 */ .word D_8008AB84
    /* 77C20 80087420 00000000 */ .word 0x00000000
enddlabel D_800873EC

nonmatching D_80087424

dlabel D_80087424
    /* 77C24 80087424 A4720880 */ .word D_800872A4
    /* 77C28 80087428 B8720880 */ .word D_800872B8
    /* 77C2C 8008742C 78AB0880 */ .word D_8008AB78
enddlabel D_80087424

nonmatching D_80087430

dlabel D_80087430
    /* 77C30 80087430 00000000 */ .word 0x00000000
    /* 77C34 80087434 7CAB0880 */ .word D_8008AB7C
    /* 77C38 80087438 FFFFFFFF */ .word 0xFFFFFFFF
    /* 77C3C 8008743C 00000000 */ .word 0x00000000
    /* 77C40 80087440 00000000 */ .word 0x00000000
enddlabel D_80087430

nonmatching D_80087444

dlabel D_80087444
    /* 77C44 80087444 0000F001 */ .word 0x01F00000
    /* 77C48 80087448 F8000000 */ .word 0x000000F8
    /* 77C4C 8008744C 08000000 */ .word 0x00000008
enddlabel D_80087444

nonmatching D_80087450

dlabel D_80087450
    /* 77C50 80087450 0001F001 */ .word 0x01F00100
    /* 77C54 80087454 01000000 */ .word 0x00000001
    /* 77C58 80087458 08000000 */ .word 0x00000008
enddlabel D_80087450

nonmatching D_8008745C

dlabel D_8008745C
    /* 77C5C 8008745C 0000F801 */ .word 0x01F80000
    /* 77C60 80087460 F8000000 */ .word 0x000000F8
    /* 77C64 80087464 08000000 */ .word 0x00000008
enddlabel D_8008745C

nonmatching D_80087468

dlabel D_80087468
    /* 77C68 80087468 0001F801 */ .word 0x01F80100
    /* 77C6C 8008746C 01000000 */ .word 0x00000001
    /* 77C70 80087470 08000000 */ .word 0x00000008
enddlabel D_80087468

nonmatching D_80087474

dlabel D_80087474
    /* 77C74 80087474 00000000 */ .word 0x00000000
    /* 77C78 80087478 00400100 */ .word 0x00014000
    /* 77C7C 8008747C 00A00000 */ .word 0x0000A000
    /* 77C80 80087480 00400000 */ .word 0x00004000
    /* 77C84 80087484 00A00000 */ .word 0x0000A000
    /* 77C88 80087488 00F00000 */ .word 0x0000F000
    /* 77C8C 8008748C 00400100 */ .word 0x00014000
    /* 77C90 80087490 00400100 */ .word 0x00014000
    /* 77C94 80087494 00A00000 */ .word 0x0000A000
    /* 77C98 80087498 00A00000 */ .word 0x0000A000
    /* 77C9C 8008749C 00500000 */ .word 0x00005000
    /* 77CA0 800874A0 00A00000 */ .word 0x0000A000
    /* 77CA4 800874A4 00F00000 */ .word 0x0000F000
    /* 77CA8 800874A8 00A00000 */ .word 0x0000A000
    /* 77CAC 800874AC 00100000 */ .word 0x00001000
enddlabel D_80087474

nonmatching gSpawnBehaviorTable

dlabel gSpawnBehaviorTable
    /* 77CB0 800874B0 00000000 */ .word 0x00000000
    /* 77CB4 800874B4 885A0580 */ .word SpawnBehavior_01
    /* 77CB8 800874B8 105B0580 */ .word SpawnBehavior_02
    /* 77CBC 800874BC 6C5B0580 */ .word SpawnBehavior_03
    /* 77CC0 800874C0 C85B0580 */ .word SpawnBehavior_04
    /* 77CC4 800874C4 A85C0580 */ .word SpawnBehavior_05
    /* 77CC8 800874C8 B45D0580 */ .word SpawnBehavior_06
    /* 77CCC 800874CC 945E0580 */ .word SpawnBehavior_07
    /* 77CD0 800874D0 F05E0580 */ .word SpawnBehavior_08
    /* 77CD4 800874D4 745F0580 */ .word SpawnBehavior_09
    /* 77CD8 800874D8 E85F0580 */ .word SpawnBehavior_10
    /* 77CDC 800874DC 54600580 */ .word SpawnBehavior_11
    /* 77CE0 800874E0 E4600580 */ .word SpawnBehavior_12
    /* 77CE4 800874E4 94610580 */ .word SpawnBehavior_13
    /* 77CE8 800874E8 38620580 */ .word SpawnBehavior_14
enddlabel gSpawnBehaviorTable

nonmatching D_800874EC

dlabel D_800874EC
    /* 77CEC 800874EC 00000000 */ .word 0x00000000
    /* 77CF0 800874F0 00000000 */ .word 0x00000000
enddlabel D_800874EC

nonmatching D_800874F4

dlabel D_800874F4
    /* 77CF4 800874F4 00020608 */ .word 0x08060200
    /* 77CF8 800874F8 00000E00 */ .word 0x000E0000
enddlabel D_800874F4

nonmatching D_800874FC

dlabel D_800874FC
    /* 77CFC 800874FC 04030B04 */ .word 0x040B0304
    /* 77D00 80087500 00000900 */ .word 0x00090000
    /* 77D04 80087504 03001009 */ .word 0x09100003
    /* 77D08 80087508 00000400 */ .word 0x00040000
    /* 77D0C 8008750C 04010602 */ .word 0x02060104
    /* 77D10 80087510 00000400 */ .word 0x00040000
    /* 77D14 80087514 0401050E */ .word 0x0E050104
    /* 77D18 80087518 00000400 */ .word 0x00040000
    /* 77D1C 8008751C 03020F05 */ .word 0x050F0203
    /* 77D20 80087520 00000400 */ .word 0x00040000
    /* 77D24 80087524 03020F11 */ .word 0x110F0203
    /* 77D28 80087528 00000400 */ .word 0x00040000
    /* 77D2C 8008752C 04030509 */ .word 0x09050304
    /* 77D30 80087530 00000400 */ .word 0x00040000
    /* 77D34 80087534 03041001 */ .word 0x01100403
    /* 77D38 80087538 00000400 */ .word 0x00040000
    /* 77D3C 8008753C 0304100D */ .word 0x0D100403
    /* 77D40 80087540 00000400 */ .word 0x00040000
enddlabel D_800874FC

nonmatching D_80087544

dlabel D_80087544
    /* 77D44 80087544 07040706 */ .word 0x06070407
    /* 77D48 80087548 00000100 */ .word 0x00010000
    /* 77D4C 8008754C 0A040E0B */ .word 0x0B0E040A
    /* 77D50 80087550 00000100 */ .word 0x00010000
    /* 77D54 80087554 0501030A */ .word 0x0A030105
    /* 77D58 80087558 00000200 */ .word 0x00020000
    /* 77D5C 8008755C 09030006 */ .word 0x06000309
    /* 77D60 80087560 00000500 */ .word 0x00050000
    /* 77D64 80087564 0A00090A */ .word 0x0A09000A
    /* 77D68 80087568 00000500 */ .word 0x00050000
    /* 77D6C 8008756C 0A00090A */ .word 0x0A09000A
    /* 77D70 80087570 00000500 */ .word 0x00050000
    /* 77D74 80087574 0A00090A */ .word 0x0A09000A
    /* 77D78 80087578 00000500 */ .word 0x00050000
    /* 77D7C 8008757C 02000909 */ .word 0x09090002
    /* 77D80 80087580 00000C00 */ .word 0x000C0000
    /* 77D84 80087584 0A00090A */ .word 0x0A09000A
    /* 77D88 80087588 00000C00 */ .word 0x000C0000
    /* 77D8C 8008758C 0A00090A */ .word 0x0A09000A
    /* 77D90 80087590 00000C00 */ .word 0x000C0000
    /* 77D94 80087594 04010900 */ .word 0x00090104
    /* 77D98 80087598 00000100 */ .word 0x00010000
    /* 77D9C 8008759C 04010813 */ .word 0x13080104
    /* 77DA0 800875A0 00000100 */ .word 0x00010000
    /* 77DA4 800875A4 08020A0C */ .word 0x0C0A0208
    /* 77DA8 800875A8 00000100 */ .word 0x00010000
    /* 77DAC 800875AC 07040705 */ .word 0x05070407
    /* 77DB0 800875B0 00000100 */ .word 0x00010000
    /* 77DB4 800875B4 0A040E0C */ .word 0x0C0E040A
    /* 77DB8 800875B8 00000100 */ .word 0x00010000
    /* 77DBC 800875BC 0205020B */ .word 0x0B020502
    /* 77DC0 800875C0 00000100 */ .word 0x00010000
    /* 77DC4 800875C4 05071307 */ .word 0x07130705
    /* 77DC8 800875C8 00000100 */ .word 0x00010000
    /* 77DCC 800875CC 0300030A */ .word 0x0A030003
    /* 77DD0 800875D0 00000C00 */ .word 0x000C0000
    /* 77DD4 800875D4 0A000113 */ .word 0x1301000A
    /* 77DD8 800875D8 00000C00 */ .word 0x000C0000
    /* 77DDC 800875DC 05011307 */ .word 0x07130105
    /* 77DE0 800875E0 00000C00 */ .word 0x000C0000
    /* 77DE4 800875E4 0C01000C */ .word 0x0C00010C
    /* 77DE8 800875E8 00000C00 */ .word 0x000C0000
    /* 77DEC 800875EC 07020403 */ .word 0x03040207
    /* 77DF0 800875F0 00000C00 */ .word 0x000C0000
    /* 77DF4 800875F4 09021100 */ .word 0x00110209
    /* 77DF8 800875F8 00000C00 */ .word 0x000C0000
    /* 77DFC 800875FC 07050F08 */ .word 0x080F0507
    /* 77E00 80087600 00000C00 */ .word 0x000C0000
    /* 77E04 80087604 06070508 */ .word 0x08050706
    /* 77E08 80087608 00000C00 */ .word 0x000C0000
    /* 77E0C 8008760C 0508070B */ .word 0x0B070805
    /* 77E10 80087610 00000C00 */ .word 0x000C0000
    /* 77E14 80087614 0D0D0F0F */ .word 0x0F0F0D0D
    /* 77E18 80087618 00000C00 */ .word 0x000C0000
    /* 77E1C 8008761C 010E010F */ .word 0x0F010E01
    /* 77E20 80087620 00000C00 */ .word 0x000C0000
    /* 77E24 80087624 0D0E0909 */ .word 0x09090E0D
    /* 77E28 80087628 00000C00 */ .word 0x000C0000
enddlabel D_80087544

nonmatching D_8008762C

dlabel D_8008762C
    /* 77E2C 8008762C 05030209 */ .word 0x09020305
    /* 77E30 80087630 00000300 */ .word 0x00030000
    /* 77E34 80087634 00021011 */ .word 0x11100200
    /* 77E38 80087638 00000800 */ .word 0x00080000
    /* 77E3C 8008763C 0104100D */ .word 0x0D100401
    /* 77E40 80087640 00000600 */ .word 0x00060000
    /* 77E44 80087644 01041100 */ .word 0x00110401
    /* 77E48 80087648 00000600 */ .word 0x00060000
    /* 77E4C 8008764C 02040E02 */ .word 0x020E0402
    /* 77E50 80087650 00000600 */ .word 0x00060000
enddlabel D_8008762C

nonmatching D_80087654

dlabel D_80087654
    /* 77E54 80087654 04050006 */ .word 0x06000504
    /* 77E58 80087658 00000B00 */ .word 0x000B0000
    /* 77E5C 8008765C 04050006 */ .word 0x06000504
    /* 77E60 80087660 00000700 */ .word 0x00070000
    /* 77E64 80087664 02050202 */ .word 0x02020502
    /* 77E68 80087668 00000700 */ .word 0x00070000
    /* 77E6C 8008766C 0004120F */ .word 0x0F120400
    /* 77E70 80087670 00000700 */ .word 0x00070000
    /* 77E74 80087674 0103080D */ .word 0x0D080301
    /* 77E78 80087678 00000700 */ .word 0x00070000
    /* 77E7C 8008767C 00021211 */ .word 0x11120200
    /* 77E80 80087680 00000700 */ .word 0x00070000
    /* 77E84 80087684 01010713 */ .word 0x13070101
    /* 77E88 80087688 00000700 */ .word 0x00070000
    /* 77E8C 8008768C 00001212 */ .word 0x12120000
    /* 77E90 80087690 00000700 */ .word 0x00070000
    /* 77E94 80087694 00001205 */ .word 0x05120000
    /* 77E98 80087698 00000700 */ .word 0x00070000
enddlabel D_80087654

nonmatching D_8008769C

dlabel D_8008769C
    /* 77E9C 8008769C 0200080A */ .word 0x0A080002
    /* 77EA0 800876A0 00000A00 */ .word 0x000A0000
enddlabel D_8008769C

nonmatching D_800876A4

dlabel D_800876A4
    /* 77EA4 800876A4 01010C08 */ .word 0x080C0101
    /* 77EA8 800876A8 00000A00 */ .word 0x000A0000
enddlabel D_800876A4

nonmatching D_800876AC

dlabel D_800876AC
    /* 77EAC 800876AC 00000309 */ .word 0x09030000
    /* 77EB0 800876B0 00000D00 */ .word 0x000D0000
enddlabel D_800876AC

nonmatching D_800876B4

dlabel D_800876B4
    /* 77EB4 800876B4 F4740880 */ .word D_800874F4
    /* 77EB8 800876B8 00000000 */ .word 0x00000000
    /* 77EBC 800876BC FC740880 */ .word D_800874FC
    /* 77EC0 800876C0 44750880 */ .word D_80087544
    /* 77EC4 800876C4 2C760880 */ .word D_8008762C
    /* 77EC8 800876C8 54760880 */ .word D_80087654
    /* 77ECC 800876CC 00000000 */ .word 0x00000000
    /* 77ED0 800876D0 00000000 */ .word 0x00000000
    /* 77ED4 800876D4 00000000 */ .word 0x00000000
    /* 77ED8 800876D8 00000000 */ .word 0x00000000
    /* 77EDC 800876DC 9C760880 */ .word D_8008769C
    /* 77EE0 800876E0 A4760880 */ .word D_800876A4
    /* 77EE4 800876E4 00000000 */ .word 0x00000000
    /* 77EE8 800876E8 AC760880 */ .word D_800876AC
enddlabel D_800876B4

nonmatching D_800876EC

dlabel D_800876EC
    /* 77EEC 800876EC 0100091D */ .word 0x1D090001
    /* 77EF0 800876F0 05090000 */ .word 0x00000905
    /* 77EF4 800876F4 00000101 */ .word 0x01010000
    /* 77EF8 800876F8 00010000 */ .word 0x00000100
enddlabel D_800876EC

nonmatching gVtable_Actor

dlabel gVtable_Actor
    /* 77EFC 800876FC 34EF0000 */ .word 0x0000EF34
    /* 77F00 80087700 B07E0180 */ .word BasicClass__Delete
    /* 77F04 80087704 C0630580 */ .word Actor__Constructor
    /* 77F08 80087708 64640580 */ .word Actor__Destructor
    /* 77F0C 8008770C B4700580 */ .word ActorBase__AddEventListener
    /* 77F10 80087710 30710580 */ .word ActorBase__RemoveEventListener
    /* 77F14 80087714 A8710580 */ .word ActorBase__ClearListeners
    /* 77F18 80087718 BC800180 */ .word BasicClass__NextChildA
    /* 77F1C 8008771C FC800180 */ .word BasicClass__AddChildB
    /* 77F20 80087720 1C810180 */ .word BasicClass__RemoveChildB
    /* 77F24 80087724 3C810180 */ .word BasicClass__ClearChildrenB
    /* 77F28 80087728 6C810180 */ .word BasicClass__NextChildB
    /* 77F2C 8008772C CC820180 */ .word BasicClass__func_182cc
    /* 77F30 80087730 50830180 */ .word BasicClass__Nop
    /* 77F34 80087734 60CD0180 */ .word SceneNode__DispatchMessage
    /* 77F38 80087738 00000000 */ .word 0x00000000
    /* 77F3C 8008773C A4640580 */ .word Actor__SetTransform
    /* 77F40 80087740 B4CE0180 */ .word func_8001CEB4
    /* 77F44 80087744 08D00180 */ .word func_8001D008
    /* 77F48 80087748 ECD00180 */ .word SceneNode__AttachChild
    /* 77F4C 8008774C A4D10180 */ .word SceneNode__DetachChild
    /* 77F50 80087750 04D20180 */ .word SceneNode__UpdateChildren
    /* 77F54 80087754 80D20180 */ .word SceneNode__FindChild
    /* 77F58 80087758 3CD30180 */ .word func_8001D33C
    /* 77F5C 8008775C 44D30180 */ .word SceneNode__SetInvisible
    /* 77F60 80087760 74D30180 */ .word SceneNode__SetAttrBit30
    /* 77F64 80087764 A0D30180 */ .word SceneNode__SetDrawMode
    /* 77F68 80087768 CCD30180 */ .word SceneNode__SetAttrBit6
    /* 77F6C 8008776C F8D30180 */ .word SceneNode__SetAttrField3
    /* 77F70 80087770 24D40180 */ .word SceneNode__SetAttrField0
    /* 77F74 80087774 50D40180 */ .word SceneNode__SetAttrBit7
    /* 77F78 80087778 80D40180 */ .word SceneNode__SetAttrField9
    /* 77F7C 8008777C ACD40180 */ .word SceneNode__SetAttrBit8
    /* 77F80 80087780 DCD40180 */ .word func_8001D4DC
    /* 77F84 80087784 F8710580 */ .word ActorBase__Method88
    /* 77F88 80087788 00D60180 */ .word func_8001D600
    /* 77F8C 8008778C 24D60180 */ .word SceneNode__LoadVerts
    /* 77F90 80087790 A4D60180 */ .word func_8001D6A4
    /* 77F94 80087794 ACD60180 */ .word func_8001D6AC
    /* 77F98 80087798 20730580 */ .word ActorBase__HandleCommand
    /* 77F9C 8008779C 14D70180 */ .word func_8001D714
    /* 77FA0 800877A0 50D90180 */ .word func_8001D950
    /* 77FA4 800877A4 28DA0180 */ .word func_8001DA28
    /* 77FA8 800877A8 F4DD0180 */ .word func_8001DDF4
    /* 77FAC 800877AC 00000000 */ .word 0x00000000
    /* 77FB0 800877B0 A4E40180 */ .word func_8001E4A4
    /* 77FB4 800877B4 84730580 */ .word ActorBase__SetVelocity
    /* 77FB8 800877B8 A8730580 */ .word ActorBase__AddVelocity
    /* 77FBC 800877BC 44740580 */ .word ActorBase__TransformPoint
    /* 77FC0 800877C0 8C740580 */ .word ActorBase__LoadAnimSet6
    /* 77FC4 800877C4 C4740580 */ .word ActorBase__LoadAnimSet7
    /* 77FC8 800877C8 FC740580 */ .word ActorBase__LoadAnimSet8
    /* 77FCC 800877CC B0750580 */ .word ActorBase__PlayAnimA
    /* 77FD0 800877D0 E0750580 */ .word ActorBase__PlayAnimB
    /* 77FD4 800877D4 10760580 */ .word ActorBase__Nop
    /* 77FD8 800877D8 907B0580 */ .word ActorBase__MethodDC
    /* 77FDC 800877DC 147C0580 */ .word ActorBase__MethodE0
    /* 77FE0 800877E0 6C7C0580 */ .word ActorBase__SetTimer48
    /* 77FE4 800877E4 747C0580 */ .word ActorBase__NopE8
    /* 77FE8 800877E8 F4640580 */ .word Actor__Tick
enddlabel gVtable_Actor

nonmatching D_800877EC

dlabel D_800877EC
    /* 77FEC 800877EC 00000000 */ .word 0x00000000
    /* 77FF0 800877F0 00000000 */ .word 0x00000000
    /* 77FF4 800877F4 00000000 */ .word 0x00000000
enddlabel D_800877EC

nonmatching D_800877F8

dlabel D_800877F8
    /* 77FF8 800877F8 00000000 */ .word 0x00000000
    /* 77FFC 800877FC 80FFFFFF */ .word 0xFFFFFF80
    /* 78000 80087800 80000000 */ .word 0x00000080
    /* 78004 80087804 00FFFFFF */ .word 0xFFFFFF00
    /* 78008 80087808 40000000 */ .word 0x00000040
enddlabel D_800877F8

nonmatching D_8008780C

dlabel D_8008780C
    /* 7800C 8008780C 00000000 */ .word 0x00000000
    /* 78010 80087810 00000000 */ .word 0x00000000
    /* 78014 80087814 00000000 */ .word 0x00000000
    /* 78018 80087818 FFFFFFFF */ .word 0xFFFFFFFF
    /* 7801C 8008781C FEFFFFFF */ .word 0xFFFFFFFE
    /* 78020 80087820 FCFFFFFF */ .word 0xFFFFFFFC
    /* 78024 80087824 F0FFFFFF */ .word 0xFFFFFFF0
    /* 78028 80087828 00FFFFFF */ .word 0xFFFFFF00
enddlabel D_8008780C

nonmatching D_8008782C

dlabel D_8008782C
    /* 7802C 8008782C 00000000 */ .word 0x00000000
    /* 78030 80087830 00000000 */ .word 0x00000000
    /* 78034 80087834 00000000 */ .word 0x00000000
enddlabel D_8008782C

nonmatching D_80087838

dlabel D_80087838
    /* 78038 80087838 00000100 */ .word 0x00010000
    /* 7803C 8008783C 01000A00 */ .word 0x000A0001
    /* 78040 80087840 00000100 */ .word 0x00010000
enddlabel D_80087838

nonmatching D_80087844

dlabel D_80087844
    /* 78044 80087844 00000000 */ .word 0x00000000
    /* 78048 80087848 00000000 */ .word 0x00000000
    /* 7804C 8008784C 80FFFFFF */ .word 0xFFFFFF80
    /* 78050 80087850 00FFFFFF */ .word 0xFFFFFF00
    /* 78054 80087854 00FEFFFF */ .word 0xFFFFFE00
    /* 78058 80087858 00FDFFFF */ .word 0xFFFFFD00
enddlabel D_80087844

nonmatching D_8008785C

dlabel D_8008785C
    /* 7805C 8008785C 06000500 */ .word 0x00050006
    /* 78060 80087860 06000500 */ .word 0x00050006
    /* 78064 80087864 01000100 */ .word 0x00010001
enddlabel D_8008785C

nonmatching D_80087868

dlabel D_80087868
    /* 78068 80087868 03000600 */ .word 0x00060003
    /* 7806C 8008786C 03000600 */ .word 0x00060003
    /* 78070 80087870 01000100 */ .word 0x00010001
enddlabel D_80087868

nonmatching D_80087874

dlabel D_80087874
    /* 78074 80087874 04000600 */ .word 0x00060004
    /* 78078 80087878 04000600 */ .word 0x00060004
    /* 7807C 8008787C 01000100 */ .word 0x00010001
enddlabel D_80087874

nonmatching D_80087880

dlabel D_80087880
    /* 78080 80087880 00000000 */ .word 0x00000000
    /* 78084 80087884 00000000 */ .word 0x00000000
    /* 78088 80087888 00000000 */ .word 0x00000000
enddlabel D_80087880

nonmatching D_8008788C

dlabel D_8008788C
    /* 7808C 8008788C 01001000 */ .word 0x00100001
    /* 78090 80087890 07000100 */ .word 0x00010007
    /* 78094 80087894 01000100 */ .word 0x00010001
    /* 78098 80087898 07000100 */ .word 0x00010007
    /* 7809C 8008789C 01001000 */ .word 0x00100001
    /* 780A0 800878A0 01000100 */ .word 0x00010001
    /* 780A4 800878A4 01001000 */ .word 0x00100001
    /* 780A8 800878A8 03000100 */ .word 0x00010003
    /* 780AC 800878AC 01000100 */ .word 0x00010001
    /* 780B0 800878B0 03000100 */ .word 0x00010003
    /* 780B4 800878B4 01001000 */ .word 0x00100001
    /* 780B8 800878B8 01000100 */ .word 0x00010001
    /* 780BC 800878BC 01001000 */ .word 0x00100001
    /* 780C0 800878C0 02000100 */ .word 0x00010002
    /* 780C4 800878C4 01000100 */ .word 0x00010001
    /* 780C8 800878C8 02000100 */ .word 0x00010002
    /* 780CC 800878CC 01001000 */ .word 0x00100001
    /* 780D0 800878D0 01000100 */ .word 0x00010001
enddlabel D_8008788C

.align 2
nonmatching gVtable_ActorBase

dlabel gVtable_ActorBase
    /* 780D4 800878D4 */ .asciz "4"
    /* 34000000 */
.align 2
    /* 780D8 800878D8 B07E0180 */ .word BasicClass__Delete
    /* 780DC 800878DC 44700580 */ .word ActorBase__Constructor
    /* 780E0 800878E0 A4CB0180 */ .word SceneNode__Destructor
    /* 780E4 800878E4 B4700580 */ .word ActorBase__AddEventListener
    /* 780E8 800878E8 30710580 */ .word ActorBase__RemoveEventListener
    /* 780EC 800878EC A8710580 */ .word ActorBase__ClearListeners
    /* 780F0 800878F0 BC800180 */ .word BasicClass__NextChildA
    /* 780F4 800878F4 FC800180 */ .word BasicClass__AddChildB
    /* 780F8 800878F8 1C810180 */ .word BasicClass__RemoveChildB
    /* 780FC 800878FC 3C810180 */ .word BasicClass__ClearChildrenB
    /* 78100 80087900 6C810180 */ .word BasicClass__NextChildB
    /* 78104 80087904 CC820180 */ .word BasicClass__func_182cc
    /* 78108 80087908 50830180 */ .word BasicClass__Nop
    /* 7810C 8008790C 60CD0180 */ .word SceneNode__DispatchMessage
    /* 78110 80087910 00000000 */ .word 0x00000000
    /* 78114 80087914 E8710580 */ .word ActorBase__InitDefaults
    /* 78118 80087918 B4CE0180 */ .word func_8001CEB4
    /* 7811C 8008791C 08D00180 */ .word func_8001D008
    /* 78120 80087920 ECD00180 */ .word SceneNode__AttachChild
    /* 78124 80087924 A4D10180 */ .word SceneNode__DetachChild
    /* 78128 80087928 04D20180 */ .word SceneNode__UpdateChildren
    /* 7812C 8008792C 80D20180 */ .word SceneNode__FindChild
    /* 78130 80087930 3CD30180 */ .word func_8001D33C
    /* 78134 80087934 44D30180 */ .word SceneNode__SetInvisible
    /* 78138 80087938 74D30180 */ .word SceneNode__SetAttrBit30
    /* 7813C 8008793C A0D30180 */ .word SceneNode__SetDrawMode
    /* 78140 80087940 CCD30180 */ .word SceneNode__SetAttrBit6
    /* 78144 80087944 F8D30180 */ .word SceneNode__SetAttrField3
    /* 78148 80087948 24D40180 */ .word SceneNode__SetAttrField0
    /* 7814C 8008794C 50D40180 */ .word SceneNode__SetAttrBit7
    /* 78150 80087950 80D40180 */ .word SceneNode__SetAttrField9
    /* 78154 80087954 ACD40180 */ .word SceneNode__SetAttrBit8
    /* 78158 80087958 DCD40180 */ .word func_8001D4DC
    /* 7815C 8008795C F8710580 */ .word ActorBase__Method88
    /* 78160 80087960 00D60180 */ .word func_8001D600
    /* 78164 80087964 24D60180 */ .word SceneNode__LoadVerts
    /* 78168 80087968 A4D60180 */ .word func_8001D6A4
    /* 7816C 8008796C ACD60180 */ .word func_8001D6AC
    /* 78170 80087970 20730580 */ .word ActorBase__HandleCommand
    /* 78174 80087974 14D70180 */ .word func_8001D714
    /* 78178 80087978 50D90180 */ .word func_8001D950
    /* 7817C 8008797C 28DA0180 */ .word func_8001DA28
    /* 78180 80087980 F4DD0180 */ .word func_8001DDF4
    /* 78184 80087984 00000000 */ .word 0x00000000
    /* 78188 80087988 A4E40180 */ .word func_8001E4A4
    /* 7818C 8008798C 84730580 */ .word ActorBase__SetVelocity
    /* 78190 80087990 A8730580 */ .word ActorBase__AddVelocity
    /* 78194 80087994 44740580 */ .word ActorBase__TransformPoint
    /* 78198 80087998 8C740580 */ .word ActorBase__LoadAnimSet6
    /* 7819C 8008799C C4740580 */ .word ActorBase__LoadAnimSet7
    /* 781A0 800879A0 FC740580 */ .word ActorBase__LoadAnimSet8
    /* 781A4 800879A4 B0750580 */ .word ActorBase__PlayAnimA
    /* 781A8 800879A8 E0750580 */ .word ActorBase__PlayAnimB
    /* 781AC 800879AC 10760580 */ .word ActorBase__Nop
    /* 781B0 800879B0 907B0580 */ .word ActorBase__MethodDC
    /* 781B4 800879B4 147C0580 */ .word ActorBase__MethodE0
    /* 781B8 800879B8 6C7C0580 */ .word ActorBase__SetTimer48
    /* 781BC 800879BC 747C0580 */ .word ActorBase__NopE8
    /* 781C0 800879C0 7C7C0580 */ .word ActorBase__SetState54
enddlabel gVtable_ActorBase

nonmatching gVtable_ActorSprite

dlabel gVtable_ActorSprite
    /* 781C4 800879C4 441F0000 */ .word 0x00001F44
    /* 781C8 800879C8 B07E0180 */ .word BasicClass__Delete
    /* 781CC 800879CC 107D0580 */ .word ActorSprite__Constructor
    /* 781D0 800879D0 A4CB0180 */ .word SceneNode__Destructor
    /* 781D4 800879D4 48CC0180 */ .word SceneNode__HandleMessage
    /* 781D8 800879D8 B4CC0180 */ .word func_8001CCB4
    /* 781DC 800879DC 20CD0180 */ .word SceneNode__Reset
    /* 781E0 800879E0 BC800180 */ .word BasicClass__NextChildA
    /* 781E4 800879E4 FC800180 */ .word BasicClass__AddChildB
    /* 781E8 800879E8 1C810180 */ .word BasicClass__RemoveChildB
    /* 781EC 800879EC 3C810180 */ .word BasicClass__ClearChildrenB
    /* 781F0 800879F0 6C810180 */ .word BasicClass__NextChildB
    /* 781F4 800879F4 CC820180 */ .word BasicClass__func_182cc
    /* 781F8 800879F8 50830180 */ .word BasicClass__Nop
    /* 781FC 800879FC 60CD0180 */ .word SceneNode__DispatchMessage
    /* 78200 80087A00 00000000 */ .word 0x00000000
    /* 78204 80087A04 BC7D0580 */ .word ActorSprite__SetVariant
    /* 78208 80087A08 70210480 */ .word func_80042170
    /* 7820C 80087A0C F47D0580 */ .word ActorSprite__Method48
    /* 78210 80087A10 ECD00180 */ .word SceneNode__AttachChild
    /* 78214 80087A14 A4D10180 */ .word SceneNode__DetachChild
    /* 78218 80087A18 04D20180 */ .word SceneNode__UpdateChildren
    /* 7821C 80087A1C 80D20180 */ .word SceneNode__FindChild
    /* 78220 80087A20 3CD30180 */ .word func_8001D33C
    /* 78224 80087A24 0C220480 */ .word func_8004220C
    /* 78228 80087A28 3C220480 */ .word func_8004223C
    /* 7822C 80087A2C 68220480 */ .word func_80042268
    /* 78230 80087A30 CCD30180 */ .word SceneNode__SetAttrBit6
    /* 78234 80087A34 F8D30180 */ .word SceneNode__SetAttrField3
    /* 78238 80087A38 24D40180 */ .word SceneNode__SetAttrField0
    /* 7823C 80087A3C 50D40180 */ .word SceneNode__SetAttrBit7
    /* 78240 80087A40 80D40180 */ .word SceneNode__SetAttrField9
    /* 78244 80087A44 ACD40180 */ .word SceneNode__SetAttrBit8
    /* 78248 80087A48 DCD40180 */ .word func_8001D4DC
    /* 7824C 80087A4C 68D50180 */ .word func_8001D568
    /* 78250 80087A50 00D60180 */ .word func_8001D600
    /* 78254 80087A54 24D60180 */ .word SceneNode__LoadVerts
    /* 78258 80087A58 A4D60180 */ .word func_8001D6A4
    /* 7825C 80087A5C 387F0580 */ .word ActorSprite__Nop98
    /* 78260 80087A60 B4D60180 */ .word func_8001D6B4
    /* 78264 80087A64 14D70180 */ .word func_8001D714
    /* 78268 80087A68 50D90180 */ .word func_8001D950
    /* 7826C 80087A6C 28DA0180 */ .word func_8001DA28
    /* 78270 80087A70 F4DD0180 */ .word func_8001DDF4
    /* 78274 80087A74 9CE40180 */ .word func_8001E49C
    /* 78278 80087A78 A4E40180 */ .word func_8001E4A4
    /* 7827C 80087A7C 9C220480 */ .word func_8004229C
    /* 78280 80087A80 407F0580 */ .word ActorSprite__NopBC
    /* 78284 80087A84 487F0580 */ .word ActorSprite__NopC0
    /* 78288 80087A88 507F0580 */ .word ActorSprite__NopC4
enddlabel gVtable_ActorSprite

nonmatching gActorSpriteConfig

dlabel gActorSpriteConfig
    /* 7828C 80087A8C 00002001 */ .word 0x01200000
    /* 78290 80087A90 10000000 */ .word 0x00000010
    /* 78294 80087A94 10000000 */ .word 0x00000010
    /* 78298 80087A98 10002001 */ .word 0x01200010
    /* 7829C 80087A9C 10000000 */ .word 0x00000010
    /* 782A0 80087AA0 10000000 */ .word 0x00000010
enddlabel gActorSpriteConfig

nonmatching gActorSpriteTexIds

dlabel gActorSpriteTexIds
    /* 782A4 80087AA4 D003FF01 */ .word 0x01FF03D0
    /* 782A8 80087AA8 E003FF01 */ .word 0x01FF03E0
enddlabel gActorSpriteTexIds

nonmatching gVtable_GraphScreen

dlabel gVtable_GraphScreen
    /* 782AC 80087AAC 30F10200 */ .word 0x0002F130
    /* 782B0 80087AB0 B07E0180 */ .word BasicClass__Delete
    /* 782B4 80087AB4 C87F0580 */ .word GraphScreen__Constructor
    /* 782B8 80087AB8 08C00380 */ .word AnimEffect__Destroy
    /* 782BC 80087ABC 987F0180 */ .word BasicClass__AdoptChild
    /* 782C0 80087AC0 F07F0180 */ .word BasicClass__func_17ff0
    /* 782C4 80087AC4 40800180 */ .word BasicClass__func_18040
    /* 782C8 80087AC8 BC800180 */ .word BasicClass__NextChildA
    /* 782CC 80087ACC FC800180 */ .word BasicClass__AddChildB
    /* 782D0 80087AD0 1C810180 */ .word BasicClass__RemoveChildB
    /* 782D4 80087AD4 3C810180 */ .word BasicClass__ClearChildrenB
    /* 782D8 80087AD8 6C810180 */ .word BasicClass__NextChildB
    /* 782DC 80087ADC CC820180 */ .word BasicClass__func_182cc
    /* 782E0 80087AE0 50830180 */ .word BasicClass__Nop
    /* 782E4 80087AE4 30E00380 */ .word Effect__Destroy
    /* 782E8 80087AE8 00000000 */ .word 0x00000000
    /* 782EC 80087AEC 78800580 */ .word GraphScreen__LoadGraph
    /* 782F0 80087AF0 90830580 */ .word GraphScreen__GetResult
    /* 782F4 80087AF4 80E20380 */ .word func_8003E280
    /* 782F8 80087AF8 38C20380 */ .word func_8003C238
    /* 782FC 80087AFC D0C30380 */ .word AnimEffect__Render
    /* 78300 80087B00 18E40380 */ .word Effect__HandleChildMsg
    /* 78304 80087B04 8CC40380 */ .word AnimEffect__HandleMessage
    /* 78308 80087B08 E0800580 */ .word GraphScreen__UpdateCursor
    /* 7830C 80087B0C 3CC60380 */ .word func_8003C63C
    /* 78310 80087B10 38E50380 */ .word Effect__ResetAndPause
    /* 78314 80087B14 78E50380 */ .word Effect__ResetAndResume
    /* 78318 80087B18 94C70380 */ .word AnimEffect__SetFrameDuration
    /* 7831C 80087B1C B4C70380 */ .word AnimEffect__SetScale
    /* 78320 80087B20 F4C70380 */ .word AnimEffect__TriggerAnimA
    /* 78324 80087B24 C4810580 */ .word GraphScreen__OnConfirm
    /* 78328 80087B28 D0C80380 */ .word AnimEffect__TriggerAnimC
    /* 7832C 80087B2C 44C90380 */ .word AnimEffect__DoModeAction1
    /* 78330 80087B30 B0C90380 */ .word AnimEffect__DoModeAction2
    /* 78334 80087B34 00000000 */ .word 0x00000000
    /* 78338 80087B38 00000000 */ .word 0x00000000
    /* 7833C 80087B3C 1CCA0380 */ .word AnimEffect__CheckFrameEntry
    /* 78340 80087B40 94CA0380 */ .word AnimEffect__RunCallback
    /* 78344 80087B44 ECCA0380 */ .word AnimEffect__SetCallback
    /* 78348 80087B48 F8CA0380 */ .word AnimEffect__SetModeA
    /* 7834C 80087B4C 30CB0380 */ .word AnimEffect__SetModeB
    /* 78350 80087B50 68CB0380 */ .word AnimEffect__SetColors
    /* 78354 80087B54 B8CB0380 */ .word AnimEffect__SetFadeSpeed
    /* 78358 80087B58 C0CB0380 */ .word AnimEffect__RunCondition
    /* 7835C 80087B5C 2CCC0380 */ .word AnimEffect__FadeInStep
    /* 78360 80087B60 00000000 */ .word 0x00000000
    /* 78364 80087B64 00000000 */ .word 0x00000000
    /* 78368 80087B68 00000000 */ .word 0x00000000
    /* 7836C 80087B6C DCCC0380 */ .word func_8003CCDC
    /* 78370 80087B70 48CD0380 */ .word AnimEffect__FadeOutStep
    /* 78374 80087B74 00000000 */ .word 0x00000000
    /* 78378 80087B78 00000000 */ .word 0x00000000
    /* 7837C 80087B7C 00000000 */ .word 0x00000000
    /* 78380 80087B80 E0CD0380 */ .word func_8003CDE0
    /* 78384 80087B84 28820580 */ .word GraphScreen__BuildChart
    /* 78388 80087B88 08830580 */ .word GraphScreen__TeardownChart
    /* 7838C 80087B8C 04840580 */ .word GraphScreen__MethodE0
    /* 78390 80087B90 CCD20380 */ .word func_8003D2CC
    /* 78394 80087B94 B0D30380 */ .word func_8003D3B0
    /* 78398 80087B98 44D40380 */ .word func_8003D444
    /* 7839C 80087B9C DCD40380 */ .word AnimEffect__SetFrame
    /* 783A0 80087BA0 C0D50380 */ .word AnimEffect__GetFrame
    /* 783A4 80087BA4 CCD50380 */ .word AnimEffect__AddFrameSet
    /* 783A8 80087BA8 D4D60380 */ .word AnimEffect__FreeFrameSet
    /* 783AC 80087BAC 3CD70380 */ .word AnimEffect__RenderFrame
    /* 783B0 80087BB0 80D90380 */ .word AnimEffect__ForEachFrameSprite
    /* 783B4 80087BB4 10DA0380 */ .word func_8003DA10
    /* 783B8 80087BB8 D4DA0380 */ .word func_8003DAD4
    /* 783BC 80087BBC ACDC0380 */ .word AnimEffect__AdvanceFrame
    /* 783C0 80087BC0 C8DD0380 */ .word func_8003DDC8
    /* 783C4 80087BC4 30DE0380 */ .word func_8003DE30
    /* 783C8 80087BC8 9CDE0380 */ .word func_8003DE9C
    /* 783CC 80087BCC A0DF0380 */ .word AnimEffect__GetFrameEntryId
    /* 783D0 80087BD0 94860580 */ .word GraphScreen__Method124
enddlabel gVtable_GraphScreen

nonmatching D_80087BD4

dlabel D_80087BD4
    /* 783D4 80087BD4 FF010101 */ .word 0x010101FF
    /* 783D8 80087BD8 000000FD */ .word 0xFD000000
enddlabel D_80087BD4
