.include "macro.inc"

.section .sdata, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching gpBMemHeap

dlabel gpBMemHeap
    /* 7B008 8008A808 00000000 */ .word 0x00000000
    /* 7B00C 8008A80C 00000000 */ .word 0x00000000
enddlabel gpBMemHeap

.align 2
nonmatching D_8008A810

dlabel D_8008A810
    /* 7B010 8008A810 */ .asciz "(null)"
    /* 286E756C6C290000 */
.align 2
enddlabel D_8008A810

nonmatching gBMemPoolSelect

dlabel gBMemPoolSelect
    /* 7B018 8008A818 00000000 */ .word 0x00000000
    /* 7B01C 8008A81C 00000000 */ .word 0x00000000
enddlabel gBMemPoolSelect

nonmatching gBMemLock

dlabel gBMemLock
    /* 7B020 8008A820 00000000 */ .word 0x00000000
enddlabel gBMemLock

nonmatching D_8008A824

dlabel D_8008A824
    /* 7B024 8008A824 40010000 */ .word 0x00000140
enddlabel D_8008A824

nonmatching D_8008A828

dlabel D_8008A828
    /* 7B028 8008A828 F0000000 */ .word 0x000000F0
enddlabel D_8008A828

nonmatching D_8008A82C

dlabel D_8008A82C
    /* 7B02C 8008A82C 80808000 */ .word 0x00808080
enddlabel D_8008A82C

nonmatching gDisplayMode

dlabel gDisplayMode
    /* 7B030 8008A830 01000000 */ .word 0x00000001
enddlabel gDisplayMode

nonmatching gDisplayParam

dlabel gDisplayParam
    /* 7B034 8008A834 02000000 */ .word 0x00000002
enddlabel gDisplayParam

nonmatching gSceneStateFlag

dlabel gSceneStateFlag
    /* 7B038 8008A838 00000000 */ .word 0x00000000
enddlabel gSceneStateFlag

nonmatching D_8008A83C

dlabel D_8008A83C
    /* 7B03C 8008A83C 00000000 */ .word 0x00000000
enddlabel D_8008A83C

.align 2
nonmatching D_8008A840

dlabel D_8008A840
    /* 7B040 8008A840 */ .asciz "<NULL>"
    /* 3C4E554C4C3E0000 */
.align 2
enddlabel D_8008A840

nonmatching gPadInstanceCount

dlabel gPadInstanceCount
    /* 7B048 8008A848 00000000 */ .word 0x00000000
enddlabel gPadInstanceCount

nonmatching gCdDriverMode

dlabel gCdDriverMode
    /* 7B04C 8008A84C 13000000 */ .word 0x00000013
enddlabel gCdDriverMode

nonmatching D_8008A850

dlabel D_8008A850
    /* 7B050 8008A850 00000000 */ .word 0x00000000
enddlabel D_8008A850

nonmatching gCdPathPrefix

dlabel gCdPathPrefix
    /* 7B054 8008A854 A8D40680 */ .word 0x8006D4A8
enddlabel gCdPathPrefix

nonmatching gCdModeInitialized

dlabel gCdModeInitialized
    /* 7B058 8008A858 00000000 */ .word 0x00000000
enddlabel gCdModeInitialized

nonmatching gCdUseFileTable

dlabel gCdUseFileTable
    /* 7B05C 8008A85C 00000000 */ .word 0x00000000
enddlabel gCdUseFileTable

nonmatching D_8008A860

dlabel D_8008A860
    /* 7B060 8008A860 00000000 */ .word 0x00000000
enddlabel D_8008A860

nonmatching gCdOpActive

dlabel gCdOpActive
    /* 7B064 8008A864 00000000 */ .word 0x00000000
enddlabel gCdOpActive

nonmatching gpCdFileTable

dlabel gpCdFileTable
    /* 7B068 8008A868 00000000 */ .word 0x00000000
enddlabel gpCdFileTable

nonmatching gCdFileTableCount

dlabel gCdFileTableCount
    /* 7B06C 8008A86C 00000000 */ .word 0x00000000
enddlabel gCdFileTableCount

nonmatching gCdOpIdle

dlabel gCdOpIdle
    /* 7B070 8008A870 01000000 */ .word 0x00000001
enddlabel gCdOpIdle

nonmatching gCdStreamCmd

dlabel gCdStreamCmd
    /* 7B074 8008A874 00000000 */ .word 0x00000000
enddlabel gCdStreamCmd

nonmatching gCdStreamState

dlabel gCdStreamState
    /* 7B078 8008A878 00000000 */ .word 0x00000000
enddlabel gCdStreamState

nonmatching D_8008A87C

dlabel D_8008A87C
    /* 7B07C 8008A87C 00000000 */ .word 0x00000000
enddlabel D_8008A87C

nonmatching D_8008A880

dlabel D_8008A880
    /* 7B080 8008A880 00000000 */ .word 0x00000000
enddlabel D_8008A880

nonmatching D_8008A884

dlabel D_8008A884
    /* 7B084 8008A884 00000000 */ .word 0x00000000
enddlabel D_8008A884

nonmatching D_8008A888

dlabel D_8008A888
    /* 7B088 8008A888 00000000 */ .word 0x00000000
enddlabel D_8008A888

nonmatching gCdStreamLock

dlabel gCdStreamLock
    /* 7B08C 8008A88C 00000000 */ .word 0x00000000
enddlabel gCdStreamLock

nonmatching gCdStreamingEnabled

dlabel gCdStreamingEnabled
    /* 7B090 8008A890 00000000 */ .word 0x00000000
enddlabel gCdStreamingEnabled

nonmatching gpCdRequestQueue

dlabel gpCdRequestQueue
    /* 7B094 8008A894 00000000 */ .word 0x00000000
enddlabel gpCdRequestQueue

nonmatching gCdStreamMode

dlabel gCdStreamMode
    /* 7B098 8008A898 00000000 */ .word 0x00000000
enddlabel gCdStreamMode

nonmatching D_8008A89C

dlabel D_8008A89C
    /* 7B09C 8008A89C 00000000 */ .word 0x00000000
enddlabel D_8008A89C

nonmatching gCdStreamRetryCount

dlabel gCdStreamRetryCount
    /* 7B0A0 8008A8A0 00000000 */ .word 0x00000000
enddlabel gCdStreamRetryCount

nonmatching gCdCallbackEnabled

dlabel gCdCallbackEnabled
    /* 7B0A4 8008A8A4 01000000 */ .word 0x00000001
enddlabel gCdCallbackEnabled

.align 2
nonmatching gCdFileSuffix

dlabel gCdFileSuffix
    /* 7B0A8 8008A8A8 */ .asciz ";1"
    /* 3B310000 */
.align 2
.align 2
    /* 7B0AC 8008A8AC */ .asciz ""
    /* 00000000 */
.align 2
enddlabel gCdFileSuffix

nonmatching gCdCallbackFn

dlabel gCdCallbackFn
    /* 7B0B0 8008A8B0 00000000 */ .word 0x00000000
enddlabel gCdCallbackFn

nonmatching gCdCallbackArg

dlabel gCdCallbackArg
    /* 7B0B4 8008A8B4 00000000 */ .word 0x00000000
enddlabel gCdCallbackArg

nonmatching D_8008A8B8

dlabel D_8008A8B8
    /* 7B0B8 8008A8B8 00000000 */ .word 0x00000000
enddlabel D_8008A8B8

nonmatching D_8008A8BC

dlabel D_8008A8BC
    /* 7B0BC 8008A8BC 00000000 */ .word 0x00000000
enddlabel D_8008A8BC

nonmatching D_8008A8C0

dlabel D_8008A8C0
    /* 7B0C0 8008A8C0 00000000 */ .word 0x00000000
enddlabel D_8008A8C0

nonmatching gSoundPlayerCount

dlabel gSoundPlayerCount
    /* 7B0C4 8008A8C4 00000000 */ .word 0x00000000
enddlabel gSoundPlayerCount

nonmatching D_8008A8C8

dlabel D_8008A8C8
    /* 7B0C8 8008A8C8 00000000 */ .word 0x00000000
enddlabel D_8008A8C8

nonmatching D_8008A8CC

dlabel D_8008A8CC
    /* 7B0CC 8008A8CC 00000000 */ .word 0x00000000
enddlabel D_8008A8CC

.align 2
nonmatching D_8008A8D0

dlabel D_8008A8D0
    /* 7B0D0 8008A8D0 */ .asciz ".VH"
    /* 2E564800 */
.align 2
enddlabel D_8008A8D0

.align 2
nonmatching D_8008A8D4

dlabel D_8008A8D4
    /* 7B0D4 8008A8D4 */ .asciz ".VB"
    /* 2E564200 */
.align 2
enddlabel D_8008A8D4

nonmatching D_8008A8D8

dlabel D_8008A8D8
    /* 7B0D8 8008A8D8 00000000 */ .word 0x00000000
enddlabel D_8008A8D8

nonmatching D_8008A8DC

dlabel D_8008A8DC
    /* 7B0DC 8008A8DC 00000000 */ .word 0x00000000
enddlabel D_8008A8DC

nonmatching D_8008A8E0

dlabel D_8008A8E0
    /* 7B0E0 8008A8E0 40010000 */ .word 0x00000140
    /* 7B0E4 8008A8E4 F0000000 */ .word 0x000000F0
enddlabel D_8008A8E0

nonmatching D_8008A8E8

dlabel D_8008A8E8
    /* 7B0E8 8008A8E8 40010000 */ .word 0x00000140
    /* 7B0EC 8008A8EC F0000000 */ .word 0x000000F0
enddlabel D_8008A8E8

.align 2
nonmatching D_8008A8F0

dlabel D_8008A8F0
    /* 7B0F0 8008A8F0 */ .asciz "  @"
    /* 20204000 */
.align 2
enddlabel D_8008A8F0

nonmatching D_8008A8F4

dlabel D_8008A8F4
    /* 7B0F4 8008A8F4 00000100 */ .word 0x00010000
enddlabel D_8008A8F4

nonmatching D_8008A8F8

dlabel D_8008A8F8
    /* 7B0F8 8008A8F8 00000000 */ .word 0x00000000
enddlabel D_8008A8F8

nonmatching D_8008A8FC

dlabel D_8008A8FC
    /* 7B0FC 8008A8FC 00010000 */ .word 0x00000100
enddlabel D_8008A8FC

nonmatching D_8008A900

dlabel D_8008A900
    /* 7B100 8008A900 F0000000 */ .word 0x000000F0
enddlabel D_8008A900

nonmatching D_8008A904

dlabel D_8008A904
    /* 7B104 8008A904 9CFFFFFF */ .word 0xFFFFFF9C
    /* 7B108 8008A908 9CFFFFFF */ .word 0xFFFFFF9C
enddlabel D_8008A904

nonmatching D_8008A90C

dlabel D_8008A90C
    /* 7B10C 8008A90C 40010000 */ .word 0x00000140
    /* 7B110 8008A910 F0000000 */ .word 0x000000F0
    /* 7B114 8008A914 0A000000 */ .word 0x0000000A
    /* 7B118 8008A918 0A000000 */ .word 0x0000000A
    /* 7B11C 8008A91C F6FFFFFF */ .word 0xFFFFFFF6
    /* 7B120 8008A920 F6FFFFFF */ .word 0xFFFFFFF6
enddlabel D_8008A90C

nonmatching D_8008A924

dlabel D_8008A924
    /* 7B124 8008A924 80808000 */ .word 0x00808080
enddlabel D_8008A924

.align 2
nonmatching D_8008A928

dlabel D_8008A928
    /* 7B128 8008A928 */ .asciz "%d"
    /* 25640000 */
.align 2
enddlabel D_8008A928

nonmatching D_8008A92C

dlabel D_8008A92C
    /* 7B12C 8008A92C */ .short 0x0003
    /* 7B12E 8008A92E */ .short 0xFFFF
    /* 7B130 8008A930 */ .short 0x00FF
    /* 7B132 8008A932 */ .short 0x0000
enddlabel D_8008A92C

nonmatching D_8008A934

dlabel D_8008A934
    /* 7B134 8008A934 */ .short 0x0003
    /* 7B136 8008A936 */ .short 0x0000
enddlabel D_8008A934

nonmatching D_8008A938

dlabel D_8008A938
    /* 7B138 8008A938 80808000 */ .word 0x00808080
enddlabel D_8008A938

nonmatching D_8008A93C

dlabel D_8008A93C
    /* 7B13C 8008A93C 00000000 */ .word 0x00000000
enddlabel D_8008A93C

nonmatching D_8008A940

dlabel D_8008A940
    /* 7B140 8008A940 00000000 */ .word 0x00000000
enddlabel D_8008A940

nonmatching D_8008A944

dlabel D_8008A944
    /* 7B144 8008A944 00000000 */ .word 0x00000000
enddlabel D_8008A944

nonmatching D_8008A948

dlabel D_8008A948
    /* 7B148 8008A948 01000000 */ .word 0x00000001
enddlabel D_8008A948

nonmatching D_8008A94C

dlabel D_8008A94C
    /* 7B14C 8008A94C 00000000 */ .word 0x00000000
enddlabel D_8008A94C

nonmatching D_8008A950

dlabel D_8008A950
    /* 7B150 8008A950 00000000 */ .word 0x00000000
enddlabel D_8008A950

.align 2
nonmatching D_8008A954

dlabel D_8008A954
    /* 7B154 8008A954 */ .asciz ";1"
    /* 3B310000 */
.align 2
enddlabel D_8008A954

.align 2
nonmatching D_8008A958

dlabel D_8008A958
    /* 7B158 8008A958 */ .asciz "CDI\\"
    /* 4344495C00000000 */
.align 2
enddlabel D_8008A958

nonmatching D_8008A960

dlabel D_8008A960
    /* 7B160 8008A960 58A90880 */ .word D_8008A958
enddlabel D_8008A960

nonmatching D_8008A964

dlabel D_8008A964
    /* 7B164 8008A964 00000000 */ .word 0x00000000
enddlabel D_8008A964

nonmatching D_8008A968

dlabel D_8008A968
    /* 7B168 8008A968 00000000 */ .word 0x00000000
enddlabel D_8008A968

nonmatching D_8008A96C

dlabel D_8008A96C
    /* 7B16C 8008A96C 70A90880 */ .word D_8008A970
enddlabel D_8008A96C

.align 2
nonmatching D_8008A970

dlabel D_8008A970
    /* 7B170 8008A970 */ .asciz "SND\\SE"
    /* 534E445C53450000 */
.align 2
enddlabel D_8008A970

nonmatching D_8008A978

dlabel D_8008A978
    /* 7B178 8008A978 00000000 */ .word 0x00000000
enddlabel D_8008A978

nonmatching D_8008A97C

dlabel D_8008A97C
    /* 7B17C 8008A97C 00000000 */ .word 0x00000000
enddlabel D_8008A97C

nonmatching D_8008A980

dlabel D_8008A980
    /* 7B180 8008A980 00A00000 */ .word 0x0000A000
enddlabel D_8008A980

.align 2
nonmatching D_8008A984

dlabel D_8008A984
    /* 7B184 8008A984 */ .asciz "On"
    /* 4F6E0000 */
.align 2
enddlabel D_8008A984

.align 2
nonmatching D_8008A988

dlabel D_8008A988
    /* 7B188 8008A988 */ .asciz "Off"
    /* 4F666600 */
.align 2
enddlabel D_8008A988

.align 2
nonmatching D_8008A98C

dlabel D_8008A98C
    /* 7B18C 8008A98C */ .asciz "SHAKE"
    /* 5348414B45000000 */
.align 2
enddlabel D_8008A98C

.align 2
nonmatching D_8008A994

dlabel D_8008A994
    /* 7B194 8008A994 */ .asciz "GRAPH"
    /* 4752415048000000 */
.align 2
enddlabel D_8008A994

.align 2
nonmatching D_8008A99C

dlabel D_8008A99C
    /* 7B19C 8008A99C */ .asciz "LOAD"
    /* 4C4F414400000000 */
.align 2
enddlabel D_8008A99C

.align 2
nonmatching D_8008A9A4

dlabel D_8008A9A4
    /* 7B1A4 8008A9A4 */ .asciz "SAVE"
    /* 5341564500000000 */
.align 2
enddlabel D_8008A9A4

.align 2
nonmatching D_8008A9AC

dlabel D_8008A9AC
    /* 7B1AC 8008A9AC */ .asciz "START"
    /* 5354415254000000 */
.align 2
enddlabel D_8008A9AC

nonmatching D_8008A9B4

dlabel D_8008A9B4
    /* 7B1B4 8008A9B4 FCFFFFFF */ .word 0xFFFFFFFC
    /* 7B1B8 8008A9B8 E9FFFFFF */ .word 0xFFFFFFE9
    /* 7B1BC 8008A9BC C2FFFFFF */ .word 0xFFFFFFC2
    /* 7B1C0 8008A9C0 B0FFFFFF */ .word 0xFFFFFFB0
    /* 7B1C4 8008A9C4 EAFFFFFF */ .word 0xFFFFFFEA
    /* 7B1C8 8008A9C8 B0FFFFFF */ .word 0xFFFFFFB0
    /* 7B1CC 8008A9CC FFFF0000 */ .word 0x0000FFFF
enddlabel D_8008A9B4

nonmatching D_8008A9D0

dlabel D_8008A9D0
    /* 7B1D0 8008A9D0 54140180 */ .word 0x80011454
enddlabel D_8008A9D0

.align 2
nonmatching D_8008A9D4

dlabel D_8008A9D4
    /* 7B1D4 8008A9D4 */ .asciz "-15"
    /* 2D313500 */
.align 2
enddlabel D_8008A9D4

.align 2
nonmatching D_8008A9D8

dlabel D_8008A9D8
    /* 7B1D8 8008A9D8 */ .asciz "-14"
    /* 2D313400 */
.align 2
enddlabel D_8008A9D8

.align 2
nonmatching D_8008A9DC

dlabel D_8008A9DC
    /* 7B1DC 8008A9DC */ .asciz "-13"
    /* 2D313300 */
.align 2
enddlabel D_8008A9DC

.align 2
nonmatching D_8008A9E0

dlabel D_8008A9E0
    /* 7B1E0 8008A9E0 */ .asciz "-12"
    /* 2D313200 */
.align 2
enddlabel D_8008A9E0

.align 2
nonmatching D_8008A9E4

dlabel D_8008A9E4
    /* 7B1E4 8008A9E4 */ .asciz "-11"
    /* 2D313100 */
.align 2
enddlabel D_8008A9E4

.align 2
nonmatching D_8008A9E8

dlabel D_8008A9E8
    /* 7B1E8 8008A9E8 */ .asciz "-10"
    /* 2D313000 */
.align 2
enddlabel D_8008A9E8

.align 2
nonmatching D_8008A9EC

dlabel D_8008A9EC
    /* 7B1EC 8008A9EC */ .asciz "-09"
    /* 2D303900 */
.align 2
enddlabel D_8008A9EC

.align 2
nonmatching D_8008A9F0

dlabel D_8008A9F0
    /* 7B1F0 8008A9F0 */ .asciz "-08"
    /* 2D303800 */
.align 2
enddlabel D_8008A9F0

.align 2
nonmatching D_8008A9F4

dlabel D_8008A9F4
    /* 7B1F4 8008A9F4 */ .asciz "-07"
    /* 2D303700 */
.align 2
enddlabel D_8008A9F4

.align 2
nonmatching D_8008A9F8

dlabel D_8008A9F8
    /* 7B1F8 8008A9F8 */ .asciz "-06"
    /* 2D303600 */
.align 2
enddlabel D_8008A9F8

.align 2
nonmatching D_8008A9FC

dlabel D_8008A9FC
    /* 7B1FC 8008A9FC */ .asciz "-05"
    /* 2D303500 */
.align 2
enddlabel D_8008A9FC

.align 2
nonmatching D_8008AA00

dlabel D_8008AA00
    /* 7B200 8008AA00 */ .asciz "-04"
    /* 2D303400 */
.align 2
enddlabel D_8008AA00

.align 2
nonmatching D_8008AA04

dlabel D_8008AA04
    /* 7B204 8008AA04 */ .asciz "-03"
    /* 2D303300 */
.align 2
enddlabel D_8008AA04

.align 2
nonmatching D_8008AA08

dlabel D_8008AA08
    /* 7B208 8008AA08 */ .asciz "-02"
    /* 2D303200 */
.align 2
enddlabel D_8008AA08

.align 2
nonmatching D_8008AA0C

dlabel D_8008AA0C
    /* 7B20C 8008AA0C */ .asciz "-01"
    /* 2D303100 */
.align 2
enddlabel D_8008AA0C

nonmatching D_8008AA10

dlabel D_8008AA10
    /* 7B210 8008AA10 64140180 */ .word 0x80011464
enddlabel D_8008AA10

nonmatching D_8008AA14

dlabel D_8008AA14
    /* 7B214 8008AA14 74140180 */ .word 0x80011474
enddlabel D_8008AA14

nonmatching D_8008AA18

dlabel D_8008AA18
    /* 7B218 8008AA18 9C140180 */ .word 0x8001149C
enddlabel D_8008AA18

.align 2
nonmatching D_8008AA1C

dlabel D_8008AA1C
    /* 7B21C 8008AA1C */ .asciz "7654321"
    /* 3736353433323100 */
.align 2
enddlabel D_8008AA1C

nonmatching D_8008AA24

dlabel D_8008AA24
    /* 7B224 8008AA24 1CAA0880 */ .word D_8008AA1C
enddlabel D_8008AA24

nonmatching D_8008AA28

dlabel D_8008AA28
    /* 7B228 8008AA28 00000000 */ .word 0x00000000
enddlabel D_8008AA28

nonmatching D_8008AA2C

dlabel D_8008AA2C
    /* 7B22C 8008AA2C 00000000 */ .word 0x00000000
enddlabel D_8008AA2C

nonmatching D_8008AA30

dlabel D_8008AA30
    /* 7B230 8008AA30 00000000 */ .word 0x00000000
enddlabel D_8008AA30

.align 2
nonmatching D_8008AA34

dlabel D_8008AA34
    /* 7B234 8008AA34 */ .asciz "LOADERR"
    /* 4C4F414445525200 */
.align 2
enddlabel D_8008AA34

.align 2
nonmatching D_8008AA3C

dlabel D_8008AA3C
    /* 7B23C 8008AA3C */ .asciz "LOADING"
    /* 4C4F4144494E4700 */
.align 2
enddlabel D_8008AA3C

.align 2
nonmatching D_8008AA44

dlabel D_8008AA44
    /* 7B244 8008AA44 */ .asciz "LOADWAR"
    /* 4C4F414457415200 */
.align 2
enddlabel D_8008AA44

.align 2
nonmatching D_8008AA4C

dlabel D_8008AA4C
    /* 7B24C 8008AA4C */ .asciz "SAVEERR"
    /* 5341564545525200 */
.align 2
enddlabel D_8008AA4C

.align 2
nonmatching D_8008AA54

dlabel D_8008AA54
    /* 7B254 8008AA54 */ .asciz "SAVING"
    /* 534156494E470000 */
.align 2
enddlabel D_8008AA54

.align 2
nonmatching D_8008AA5C

dlabel D_8008AA5C
    /* 7B25C 8008AA5C */ .asciz "SAVEWAR"
    /* 5341564557415200 */
.align 2
enddlabel D_8008AA5C

.align 2
nonmatching D_8008AA64

dlabel D_8008AA64
    /* 7B264 8008AA64 */ .asciz "FORMERR"
    /* 464F524D45525200 */
.align 2
enddlabel D_8008AA64

.align 2
nonmatching D_8008AA6C

dlabel D_8008AA6C
    /* 7B26C 8008AA6C */ .asciz "FORMING"
    /* 464F524D494E4700 */
.align 2
enddlabel D_8008AA6C

.align 2
nonmatching D_8008AA74

dlabel D_8008AA74
    /* 7B274 8008AA74 */ .asciz "UNFORM2"
    /* 554E464F524D3200 */
.align 2
enddlabel D_8008AA74

.align 2
nonmatching D_8008AA7C

dlabel D_8008AA7C
    /* 7B27C 8008AA7C */ .asciz "UNFORM1"
    /* 554E464F524D3100 */
.align 2
enddlabel D_8008AA7C

.align 2
nonmatching D_8008AA84

dlabel D_8008AA84
    /* 7B284 8008AA84 */ .asciz "CHANGE"
    /* 4348414E47450000 */
.align 2
enddlabel D_8008AA84

.align 2
nonmatching D_8008AA8C

dlabel D_8008AA8C
    /* 7B28C 8008AA8C */ .asciz "ERROR"
    /* 4552524F52000000 */
.align 2
enddlabel D_8008AA8C

nonmatching D_8008AA94

dlabel D_8008AA94
    /* 7B294 8008AA94 BAFFFFFF */ .word 0xFFFFFFBA
    /* 7B298 8008AA98 C4FFFFFF */ .word 0xFFFFFFC4
enddlabel D_8008AA94

.align 2
nonmatching D_8008AA9C

dlabel D_8008AA9C
    /* 7B29C 8008AA9C */ .asciz "bu10:"
    /* 627531303A000000 */
.align 2
enddlabel D_8008AA9C

.align 2
nonmatching D_8008AAA4

dlabel D_8008AAA4
    /* 7B2A4 8008AAA4 */ .asciz "bu00:"
    /* 627530303A000000 */
.align 2
enddlabel D_8008AAA4

.align 2
nonmatching D_8008AAAC

dlabel D_8008AAAC
    /* 7B2AC 8008AAAC */ .asciz "TEMP"
    /* 54454D5000000000 */
.align 2
enddlabel D_8008AAAC

.align 2
nonmatching D_8008AAB4

dlabel D_8008AAB4
    /* 7B2B4 8008AAB4 */ .asciz "CARD\\"
    /* 434152445C000000 */
.align 2
enddlabel D_8008AAB4

.align 2
nonmatching D_8008AABC

dlabel D_8008AABC
    /* 7B2BC 8008AABC */ .asciz ".TIM"
    /* 2E54494D00000000 */
.align 2
enddlabel D_8008AABC

nonmatching D_8008AAC4

dlabel D_8008AAC4
    /* 7B2C4 8008AAC4 50150180 */ .word 0x80011550
enddlabel D_8008AAC4

nonmatching D_8008AAC8

dlabel D_8008AAC8
    /* 7B2C8 8008AAC8 80800000 */ .word 0x00008080
enddlabel D_8008AAC8

nonmatching D_8008AACC

dlabel D_8008AACC
    /* 7B2CC 8008AACC BAFFFFFF */ .word 0xFFFFFFBA
    /* 7B2D0 8008AAD0 C4FFFFFF */ .word 0xFFFFFFC4
enddlabel D_8008AACC

nonmatching D_8008AAD4

dlabel D_8008AAD4
    /* 7B2D4 8008AAD4 C2FFFFFF */ .word 0xFFFFFFC2
    /* 7B2D8 8008AAD8 F1FFFFFF */ .word 0xFFFFFFF1
enddlabel D_8008AAD4

nonmatching D_8008AADC

dlabel D_8008AADC
    /* 7B2DC 8008AADC C2FFFFFF */ .word 0xFFFFFFC2
enddlabel D_8008AADC

nonmatching D_8008AAE0

dlabel D_8008AAE0
    /* 7B2E0 8008AAE0 F4FFFFFF */ .word 0xFFFFFFF4
enddlabel D_8008AAE0

nonmatching D_8008AAE4

dlabel D_8008AAE4
    /* 7B2E4 8008AAE4 D0150180 */ .word D_800115D0
enddlabel D_8008AAE4

.align 2
nonmatching D_8008AAE8

dlabel D_8008AAE8
    /* 7B2E8 8008AAE8 */ .asciz "CARD\\"
    /* 434152445C000000 */
.align 2
enddlabel D_8008AAE8

.align 2
nonmatching D_8008AAF0

dlabel D_8008AAF0
    /* 7B2F0 8008AAF0 */ .asciz ".TIM"
    /* 2E54494D00000000 */
.align 2
enddlabel D_8008AAF0

nonmatching D_8008AAF8

dlabel D_8008AAF8
    /* 7B2F8 8008AAF8 9CFFFFFF */ .word 0xFFFFFF9C
    /* 7B2FC 8008AAFC C4FFFFFF */ .word 0xFFFFFFC4
enddlabel D_8008AAF8

nonmatching D_8008AB00

dlabel D_8008AB00
    /* 7B300 8008AB00 A4FFFFFF */ .word 0xFFFFFFA4
enddlabel D_8008AB00

nonmatching D_8008AB04

dlabel D_8008AB04
    /* 7B304 8008AB04 F1FFFFFF */ .word 0xFFFFFFF1
    /* 7B308 8008AB08 A4160180 */ .word D_800116A4
enddlabel D_8008AB04

.align 2
nonmatching D_8008AB0C

dlabel D_8008AB0C
    /* 7B30C 8008AB0C */ .asciz "PPP"
    /* 50505000 */
.align 2
enddlabel D_8008AB0C

nonmatching D_8008AB10

dlabel D_8008AB10
    /* 7B310 8008AB10 80800000 */ .word 0x00008080
enddlabel D_8008AB10

.align 2
nonmatching D_8008AB14

dlabel D_8008AB14
    /* 7B314 8008AB14 */ .asciz "SELECT"
    /* 53454C4543540000 */
.align 2
enddlabel D_8008AB14

.align 2
nonmatching D_8008AB1C

dlabel D_8008AB1C
    /* 7B31C 8008AB1C */ .asciz "CARD\\"
    /* 434152445C000000 */
.align 2
enddlabel D_8008AB1C

.align 2
nonmatching D_8008AB24

dlabel D_8008AB24
    /* 7B324 8008AB24 */ .asciz ".TIM"
    /* 2E54494D00000000 */
.align 2
    /* 7B32C 8008AB2C 00A00000 */ .word 0x0000A000
    /* 7B330 8008AB30 00A00000 */ .word 0x0000A000
enddlabel D_8008AB24

nonmatching D_8008AB34

dlabel D_8008AB34
    /* 7B334 8008AB34 00000000 */ .word 0x00000000
enddlabel D_8008AB34

nonmatching D_8008AB38

dlabel D_8008AB38
    /* 7B338 8008AB38 ECFFFFFF */ .word 0xFFFFFFEC
    /* 7B33C 8008AB3C CEFFFFFF */ .word 0xFFFFFFCE
enddlabel D_8008AB38

nonmatching D_8008AB40

dlabel D_8008AB40
    /* 7B340 8008AB40 FF000000 */ .word 0x000000FF
enddlabel D_8008AB40

.align 2
nonmatching D_8008AB44

dlabel D_8008AB44
    /* 7B344 8008AB44 */ .asciz "Pause"
    /* 5061757365000000 */
.align 2
enddlabel D_8008AB44

nonmatching D_8008AB4C

dlabel D_8008AB4C
    /* 7B34C 8008AB4C 00000000 */ .word 0x00000000
enddlabel D_8008AB4C

nonmatching D_8008AB50

dlabel D_8008AB50
    /* 7B350 8008AB50 00000000 */ .word 0x00000000
enddlabel D_8008AB50

nonmatching gSpawnObj1Active

dlabel gSpawnObj1Active
    /* 7B354 8008AB54 00000000 */ .word 0x00000000
enddlabel gSpawnObj1Active

nonmatching D_8008AB58

dlabel D_8008AB58
    /* 7B358 8008AB58 9CFFFFFF */ .word 0xFFFFFF9C
    /* 7B35C 8008AB5C 9CFFFFFF */ .word 0xFFFFFF9C
enddlabel D_8008AB58

nonmatching D_8008AB60

dlabel D_8008AB60
    /* 7B360 8008AB60 40010000 */ .word 0x00000140
    /* 7B364 8008AB64 F0000000 */ .word 0x000000F0
enddlabel D_8008AB60

nonmatching D_8008AB68

dlabel D_8008AB68
    /* 7B368 8008AB68 9CFFFFFF */ .word 0xFFFFFF9C
enddlabel D_8008AB68

nonmatching D_8008AB6C

dlabel D_8008AB6C
    /* 7B36C 8008AB6C C4FFFFFF */ .word 0xFFFFFFC4
enddlabel D_8008AB6C

nonmatching D_8008AB70

dlabel D_8008AB70
    /* 7B370 8008AB70 40010000 */ .word 0x00000140
enddlabel D_8008AB70

nonmatching D_8008AB74

dlabel D_8008AB74
    /* 7B374 8008AB74 90000000 */ .word 0x00000090
enddlabel D_8008AB74

nonmatching D_8008AB78

dlabel D_8008AB78
    /* 7B378 8008AB78 80808000 */ .word 0x00808080
enddlabel D_8008AB78

nonmatching D_8008AB7C

dlabel D_8008AB7C
    /* 7B37C 8008AB7C 80808000 */ .word 0x00808080
enddlabel D_8008AB7C

nonmatching D_8008AB80

dlabel D_8008AB80
    /* 7B380 8008AB80 00000000 */ .word 0x00000000
enddlabel D_8008AB80

nonmatching D_8008AB84

dlabel D_8008AB84
    /* 7B384 8008AB84 00000000 */ .word 0x00000000
    /* 7B388 8008AB88 0002030C */ .word 0x0C030200
enddlabel D_8008AB84

nonmatching D_8008AB8C

dlabel D_8008AB8C
    /* 7B38C 8008AB8C 00020B0B */ .word 0x0B0B0200
enddlabel D_8008AB8C

nonmatching D_8008AB90

dlabel D_8008AB90
    /* 7B390 8008AB90 00020303 */ .word 0x03030200
enddlabel D_8008AB90

nonmatching D_8008AB94

dlabel D_8008AB94
    /* 7B394 8008AB94 F003FF01 */ .word 0x01FF03F0
enddlabel D_8008AB94

nonmatching D_8008AB98

dlabel D_8008AB98
    /* 7B398 8008AB98 00000000 */ .word 0x00000000
    /* 7B39C 8008AB9C 02000000 */ .word 0x00000002
    /* 7B3A0 8008ABA0 FFFF8000 */ .word 0x0080FFFF
enddlabel D_8008AB98

nonmatching gAnimSetTable7

dlabel gAnimSetTable7
    /* 7B3A4 8008ABA4 00000000 */ .word 0x00000000
enddlabel gAnimSetTable7

nonmatching gAnimSetTable6

dlabel gAnimSetTable6
    /* 7B3A8 8008ABA8 00000000 */ .word 0x00000000
enddlabel gAnimSetTable6

.align 2
nonmatching D_8008ABAC

dlabel D_8008ABAC
    /* 7B3AC 8008ABAC */ .asciz "\n"
    /* 0A000000 */
.align 2
.align 2
    /* 7B3B0 8008ABB0 */ .asciz "\n"
    /* 0A000000 */
.align 2
enddlabel D_8008ABAC

nonmatching D_8008ABB4

dlabel D_8008ABB4
    /* 7B3B4 8008ABB4 FF000000 */ .word 0x000000FF
enddlabel D_8008ABB4

nonmatching D_8008ABB8

dlabel D_8008ABB8
    /* 7B3B8 8008ABB8 FFFFFF00 */ .word 0x00FFFFFF
enddlabel D_8008ABB8

nonmatching D_8008ABBC

dlabel D_8008ABBC
    /* 7B3BC 8008ABBC 00FF0000 */ .word 0x0000FF00
enddlabel D_8008ABBC
