.include "macro.inc"

.section .sdata, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching gEntityStageId

dlabel gEntityStageId
    /* 7B3F8 8008ABF8 FFFFFFFF */ .word 0xFFFFFFFF
enddlabel gEntityStageId

nonmatching gEntityStageArg1

dlabel gEntityStageArg1
    /* 7B3FC 8008ABFC 00000000 */ .word 0x00000000
enddlabel gEntityStageArg1

nonmatching gpStageContextObj

dlabel gpStageContextObj
    /* 7B400 8008AC00 00000000 */ .word 0x00000000
enddlabel gpStageContextObj

nonmatching gEntityStageArg3

dlabel gEntityStageArg3
    /* 7B404 8008AC04 00000000 */ .word 0x00000000
enddlabel gEntityStageArg3

nonmatching gEntityStageArg4

dlabel gEntityStageArg4
    /* 7B408 8008AC08 00000000 */ .word 0x00000000
enddlabel gEntityStageArg4

nonmatching D_8008AC0C

dlabel D_8008AC0C
    /* 7B40C 8008AC0C 9CFFFFFF */ .word 0xFFFFFF9C
    /* 7B410 8008AC10 9CFFFFFF */ .word 0xFFFFFF9C
enddlabel D_8008AC0C

nonmatching D_8008AC14

dlabel D_8008AC14
    /* 7B414 8008AC14 40010000 */ .word 0x00000140
    /* 7B418 8008AC18 F0000000 */ .word 0x000000F0
enddlabel D_8008AC14

nonmatching D_8008AC1C

dlabel D_8008AC1C
    /* 7B41C 8008AC1C 0064BE00 */ .word 0x00BE6400
enddlabel D_8008AC1C
