.include "macro.inc"

.section .sbss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching gpSceneMgr

dlabel gpSceneMgr
    /* 7B420 8008AC20 00000000 */ .word 0x00000000
    /* 7B424 8008AC24 00000000 */ .word 0x00000000
enddlabel gpSceneMgr

nonmatching D_8008AC28

dlabel D_8008AC28
    /* 7B428 8008AC28 00000000 */ .word 0x00000000
    /* 7B42C 8008AC2C 00000000 */ .word 0x00000000
enddlabel D_8008AC28

nonmatching D_8008AC30

dlabel D_8008AC30
    /* 7B430 8008AC30 00000000 */ .word 0x00000000
    /* 7B434 8008AC34 00000000 */ .word 0x00000000
enddlabel D_8008AC30

nonmatching D_8008AC38

dlabel D_8008AC38
    /* 7B438 8008AC38 00000000 */ .word 0x00000000
    /* 7B43C 8008AC3C 00000000 */ .word 0x00000000
enddlabel D_8008AC38

nonmatching D_8008AC40

dlabel D_8008AC40
    /* 7B440 8008AC40 00000000 */ .word 0x00000000
    /* 7B444 8008AC44 00000000 */ .word 0x00000000
enddlabel D_8008AC40

nonmatching D_8008AC48

dlabel D_8008AC48
    /* 7B448 8008AC48 00000000 */ .word 0x00000000
enddlabel D_8008AC48

nonmatching D_8008AC4C

dlabel D_8008AC4C
    /* 7B44C 8008AC4C 00000000 */ .word 0x00000000
enddlabel D_8008AC4C

nonmatching D_8008AC50

dlabel D_8008AC50
    /* 7B450 8008AC50 00000000 */ .word 0x00000000
    /* 7B454 8008AC54 00000000 */ .word 0x00000000
    /* 7B458 8008AC58 00000000 */ .word 0x00000000
    /* 7B45C 8008AC5C 00000000 */ .word 0x00000000
    /* 7B460 8008AC60 00000000 */ .word 0x00000000
    /* 7B464 8008AC64 00000000 */ .word 0x00000000
enddlabel D_8008AC50
