.include "macro.inc"

.section .sbss, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching gLinkTypeId

dlabel gLinkTypeId
    /* 7B46C 8008AC6C 00000000 */ .word 0x00000000
enddlabel gLinkTypeId

nonmatching D_8008AC70

dlabel D_8008AC70
    /* 7B470 8008AC70 00000000 */ .word 0x00000000
enddlabel D_8008AC70

nonmatching D_8008AC74

dlabel D_8008AC74
    /* 7B474 8008AC74 00000000 */ .word 0x00000000
enddlabel D_8008AC74

nonmatching D_8008AC78

dlabel D_8008AC78
    /* 7B478 8008AC78 00000000 */ .word 0x00000000
enddlabel D_8008AC78

nonmatching gSpawnListHead

dlabel gSpawnListHead
    /* 7B47C 8008AC7C 00000000 */ .word 0x00000000
enddlabel gSpawnListHead

nonmatching gSpawnCounter

dlabel gSpawnCounter
    /* 7B480 8008AC80 00000000 */ .word 0x00000000
enddlabel gSpawnCounter

nonmatching D_8008AC84

dlabel D_8008AC84
    /* 7B484 8008AC84 00000000 */ .word 0x00000000
enddlabel D_8008AC84

nonmatching gSpawnCounterBufSize

dlabel gSpawnCounterBufSize
    /* 7B488 8008AC88 00000000 */ .word 0x00000000
enddlabel gSpawnCounterBufSize

nonmatching D_8008AC8C

dlabel D_8008AC8C
    /* 7B48C 8008AC8C 00000000 */ .word 0x00000000
enddlabel D_8008AC8C

nonmatching D_8008AC90

dlabel D_8008AC90
    /* 7B490 8008AC90 00000000 */ .word 0x00000000
enddlabel D_8008AC90

nonmatching gSpawnObj1

dlabel gSpawnObj1
    /* 7B494 8008AC94 00000000 */ .word 0x00000000
enddlabel gSpawnObj1

nonmatching D_8008AC98

dlabel D_8008AC98
    /* 7B498 8008AC98 00000000 */ .word 0x00000000
enddlabel D_8008AC98

nonmatching D_8008AC9C

dlabel D_8008AC9C
    /* 7B49C 8008AC9C 00000000 */ .word 0x00000000
enddlabel D_8008AC9C

nonmatching D_8008ACA0

dlabel D_8008ACA0
    /* 7B4A0 8008ACA0 00000000 */ .word 0x00000000
enddlabel D_8008ACA0

nonmatching D_8008ACA4

dlabel D_8008ACA4
    /* 7B4A4 8008ACA4 00000000 */ .word 0x00000000
enddlabel D_8008ACA4

nonmatching D_8008ACA8

dlabel D_8008ACA8
    /* 7B4A8 8008ACA8 00000000 */ .word 0x00000000
enddlabel D_8008ACA8

nonmatching D_8008ACAC

dlabel D_8008ACAC
    /* 7B4AC 8008ACAC 00000000 */ .word 0x00000000
enddlabel D_8008ACAC

nonmatching D_8008ACB0

dlabel D_8008ACB0
    /* 7B4B0 8008ACB0 00000000 */ .word 0x00000000
enddlabel D_8008ACB0
