.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 2
nonmatching D_8001028C

dlabel D_8001028C
    /* A8C 8001028C */ .asciz "bMemPMgr = %p, poolSize = %ld in BMemPMgrInit\n"
    /* 624D656D504D6772203D2025702C20706F6F6C53697A65203D20256C6420696E20424D656D504D6772496E69740A0000 */
.align 2
enddlabel D_8001028C
