.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 2
nonmatching D_800102BC

dlabel D_800102BC
    /* ABC 800102BC */ .asciz "GPU CODE %02xH not assigned.\n"
    /* 47505520434F4445202530327848206E6F742061737369676E65642E0A000000 */
.align 2
enddlabel D_800102BC

.align 3
nonmatching jtbl_800102DC

dlabel jtbl_800102DC
    /* ADC 800102DC 1CF00180 */ .word .L8001F01C
    /* AE0 800102E0 5CF00180 */ .word .L8001F05C
    /* AE4 800102E4 7CF00180 */ .word .L8001F07C
    /* AE8 800102E8 7CF00180 */ .word .L8001F07C
    /* AEC 800102EC 30F00180 */ .word .L8001F030
    /* AF0 800102F0 4CF00180 */ .word .L8001F04C
    /* AF4 800102F4 7CF00180 */ .word .L8001F07C
    /* AF8 800102F8 7CF00180 */ .word .L8001F07C
    /* AFC 800102FC 54F00180 */ .word .L8001F054
    /* B00 80010300 5CF00180 */ .word .L8001F05C
    /* B04 80010304 7CF00180 */ .word .L8001F07C
    /* B08 80010308 7CF00180 */ .word .L8001F07C
    /* B0C 8001030C 64F00180 */ .word .L8001F064
    /* B10 80010310 64F00180 */ .word .L8001F064
    /* B14 80010314 7CF00180 */ .word .L8001F07C
    /* B18 80010318 7CF00180 */ .word .L8001F07C
    /* B1C 8001031C 38F00180 */ .word .L8001F038
    /* B20 80010320 30F00180 */ .word .L8001F030
    /* B24 80010324 7CF00180 */ .word .L8001F07C
    /* B28 80010328 7CF00180 */ .word .L8001F07C
    /* B2C 8001032C 4CF00180 */ .word .L8001F04C
    /* B30 80010330 74F00180 */ .word .L8001F074
    /* B34 80010334 7CF00180 */ .word .L8001F07C
    /* B38 80010338 7CF00180 */ .word .L8001F07C
    /* B3C 8001033C 30F00180 */ .word .L8001F030
    /* B40 80010340 4CF00180 */ .word .L8001F04C
    /* B44 80010344 7CF00180 */ .word .L8001F07C
    /* B48 80010348 7CF00180 */ .word .L8001F07C
    /* B4C 8001034C 74F00180 */ .word .L8001F074
    /* B50 80010350 6CF00180 */ .word .L8001F06C
enddlabel jtbl_800102DC

.align 3
nonmatching jtbl_80010354

dlabel jtbl_80010354
    /* B54 80010354 D0000280 */ .word .L800200D0
    /* B58 80010358 2C010280 */ .word .L8002012C
    /* B5C 8001035C D0000280 */ .word .L800200D0
    /* B60 80010360 2C010280 */ .word .L8002012C
    /* B64 80010364 50010280 */ .word .L80020150
    /* B68 80010368 74010280 */ .word .L80020174
    /* B6C 8001036C 50010280 */ .word .L80020150
    /* B70 80010370 74010280 */ .word .L80020174
    /* B74 80010374 98010280 */ .word .L80020198
    /* B78 80010378 0C020280 */ .word .L8002020C
    /* B7C 8001037C 98010280 */ .word .L80020198
    /* B80 80010380 0C020280 */ .word .L8002020C
    /* B84 80010384 40020280 */ .word .L80020240
    /* B88 80010388 70020280 */ .word .L80020270
    /* B8C 8001038C 40020280 */ .word .L80020240
    /* B90 80010390 70020280 */ .word .L80020270
    /* B94 80010394 A4020280 */ .word .L800202A4
    /* B98 80010398 00030280 */ .word .L80020300
    /* B9C 8001039C A4020280 */ .word .L800202A4
    /* BA0 800103A0 00030280 */ .word .L80020300
    /* BA4 800103A4 24030280 */ .word .L80020324
    /* BA8 800103A8 48030280 */ .word .L80020348
    /* BAC 800103AC 24030280 */ .word .L80020324
    /* BB0 800103B0 48030280 */ .word .L80020348
    /* BB4 800103B4 78030280 */ .word .L80020378
    /* BB8 800103B8 BC030280 */ .word .L800203BC
    /* BBC 800103BC 78030280 */ .word .L80020378
    /* BC0 800103C0 BC030280 */ .word .L800203BC
    /* BC4 800103C4 F0030280 */ .word .L800203F0
    /* BC8 800103C8 24040280 */ .word .L80020424
    /* BCC 800103CC F0030280 */ .word .L800203F0
    /* BD0 800103D0 24040280 */ .word .L80020424
enddlabel jtbl_80010354

.align 2
nonmatching D_800103D4

dlabel D_800103D4
    /* BD4 800103D4 */ .asciz "$Id: sys.c,v 1.116 1995/12/01 07:03:58 suzu Exp $"
    /* 2449643A207379732E632C7620312E31313620313939352F31322F30312030373A30333A35382073757A75204578702024000000 */
.align 2
enddlabel D_800103D4

.align 2
nonmatching D_80010408

dlabel D_80010408
    /* C08 80010408 */ .asciz "ResetGraph:jtb=%08x,env=%08x\n"
    /* 526573657447726170683A6A74623D253038782C656E763D253038780A000000 */
.align 2
enddlabel D_80010408

.align 2
nonmatching D_80010428

dlabel D_80010428
    /* C28 80010428 */ .asciz "ResetGraph(%d)...\n"
    /* 52657365744772617068282564292E2E2E0A0000 */
.align 2
enddlabel D_80010428

.align 2
nonmatching D_8001043C

dlabel D_8001043C
    /* C3C 8001043C */ .asciz "SetGraphReverse(%d)...\n"
    /* 536574477261706852657665727365282564292E2E2E0A00 */
.align 2
enddlabel D_8001043C

.align 2
nonmatching D_80010454

dlabel D_80010454
    /* C54 80010454 */ .asciz "SetGraphDebug:level:%d,type:%d reverse:%d\n"
    /* 536574477261706844656275673A6C6576656C3A25642C747970653A256420726576657273653A25640A0000 */
.align 2
enddlabel D_80010454

.align 2
nonmatching D_80010480

dlabel D_80010480
    /* C80 80010480 */ .asciz "SetGrapQue(%d)...\n"
    /* 53657447726170517565282564292E2E2E0A0000 */
.align 2
enddlabel D_80010480

.align 2
nonmatching D_80010494

dlabel D_80010494
    /* C94 80010494 */ .asciz "DrawSyncCallback(%08x)...\n"
    /* 4472617753796E6343616C6C6261636B2825303878292E2E2E0A0000 */
.align 2
enddlabel D_80010494

.align 2
nonmatching D_800104B0

dlabel D_800104B0
    /* CB0 800104B0 */ .asciz "SetDispMask(%d)...\n"
    /* 536574446973704D61736B282564292E2E2E0A00 */
.align 2
enddlabel D_800104B0

.align 2
nonmatching D_800104C4

dlabel D_800104C4
    /* CC4 800104C4 */ .asciz "DrawSync(%d)...\n"
    /* 4472617753796E63282564292E2E2E0A00000000 */
.align 2
enddlabel D_800104C4

.align 2
nonmatching D_800104D8

dlabel D_800104D8
    /* CD8 800104D8 */ .asciz "%s:bad RECT"
    /* 25733A626164205245435400 */
.align 2
enddlabel D_800104D8

.align 2
nonmatching D_800104E4

dlabel D_800104E4
    /* CE4 800104E4 */ .asciz "(%d,%d)-(%d,%d)\n"
    /* 2825642C2564292D2825642C2564290A00000000 */
.align 2
enddlabel D_800104E4

.align 2
nonmatching D_800104F8

dlabel D_800104F8
    /* CF8 800104F8 */ .asciz "%s:"
    /* 25733A00 */
.align 2
enddlabel D_800104F8

.align 2
nonmatching D_800104FC

dlabel D_800104FC
    /* CFC 800104FC */ .asciz "ClearImage"
    /* 436C656172496D6167650000 */
.align 2
enddlabel D_800104FC

.align 2
nonmatching D_80010508

dlabel D_80010508
    /* D08 80010508 */ .asciz "LoadImage"
    /* 4C6F6164496D616765000000 */
.align 2
enddlabel D_80010508

.align 2
nonmatching D_80010514

dlabel D_80010514
    /* D14 80010514 */ .asciz "StoreImage"
    /* 53746F7265496D6167650000 */
.align 2
enddlabel D_80010514

.align 2
nonmatching D_80010520

dlabel D_80010520
    /* D20 80010520 */ .asciz "MoveImage"
    /* 4D6F7665496D616765000000 */
.align 2
enddlabel D_80010520

.align 2
nonmatching D_8001052C

dlabel D_8001052C
    /* D2C 8001052C */ .asciz "ClearOTag(%08x,%d)...\n"
    /* 436C6561724F54616728253038782C2564292E2E2E0A0000 */
.align 2
enddlabel D_8001052C

.align 2
nonmatching D_80010544

dlabel D_80010544
    /* D44 80010544 */ .asciz "ClearOTagR(%08x,%d)...\n"
    /* 436C6561724F5461675228253038782C2564292E2E2E0A00 */
.align 2
enddlabel D_80010544

.align 2
nonmatching D_8001055C

dlabel D_8001055C
    /* D5C 8001055C */ .asciz "DrawOTag(%08x)...\n"
    /* 447261774F5461672825303878292E2E2E0A0000 */
.align 2
enddlabel D_8001055C

.align 2
nonmatching D_80010570

dlabel D_80010570
    /* D70 80010570 */ .asciz "PutDrawEnv(%08x)...\n"
    /* 50757444726177456E762825303878292E2E2E0A00000000 */
.align 2
enddlabel D_80010570

.align 2
nonmatching D_80010588

dlabel D_80010588
    /* D88 80010588 */ .asciz "PutDispEnv(%08x)...\n"
    /* 50757444697370456E762825303878292E2E2E0A00000000 */
.align 2
enddlabel D_80010588

.align 2
nonmatching D_800105A0

dlabel D_800105A0
    /* DA0 800105A0 */ .asciz "GPU timeout:que=%d,stat=%08x,chcr=%08x,madr=%08x,"
    /* 4750552074696D656F75743A7175653D25642C737461743D253038782C636863723D253038782C6D6164723D253038782C000000 */
.align 2
enddlabel D_800105A0

.align 2
nonmatching D_800105D4

dlabel D_800105D4
    /* DD4 800105D4 */ .asciz "func=(%08x)(%08x,%08x)\n"
    /* 66756E633D28253038782928253038782C25303878290A00 */
.align 2
enddlabel D_800105D4

.align 2
nonmatching D_800105EC

dlabel D_800105EC
    /* DEC 800105EC */ .asciz "tpage: (%d,%d,%d,%d)\n"
    /* 74706167653A202825642C25642C25642C2564290A000000 */
.align 2
enddlabel D_800105EC

.align 2
nonmatching D_80010604

dlabel D_80010604
    /* E04 80010604 */ .asciz "clut: (%d,%d)\n"
    /* 636C75743A202825642C2564290A0000 */
.align 2
enddlabel D_80010604

.align 2
nonmatching D_80010614

dlabel D_80010614
    /* E14 80010614 */ .asciz "clip (%3d,%3d)-(%d,%d)\n"
    /* 636C697020282533642C253364292D2825642C2564290A00 */
.align 2
enddlabel D_80010614

.align 2
nonmatching D_8001062C

dlabel D_8001062C
    /* E2C 8001062C */ .asciz "ofs  (%3d,%3d)\n"
    /* 6F66732020282533642C253364290A00 */
.align 2
enddlabel D_8001062C

.align 2
nonmatching D_8001063C

dlabel D_8001063C
    /* E3C 8001063C */ .asciz "tw   (%d,%d)-(%d,%d)\n"
    /* 74772020202825642C2564292D2825642C2564290A000000 */
.align 2
enddlabel D_8001063C

.align 2
nonmatching D_80010654

dlabel D_80010654
    /* E54 80010654 */ .asciz "dtd   %d\n"
    /* 64746420202025640A000000 */
.align 2
enddlabel D_80010654

.align 2
nonmatching D_80010660

dlabel D_80010660
    /* E60 80010660 */ .asciz "dfe   %d\n"
    /* 64666520202025640A000000 */
.align 2
enddlabel D_80010660

.align 2
nonmatching D_8001066C

dlabel D_8001066C
    /* E6C 8001066C */ .asciz "disp   (%3d,%3d)-(%d,%d)\n"
    /* 64697370202020282533642C253364292D2825642C2564290A000000 */
.align 2
enddlabel D_8001066C

.align 2
nonmatching D_80010688

dlabel D_80010688
    /* E88 80010688 */ .asciz "screen (%3d,%3d)-(%d,%d)\n"
    /* 73637265656E20282533642C253364292D2825642C2564290A000000 */
.align 2
enddlabel D_80010688

.align 2
nonmatching D_800106A4

dlabel D_800106A4
    /* EA4 800106A4 */ .asciz "isinter %d\n"
    /* 6973696E7465722025640A00 */
.align 2
enddlabel D_800106A4

.align 2
nonmatching D_800106B0

dlabel D_800106B0
    /* EB0 800106B0 */ .asciz "isrgb24 %d\n"
    /* 697372676232342025640A00 */
.align 2
.align 2
    /* EBC 800106BC */ .asciz "$Id: intr.c,v 1.73 1995/11/10 05:29:40 suzu Exp $"
    /* 2449643A20696E74722E632C7620312E373320313939352F31312F31302030353A32393A34302073757A75204578702024000000 */
.align 2
enddlabel D_800106B0

.align 2
nonmatching D_800106F0

dlabel D_800106F0
    /* EF0 800106F0 */ .asciz "unexpected interrupt(%04x)\n"
    /* 756E657870656374656420696E746572727570742825303478290A00 */
.align 2
enddlabel D_800106F0

.align 2
nonmatching D_8001070C

dlabel D_8001070C
    /* F0C 8001070C */ .asciz "intr timeout(%04x:%04x)\n"
    /* 696E74722074696D656F757428253034783A25303478290A00000000 */
.align 2
enddlabel D_8001070C
