.include "macro.inc"

.section .sdata, "wa"

/* Generated by spimdisasm 1.41.0 */

nonmatching gTunnelLinkStartPos1

dlabel gTunnelLinkStartPos1
    /* 7B3C0 8008ABC0 00000000 */ .word 0x00000000
    /* 7B3C4 8008ABC4 00000000 */ .word 0x00000000
enddlabel gTunnelLinkStartPos1

nonmatching gTunnelLinkStartPos2

dlabel gTunnelLinkStartPos2
    /* 7B3C8 8008ABC8 00000000 */ .word 0x00000000
    /* 7B3CC 8008ABCC E8030000 */ .word 0x000003E8
enddlabel gTunnelLinkStartPos2

nonmatching gTunnelLinkStartPos3

dlabel gTunnelLinkStartPos3
    /* 7B3D0 8008ABD0 00000000 */ .word 0x00000000
    /* 7B3D4 8008ABD4 00000000 */ .word 0x00000000
enddlabel gTunnelLinkStartPos3

nonmatching gTunnelLinkStartPos4

dlabel gTunnelLinkStartPos4
    /* 7B3D8 8008ABD8 18FC0000 */ .word 0x0000FC18
    /* 7B3DC 8008ABDC 20030000 */ .word 0x00000320
enddlabel gTunnelLinkStartPos4

nonmatching gInitialField178

dlabel gInitialField178
    /* 7B3E0 8008ABE0 4A303100 */ .word 0x0031304A
enddlabel gInitialField178

nonmatching gInstantTeleportersEnabled

dlabel gInstantTeleportersEnabled
    /* 7B3E4 8008ABE4 01000000 */ .word 0x00000001
enddlabel gInstantTeleportersEnabled

nonmatching gFallingLinkChunkId

dlabel gFallingLinkChunkId
    /* 7B3E8 8008ABE8 01030C0E */ .word 0x0E0C0301
    /* 7B3EC 8008ABEC 00000000 */ .word 0x00000000
enddlabel gFallingLinkChunkId

nonmatching gLinkAngleBlockFallback

dlabel gLinkAngleBlockFallback
    /* 7B3F0 8008ABF0 B4000100 */ .word 0x000100B4
enddlabel gLinkAngleBlockFallback

nonmatching gSpecialDayMood

dlabel gSpecialDayMood
    /* 7B3F4 8008ABF4 00000000 */ .word 0x00000000
enddlabel gSpecialDayMood
