.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 2
nonmatching D_80010728

dlabel D_80010728
    /* F28 80010728 */ .asciz "DMA bus error: code=%08x\n"
    /* 444D4120627573206572726F723A20636F64653D253038780A000000 */
.align 2
enddlabel D_80010728

.align 2
nonmatching D_80010744

dlabel D_80010744
    /* F44 80010744 */ .asciz "MADR[%d]=%08x\n"
    /* 4D4144525B25645D3D253038780A0000 */
.align 2
enddlabel D_80010744

.align 2
nonmatching D_80010754

dlabel D_80010754
    /* F54 80010754 */ .asciz "VSync: timeout\n"
    /* 5653796E633A2074696D656F75740A00 */
.align 2
enddlabel D_80010754

nonmatching D_80010764

dlabel D_80010764
    /* F64 80010764 00100000 */ .word 0x00001000
    /* F68 80010768 00400000 */ .word 0x00004000
    /* F6C 8001076C 00800000 */ .word 0x00008000
    /* F70 80010770 00200000 */ .word 0x00002000
    /* F74 80010774 10000000 */ .word 0x00000010
    /* F78 80010778 40000000 */ .word 0x00000040
    /* F7C 8001077C 80000000 */ .word 0x00000080
    /* F80 80010780 20000000 */ .word 0x00000020
    /* F84 80010784 00020000 */ .word 0x00000200
    /* F88 80010788 00040000 */ .word 0x00000400
    /* F8C 8001078C 00010000 */ .word 0x00000100
    /* F90 80010790 08000000 */ .word 0x00000008
    /* F94 80010794 02000000 */ .word 0x00000002
    /* F98 80010798 04000000 */ .word 0x00000004
    /* F9C 8001079C 01000000 */ .word 0x00000001
    /* FA0 800107A0 00080000 */ .word 0x00000800
enddlabel D_80010764
