.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.41.0 */

.align 2
nonmatching D_800107A4

dlabel D_800107A4
    /* FA4 800107A4 */ .asciz "ETC\\DREAME5.TMD"
    /* 4554435C445245414D45352E544D4400 */
.align 2
enddlabel D_800107A4

.align 2
nonmatching gDayIntroEffectCfgA

dlabel gDayIntroEffectCfgA
    /* FB4 800107B4 */ .asciz "ETC\\ASMKLOGO.TIM"
    /* 4554435C41534D4B4C4F474F2E54494D00000000 */
.align 2
enddlabel gDayIntroEffectCfgA

.align 2
nonmatching gDayIntroEffectCfgB

dlabel gDayIntroEffectCfgB
    /* FC8 800107C8 */ .asciz "ETC\\OSDLOGO.TIM"
    /* 4554435C4F53444C4F474F2E54494D00 */
.align 2
enddlabel gDayIntroEffectCfgB
