.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching func_8001BFD4, 0x8

glabel func_8001BFD4
    /* C7D4 8001BFD4 6000A720 */  addi       $a3, $a1, 0x60 /* handwritten instruction */
    /* C7D8 8001BFD8 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001BFD4

/* Handwritten function */
nonmatching func_8001BFDC, 0x404

glabel func_8001BFDC
    /* C7DC 8001BFDC 4800E88C */  lw         $t0, 0x48($a3)
    /* C7E0 8001BFE0 4C00E98C */  lw         $t1, 0x4C($a3)
    /* C7E4 8001BFE4 5000EA8C */  lw         $t2, 0x50($a3)
    /* C7E8 8001BFE8 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* C7EC 8001BFEC 14000C8D */  lw         $t4, 0x14($t0)
    /* C7F0 8001BFF0 14002D8D */  lw         $t5, 0x14($t1)
    /* C7F4 8001BFF4 14004E8D */  lw         $t6, 0x14($t2)
    /* C7F8 8001BFF8 43C01900 */  sra        $t8, $t9, 1
    /* C7FC 8001BFFC 2B089801 */  sltu       $at, $t4, $t8
    /* C800 8001C000 08002010 */  beqz       $at, .L8001C024
    /* C804 8001C004 2B08B801 */   sltu      $at, $t5, $t8
    /* C808 8001C008 06002010 */  beqz       $at, .L8001C024
    /* C80C 8001C00C 2B08D801 */   sltu      $at, $t6, $t8
    /* C810 8001C010 04002010 */  beqz       $at, .L8001C024
    /* C814 8001C014 00000000 */   nop
    /* C818 8001C018 21108000 */  addu       $v0, $a0, $zero
    /* C81C 8001C01C 0800E003 */  jr         $ra
    /* C820 8001C020 00000000 */   nop
  .L8001C024:
    /* C824 8001C024 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* C828 8001C028 0400A28C */  lw         $v0, 0x4($a1)
    /* C82C 8001C02C 0800A38C */  lw         $v1, 0x8($a1)
    /* C830 8001C030 03CC1900 */  sra        $t9, $t9, 16
    /* C834 8001C034 42100200 */  srl        $v0, $v0, 1
    /* C838 8001C038 42180300 */  srl        $v1, $v1, 1
    /* C83C 8001C03C 21C02203 */  addu       $t8, $t9, $v0
    /* C840 8001C040 10000C85 */  lh         $t4, 0x10($t0)
    /* C844 8001C044 10002D85 */  lh         $t5, 0x10($t1)
    /* C848 8001C048 10004E85 */  lh         $t6, 0x10($t2)
    /* C84C 8001C04C 2A080C03 */  slt        $at, $t8, $t4
    /* C850 8001C050 08002010 */  beqz       $at, .L8001C074
    /* C854 8001C054 2A080D03 */   slt       $at, $t8, $t5
    /* C858 8001C058 06002010 */  beqz       $at, .L8001C074
    /* C85C 8001C05C 2A080E03 */   slt       $at, $t8, $t6
    /* C860 8001C060 04002010 */  beqz       $at, .L8001C074
    /* C864 8001C064 00000000 */   nop
    /* C868 8001C068 21108000 */  addu       $v0, $a0, $zero
    /* C86C 8001C06C 0800E003 */  jr         $ra
    /* C870 8001C070 00000000 */   nop
  .L8001C074:
    /* C874 8001C074 23C02203 */  subu       $t8, $t9, $v0
    /* C878 8001C078 2A089801 */  slt        $at, $t4, $t8
    /* C87C 8001C07C 08002010 */  beqz       $at, .L8001C0A0
    /* C880 8001C080 2A08B801 */   slt       $at, $t5, $t8
    /* C884 8001C084 06002010 */  beqz       $at, .L8001C0A0
    /* C888 8001C088 2A08D801 */   slt       $at, $t6, $t8
    /* C88C 8001C08C 04002010 */  beqz       $at, .L8001C0A0
    /* C890 8001C090 00000000 */   nop
    /* C894 8001C094 21108000 */  addu       $v0, $a0, $zero
    /* C898 8001C098 0800E003 */  jr         $ra
    /* C89C 8001C09C 00000000 */   nop
  .L8001C0A0:
    /* C8A0 8001C0A0 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* C8A4 8001C0A4 12000C85 */  lh         $t4, 0x12($t0)
    /* C8A8 8001C0A8 12002D85 */  lh         $t5, 0x12($t1)
    /* C8AC 8001C0AC 12004E85 */  lh         $t6, 0x12($t2)
    /* C8B0 8001C0B0 03CC1900 */  sra        $t9, $t9, 16
    /* C8B4 8001C0B4 21C02303 */  addu       $t8, $t9, $v1
    /* C8B8 8001C0B8 2A080C03 */  slt        $at, $t8, $t4
    /* C8BC 8001C0BC 08002010 */  beqz       $at, .L8001C0E0
    /* C8C0 8001C0C0 2A080D03 */   slt       $at, $t8, $t5
    /* C8C4 8001C0C4 06002010 */  beqz       $at, .L8001C0E0
    /* C8C8 8001C0C8 2A080E03 */   slt       $at, $t8, $t6
    /* C8CC 8001C0CC 04002010 */  beqz       $at, .L8001C0E0
    /* C8D0 8001C0D0 00000000 */   nop
    /* C8D4 8001C0D4 21108000 */  addu       $v0, $a0, $zero
    /* C8D8 8001C0D8 0800E003 */  jr         $ra
    /* C8DC 8001C0DC 00000000 */   nop
  .L8001C0E0:
    /* C8E0 8001C0E0 23C02303 */  subu       $t8, $t9, $v1
    /* C8E4 8001C0E4 2A089801 */  slt        $at, $t4, $t8
    /* C8E8 8001C0E8 08002010 */  beqz       $at, .L8001C10C
    /* C8EC 8001C0EC 2A08B801 */   slt       $at, $t5, $t8
    /* C8F0 8001C0F0 06002010 */  beqz       $at, .L8001C10C
    /* C8F4 8001C0F4 2A08D801 */   slt       $at, $t6, $t8
    /* C8F8 8001C0F8 04002010 */  beqz       $at, .L8001C10C
    /* C8FC 8001C0FC 00000000 */   nop
    /* C900 8001C100 21108000 */  addu       $v0, $a0, $zero
    /* C904 8001C104 0800E003 */  jr         $ra
    /* C908 8001C108 00000000 */   nop
  .L8001C10C:
    /* C90C 8001C10C 00000C85 */  lh         $t4, 0x0($t0)
    /* C910 8001C110 00002D85 */  lh         $t5, 0x0($t1)
    /* C914 8001C114 00004E85 */  lh         $t6, 0x0($t2)
    /* C918 8001C118 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* C91C 8001C11C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* C920 8001C120 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* C924 8001C124 43780F00 */  sra        $t7, $t7, 1
    /* C928 8001C128 43C01800 */  sra        $t8, $t8, 1
    /* C92C 8001C12C 43C81900 */  sra        $t9, $t9, 1
    /* C930 8001C130 0000EFA4 */  sh         $t7, 0x0($a3)
    /* C934 8001C134 1800F8A4 */  sh         $t8, 0x18($a3)
    /* C938 8001C138 3000F9A4 */  sh         $t9, 0x30($a3)
    /* C93C 8001C13C 02000C85 */  lh         $t4, 0x2($t0)
    /* C940 8001C140 02002D85 */  lh         $t5, 0x2($t1)
    /* C944 8001C144 02004E85 */  lh         $t6, 0x2($t2)
    /* C948 8001C148 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* C94C 8001C14C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* C950 8001C150 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* C954 8001C154 43780F00 */  sra        $t7, $t7, 1
    /* C958 8001C158 43C01800 */  sra        $t8, $t8, 1
    /* C95C 8001C15C 43C81900 */  sra        $t9, $t9, 1
    /* C960 8001C160 0200EFA4 */  sh         $t7, 0x2($a3)
    /* C964 8001C164 1A00F8A4 */  sh         $t8, 0x1A($a3)
    /* C968 8001C168 3200F9A4 */  sh         $t9, 0x32($a3)
    /* C96C 8001C16C 04000C85 */  lh         $t4, 0x4($t0)
    /* C970 8001C170 04002D85 */  lh         $t5, 0x4($t1)
    /* C974 8001C174 04004E85 */  lh         $t6, 0x4($t2)
    /* C978 8001C178 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* C97C 8001C17C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* C980 8001C180 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* C984 8001C184 43780F00 */  sra        $t7, $t7, 1
    /* C988 8001C188 43C01800 */  sra        $t8, $t8, 1
    /* C98C 8001C18C 43C81900 */  sra        $t9, $t9, 1
    /* C990 8001C190 0400EFA4 */  sh         $t7, 0x4($a3)
    /* C994 8001C194 1C00F8A4 */  sh         $t8, 0x1C($a3)
    /* C998 8001C198 3400F9A4 */  sh         $t9, 0x34($a3)
    /* C99C 8001C19C 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* C9A0 8001C1A0 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* C9A4 8001C1A4 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* C9A8 8001C1A8 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* C9AC 8001C1AC 3000E4C8 */  lwc2       $4, 0x30($a3)
    /* C9B0 8001C1B0 3400E5C8 */  lwc2       $5, 0x34($a3)
    /* C9B4 8001C1B4 08000C91 */  lbu        $t4, 0x8($t0)
    /* C9B8 8001C1B8 08002D91 */  lbu        $t5, 0x8($t1)
    /* C9BC 8001C1BC 08004E91 */  lbu        $t6, 0x8($t2)
    /* C9C0 8001C1C0 21788D01 */  addu       $t7, $t4, $t5
    /* C9C4 8001C1C4 21C0AE01 */  addu       $t8, $t5, $t6
    /* C9C8 8001C1C8 21C8CC01 */  addu       $t9, $t6, $t4
    /* C9CC 8001C1CC 42780F00 */  srl        $t7, $t7, 1
    /* C9D0 8001C1D0 42C01800 */  srl        $t8, $t8, 1
    /* C9D4 8001C1D4 42C81900 */  srl        $t9, $t9, 1
    /* C9D8 8001C1D8 0800EFA0 */  sb         $t7, 0x8($a3)
    /* C9DC 8001C1DC 2000F8A0 */  sb         $t8, 0x20($a3)
    /* C9E0 8001C1E0 3800F9A0 */  sb         $t9, 0x38($a3)
    /* C9E4 8001C1E4 3000284A */  rtpt
    /* C9E8 8001C1E8 09000C91 */  lbu        $t4, 0x9($t0)
    /* C9EC 8001C1EC 09002D91 */  lbu        $t5, 0x9($t1)
    /* C9F0 8001C1F0 09004E91 */  lbu        $t6, 0x9($t2)
    /* C9F4 8001C1F4 21788D01 */  addu       $t7, $t4, $t5
    /* C9F8 8001C1F8 21C0AE01 */  addu       $t8, $t5, $t6
    /* C9FC 8001C1FC 21C8CC01 */  addu       $t9, $t6, $t4
    /* CA00 8001C200 42780F00 */  srl        $t7, $t7, 1
    /* CA04 8001C204 42C01800 */  srl        $t8, $t8, 1
    /* CA08 8001C208 42C81900 */  srl        $t9, $t9, 1
    /* CA0C 8001C20C 0900EFA0 */  sb         $t7, 0x9($a3)
    /* CA10 8001C210 2100F8A0 */  sb         $t8, 0x21($a3)
    /* CA14 8001C214 3900F9A0 */  sb         $t9, 0x39($a3)
    /* CA18 8001C218 0C000C91 */  lbu        $t4, 0xC($t0)
    /* CA1C 8001C21C 0C002D91 */  lbu        $t5, 0xC($t1)
    /* CA20 8001C220 0C004E91 */  lbu        $t6, 0xC($t2)
    /* CA24 8001C224 21788D01 */  addu       $t7, $t4, $t5
    /* CA28 8001C228 21C0AE01 */  addu       $t8, $t5, $t6
    /* CA2C 8001C22C 21C8CC01 */  addu       $t9, $t6, $t4
    /* CA30 8001C230 42780F00 */  srl        $t7, $t7, 1
    /* CA34 8001C234 42C01800 */  srl        $t8, $t8, 1
    /* CA38 8001C238 42C81900 */  srl        $t9, $t9, 1
    /* CA3C 8001C23C 0C00EFA0 */  sb         $t7, 0xC($a3)
    /* CA40 8001C240 2400F8A0 */  sb         $t8, 0x24($a3)
    /* CA44 8001C244 3C00F9A0 */  sb         $t9, 0x3C($a3)
    /* CA48 8001C248 0D000C91 */  lbu        $t4, 0xD($t0)
    /* CA4C 8001C24C 0D002D91 */  lbu        $t5, 0xD($t1)
    /* CA50 8001C250 0D004E91 */  lbu        $t6, 0xD($t2)
    /* CA54 8001C254 21788D01 */  addu       $t7, $t4, $t5
    /* CA58 8001C258 21C0AE01 */  addu       $t8, $t5, $t6
    /* CA5C 8001C25C 21C8CC01 */  addu       $t9, $t6, $t4
    /* CA60 8001C260 42780F00 */  srl        $t7, $t7, 1
    /* CA64 8001C264 42C01800 */  srl        $t8, $t8, 1
    /* CA68 8001C268 42C81900 */  srl        $t9, $t9, 1
    /* CA6C 8001C26C 0D00EFA0 */  sb         $t7, 0xD($a3)
    /* CA70 8001C270 2500F8A0 */  sb         $t8, 0x25($a3)
    /* CA74 8001C274 3D00F9A0 */  sb         $t9, 0x3D($a3)
    /* CA78 8001C278 0E000C91 */  lbu        $t4, 0xE($t0)
    /* CA7C 8001C27C 0E002D91 */  lbu        $t5, 0xE($t1)
    /* CA80 8001C280 0E004E91 */  lbu        $t6, 0xE($t2)
    /* CA84 8001C284 21788D01 */  addu       $t7, $t4, $t5
    /* CA88 8001C288 21C0AE01 */  addu       $t8, $t5, $t6
    /* CA8C 8001C28C 21C8CC01 */  addu       $t9, $t6, $t4
    /* CA90 8001C290 42780F00 */  srl        $t7, $t7, 1
    /* CA94 8001C294 42C01800 */  srl        $t8, $t8, 1
    /* CA98 8001C298 42C81900 */  srl        $t9, $t9, 1
    /* CA9C 8001C29C 0E00EFA0 */  sb         $t7, 0xE($a3)
    /* CAA0 8001C2A0 2600F8A0 */  sb         $t8, 0x26($a3)
    /* CAA4 8001C2A4 3E00F9A0 */  sb         $t9, 0x3E($a3)
    /* CAA8 8001C2A8 0000AC8C */  lw         $t4, 0x0($a1)
    /* CAAC 8001C2AC 0100C624 */  addiu      $a2, $a2, 0x1
    /* CAB0 8001C2B0 1D008615 */  bne        $t4, $a2, .L8001C328
    /* CAB4 8001C2B4 00000000 */   nop
    /* CAB8 8001C2B8 1000ECE8 */  swc2       $12, 0x10($a3)
    /* CABC 8001C2BC 2800EDE8 */  swc2       $13, 0x28($a3)
    /* CAC0 8001C2C0 4000EEE8 */  swc2       $14, 0x40($a3)
    /* CAC4 8001C2C4 2118E003 */  addu       $v1, $ra, $zero
    /* CAC8 8001C2C8 4C00E88C */  lw         $t0, 0x4C($a3)
    /* CACC 8001C2CC 1800E924 */  addiu      $t1, $a3, 0x18
    /* CAD0 8001C2D0 0000EA24 */  addiu      $t2, $a3, 0x0
    /* CAD4 8001C2D4 F870000C */  jal        func_8001C3E0
    /* CAD8 8001C2D8 00000000 */   nop
    /* CADC 8001C2DC 0000E824 */  addiu      $t0, $a3, 0x0
    /* CAE0 8001C2E0 1800E924 */  addiu      $t1, $a3, 0x18
    /* CAE4 8001C2E4 3000EA24 */  addiu      $t2, $a3, 0x30
    /* CAE8 8001C2E8 F870000C */  jal        func_8001C3E0
    /* CAEC 8001C2EC 00000000 */   nop
    /* CAF0 8001C2F0 4800E88C */  lw         $t0, 0x48($a3)
    /* CAF4 8001C2F4 0000E924 */  addiu      $t1, $a3, 0x0
    /* CAF8 8001C2F8 3000EA24 */  addiu      $t2, $a3, 0x30
    /* CAFC 8001C2FC F870000C */  jal        func_8001C3E0
    /* CB00 8001C300 00000000 */   nop
    /* CB04 8001C304 5000E88C */  lw         $t0, 0x50($a3)
    /* CB08 8001C308 3000E924 */  addiu      $t1, $a3, 0x30
    /* CB0C 8001C30C 1800EA24 */  addiu      $t2, $a3, 0x18
    /* CB10 8001C310 F870000C */  jal        func_8001C3E0
    /* CB14 8001C314 00000000 */   nop
    /* CB18 8001C318 21F86000 */  addu       $ra, $v1, $zero
    /* CB1C 8001C31C FFFFC624 */  addiu      $a2, $a2, -0x1
    /* CB20 8001C320 2C000010 */  b          .L8001C3D4
    /* CB24 8001C324 00000000 */   nop
  .L8001C328:
    /* CB28 8001C328 1400F1E8 */  swc2       $17, 0x14($a3)
    /* CB2C 8001C32C 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* CB30 8001C330 4400F3E8 */  swc2       $19, 0x44($a3)
    /* CB34 8001C334 1000ECE8 */  swc2       $12, 0x10($a3)
    /* CB38 8001C338 2800EDE8 */  swc2       $13, 0x28($a3)
    /* CB3C 8001C33C 4000EEE8 */  swc2       $14, 0x40($a3)
    /* CB40 8001C340 5800E724 */  addiu      $a3, $a3, 0x58
    /* CB44 8001C344 5400FFAC */  sw         $ra, 0x54($a3)
    /* CB48 8001C348 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* CB4C 8001C34C A8FFED24 */  addiu      $t5, $a3, -0x58
    /* CB50 8001C350 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* CB54 8001C354 4800ECAC */  sw         $t4, 0x48($a3)
    /* CB58 8001C358 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* CB5C 8001C35C 5000EEAC */  sw         $t6, 0x50($a3)
    /* CB60 8001C360 F76F000C */  jal        func_8001BFDC
    /* CB64 8001C364 00000000 */   nop
    /* CB68 8001C368 F4FFEC8C */  lw         $t4, -0xC($a3)
    /* CB6C 8001C36C C0FFED24 */  addiu      $t5, $a3, -0x40
    /* CB70 8001C370 A8FFEE24 */  addiu      $t6, $a3, -0x58
    /* CB74 8001C374 4800ECAC */  sw         $t4, 0x48($a3)
    /* CB78 8001C378 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* CB7C 8001C37C 5000EEAC */  sw         $t6, 0x50($a3)
    /* CB80 8001C380 F76F000C */  jal        func_8001BFDC
    /* CB84 8001C384 00000000 */   nop
    /* CB88 8001C388 F8FFEC8C */  lw         $t4, -0x8($a3)
    /* CB8C 8001C38C D8FFED24 */  addiu      $t5, $a3, -0x28
    /* CB90 8001C390 C0FFEE24 */  addiu      $t6, $a3, -0x40
    /* CB94 8001C394 4800ECAC */  sw         $t4, 0x48($a3)
    /* CB98 8001C398 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* CB9C 8001C39C 5000EEAC */  sw         $t6, 0x50($a3)
    /* CBA0 8001C3A0 F76F000C */  jal        func_8001BFDC
    /* CBA4 8001C3A4 00000000 */   nop
    /* CBA8 8001C3A8 A8FFEC24 */  addiu      $t4, $a3, -0x58
    /* CBAC 8001C3AC C0FFED24 */  addiu      $t5, $a3, -0x40
    /* CBB0 8001C3B0 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* CBB4 8001C3B4 4800ECAC */  sw         $t4, 0x48($a3)
    /* CBB8 8001C3B8 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* CBBC 8001C3BC 5000EEAC */  sw         $t6, 0x50($a3)
    /* CBC0 8001C3C0 F76F000C */  jal        func_8001BFDC
    /* CBC4 8001C3C4 00000000 */   nop
    /* CBC8 8001C3C8 5400FF8C */  lw         $ra, 0x54($a3)
    /* CBCC 8001C3CC A8FFE724 */  addiu      $a3, $a3, -0x58
    /* CBD0 8001C3D0 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001C3D4:
    /* CBD4 8001C3D4 21108000 */  addu       $v0, $a0, $zero
    /* CBD8 8001C3D8 0800E003 */  jr         $ra
    /* CBDC 8001C3DC 00000000 */   nop
endlabel func_8001BFDC

nonmatching func_8001C3E0, 0x94

glabel func_8001C3E0
    /* CBE0 8001C3E0 0C00AC94 */  lhu        $t4, 0xC($a1)
    /* CBE4 8001C3E4 08000D95 */  lhu        $t5, 0x8($t0)
    /* CBE8 8001C3E8 00640C00 */  sll        $t4, $t4, 16
    /* CBEC 8001C3EC 2168AC01 */  addu       $t5, $t5, $t4
    /* CBF0 8001C3F0 0E00AC94 */  lhu        $t4, 0xE($a1)
    /* CBF4 8001C3F4 08002E95 */  lhu        $t6, 0x8($t1)
    /* CBF8 8001C3F8 00640C00 */  sll        $t4, $t4, 16
    /* CBFC 8001C3FC 2170CC01 */  addu       $t6, $t6, $t4
    /* CC00 8001C400 08004F95 */  lhu        $t7, 0x8($t2)
    /* CC04 8001C404 1300AC80 */  lb         $t4, 0x13($a1)
    /* CC08 8001C408 0C008DAC */  sw         $t5, 0xC($a0)
    /* CC0C 8001C40C 18008EAC */  sw         $t6, 0x18($a0)
    /* CC10 8001C410 24008FAC */  sw         $t7, 0x24($a0)
    /* CC14 8001C414 0F000CA1 */  sb         $t4, 0xF($t0)
    /* CC18 8001C418 10000C8D */  lw         $t4, 0x10($t0)
    /* CC1C 8001C41C 10002D8D */  lw         $t5, 0x10($t1)
    /* CC20 8001C420 10004E8D */  lw         $t6, 0x10($t2)
    /* CC24 8001C424 08008CAC */  sw         $t4, 0x8($a0)
    /* CC28 8001C428 14008DAC */  sw         $t5, 0x14($a0)
    /* CC2C 8001C42C 20008EAC */  sw         $t6, 0x20($a0)
    /* CC30 8001C430 1400AC8C */  lw         $t4, 0x14($a1)
    /* CC34 8001C434 00CA0400 */  sll        $t9, $a0, 8
    /* CC38 8001C438 02CA1900 */  srl        $t9, $t9, 8
    /* CC3C 8001C43C 0000988D */  lw         $t8, 0x0($t4)
    /* CC40 8001C440 000099AD */  sw         $t9, 0x0($t4)
    /* CC44 8001C444 00090E3C */  lui        $t6, (0x9000000 >> 16)
    /* CC48 8001C448 25C00E03 */  or         $t8, $t8, $t6
    /* CC4C 8001C44C 0C000C8D */  lw         $t4, 0xC($t0)
    /* CC50 8001C450 0C002D8D */  lw         $t5, 0xC($t1)
    /* CC54 8001C454 0C004E8D */  lw         $t6, 0xC($t2)
    /* CC58 8001C458 04008CAC */  sw         $t4, 0x4($a0)
    /* CC5C 8001C45C 10008DAC */  sw         $t5, 0x10($a0)
    /* CC60 8001C460 1C008EAC */  sw         $t6, 0x1C($a0)
    /* CC64 8001C464 000098AC */  sw         $t8, 0x0($a0)
    /* CC68 8001C468 28008424 */  addiu      $a0, $a0, 0x28
    /* CC6C 8001C46C 0800E003 */  jr         $ra
    /* CC70 8001C470 00000000 */   nop
endlabel func_8001C3E0

/* Handwritten function */
nonmatching func_8001C474, 0x8

glabel func_8001C474
    /* CC74 8001C474 7800A720 */  addi       $a3, $a1, 0x78 /* handwritten instruction */
    /* CC78 8001C478 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001C474

/* Handwritten function */
nonmatching func_8001C47C, 0x564

glabel func_8001C47C
    /* CC7C 8001C47C 7800E88C */  lw         $t0, 0x78($a3)
    /* CC80 8001C480 7C00E98C */  lw         $t1, 0x7C($a3)
    /* CC84 8001C484 8000EA8C */  lw         $t2, 0x80($a3)
    /* CC88 8001C488 8400EB8C */  lw         $t3, 0x84($a3)
    /* CC8C 8001C48C 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* CC90 8001C490 14000C8D */  lw         $t4, 0x14($t0)
    /* CC94 8001C494 14002D8D */  lw         $t5, 0x14($t1)
    /* CC98 8001C498 14004E8D */  lw         $t6, 0x14($t2)
    /* CC9C 8001C49C 14006F8D */  lw         $t7, 0x14($t3)
    /* CCA0 8001C4A0 43C01900 */  sra        $t8, $t9, 1
    /* CCA4 8001C4A4 2B089801 */  sltu       $at, $t4, $t8
    /* CCA8 8001C4A8 0A002010 */  beqz       $at, .L8001C4D4
    /* CCAC 8001C4AC 2B08B801 */   sltu      $at, $t5, $t8
    /* CCB0 8001C4B0 08002010 */  beqz       $at, .L8001C4D4
    /* CCB4 8001C4B4 2B08D801 */   sltu      $at, $t6, $t8
    /* CCB8 8001C4B8 06002010 */  beqz       $at, .L8001C4D4
    /* CCBC 8001C4BC 2B08F801 */   sltu      $at, $t7, $t8
    /* CCC0 8001C4C0 04002010 */  beqz       $at, .L8001C4D4
    /* CCC4 8001C4C4 00000000 */   nop
    /* CCC8 8001C4C8 21108000 */  addu       $v0, $a0, $zero
    /* CCCC 8001C4CC 0800E003 */  jr         $ra
    /* CCD0 8001C4D0 00000000 */   nop
  .L8001C4D4:
    /* CCD4 8001C4D4 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* CCD8 8001C4D8 0400A28C */  lw         $v0, 0x4($a1)
    /* CCDC 8001C4DC 0800A38C */  lw         $v1, 0x8($a1)
    /* CCE0 8001C4E0 03CC1900 */  sra        $t9, $t9, 16
    /* CCE4 8001C4E4 42100200 */  srl        $v0, $v0, 1
    /* CCE8 8001C4E8 42180300 */  srl        $v1, $v1, 1
    /* CCEC 8001C4EC 21C02203 */  addu       $t8, $t9, $v0
    /* CCF0 8001C4F0 10000C85 */  lh         $t4, 0x10($t0)
    /* CCF4 8001C4F4 10002D85 */  lh         $t5, 0x10($t1)
    /* CCF8 8001C4F8 10004E85 */  lh         $t6, 0x10($t2)
    /* CCFC 8001C4FC 10006F85 */  lh         $t7, 0x10($t3)
    /* CD00 8001C500 2A080C03 */  slt        $at, $t8, $t4
    /* CD04 8001C504 0A002010 */  beqz       $at, .L8001C530
    /* CD08 8001C508 2A080D03 */   slt       $at, $t8, $t5
    /* CD0C 8001C50C 08002010 */  beqz       $at, .L8001C530
    /* CD10 8001C510 2A080E03 */   slt       $at, $t8, $t6
    /* CD14 8001C514 06002010 */  beqz       $at, .L8001C530
    /* CD18 8001C518 2A080F03 */   slt       $at, $t8, $t7
    /* CD1C 8001C51C 04002010 */  beqz       $at, .L8001C530
    /* CD20 8001C520 00000000 */   nop
    /* CD24 8001C524 21108000 */  addu       $v0, $a0, $zero
    /* CD28 8001C528 0800E003 */  jr         $ra
    /* CD2C 8001C52C 00000000 */   nop
  .L8001C530:
    /* CD30 8001C530 23C02203 */  subu       $t8, $t9, $v0
    /* CD34 8001C534 2A089801 */  slt        $at, $t4, $t8
    /* CD38 8001C538 0A002010 */  beqz       $at, .L8001C564
    /* CD3C 8001C53C 2A08B801 */   slt       $at, $t5, $t8
    /* CD40 8001C540 08002010 */  beqz       $at, .L8001C564
    /* CD44 8001C544 2A08D801 */   slt       $at, $t6, $t8
    /* CD48 8001C548 06002010 */  beqz       $at, .L8001C564
    /* CD4C 8001C54C 2A08F801 */   slt       $at, $t7, $t8
    /* CD50 8001C550 04002010 */  beqz       $at, .L8001C564
    /* CD54 8001C554 00000000 */   nop
    /* CD58 8001C558 21108000 */  addu       $v0, $a0, $zero
    /* CD5C 8001C55C 0800E003 */  jr         $ra
    /* CD60 8001C560 00000000 */   nop
  .L8001C564:
    /* CD64 8001C564 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* CD68 8001C568 12000C85 */  lh         $t4, 0x12($t0)
    /* CD6C 8001C56C 12002D85 */  lh         $t5, 0x12($t1)
    /* CD70 8001C570 12004E85 */  lh         $t6, 0x12($t2)
    /* CD74 8001C574 12006F85 */  lh         $t7, 0x12($t3)
    /* CD78 8001C578 03CC1900 */  sra        $t9, $t9, 16
    /* CD7C 8001C57C 21C02303 */  addu       $t8, $t9, $v1
    /* CD80 8001C580 2A080C03 */  slt        $at, $t8, $t4
    /* CD84 8001C584 0A002010 */  beqz       $at, .L8001C5B0
    /* CD88 8001C588 2A080D03 */   slt       $at, $t8, $t5
    /* CD8C 8001C58C 08002010 */  beqz       $at, .L8001C5B0
    /* CD90 8001C590 2A080E03 */   slt       $at, $t8, $t6
    /* CD94 8001C594 06002010 */  beqz       $at, .L8001C5B0
    /* CD98 8001C598 2A080F03 */   slt       $at, $t8, $t7
    /* CD9C 8001C59C 04002010 */  beqz       $at, .L8001C5B0
    /* CDA0 8001C5A0 00000000 */   nop
    /* CDA4 8001C5A4 21108000 */  addu       $v0, $a0, $zero
    /* CDA8 8001C5A8 0800E003 */  jr         $ra
    /* CDAC 8001C5AC 00000000 */   nop
  .L8001C5B0:
    /* CDB0 8001C5B0 23C02303 */  subu       $t8, $t9, $v1
    /* CDB4 8001C5B4 2A089801 */  slt        $at, $t4, $t8
    /* CDB8 8001C5B8 0A002010 */  beqz       $at, .L8001C5E4
    /* CDBC 8001C5BC 2A08B801 */   slt       $at, $t5, $t8
    /* CDC0 8001C5C0 08002010 */  beqz       $at, .L8001C5E4
    /* CDC4 8001C5C4 2A08D801 */   slt       $at, $t6, $t8
    /* CDC8 8001C5C8 06002010 */  beqz       $at, .L8001C5E4
    /* CDCC 8001C5CC 2A08F801 */   slt       $at, $t7, $t8
    /* CDD0 8001C5D0 04002010 */  beqz       $at, .L8001C5E4
    /* CDD4 8001C5D4 00000000 */   nop
    /* CDD8 8001C5D8 21108000 */  addu       $v0, $a0, $zero
    /* CDDC 8001C5DC 0800E003 */  jr         $ra
    /* CDE0 8001C5E0 00000000 */   nop
  .L8001C5E4:
    /* CDE4 8001C5E4 00000C85 */  lh         $t4, 0x0($t0)
    /* CDE8 8001C5E8 00002D85 */  lh         $t5, 0x0($t1)
    /* CDEC 8001C5EC 00004E85 */  lh         $t6, 0x0($t2)
    /* CDF0 8001C5F0 00006F85 */  lh         $t7, 0x0($t3)
    /* CDF4 8001C5F4 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* CDF8 8001C5F8 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* CDFC 8001C5FC 43C01800 */  sra        $t8, $t8, 1
    /* CE00 8001C600 43C81900 */  sra        $t9, $t9, 1
    /* CE04 8001C604 3000F8A4 */  sh         $t8, 0x30($a3)
    /* CE08 8001C608 1800F9A4 */  sh         $t9, 0x18($a3)
    /* CE0C 8001C60C 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* CE10 8001C610 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* CE14 8001C614 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* CE18 8001C618 43C01800 */  sra        $t8, $t8, 1
    /* CE1C 8001C61C 43C81900 */  sra        $t9, $t9, 1
    /* CE20 8001C620 83180300 */  sra        $v1, $v1, 2
    /* CE24 8001C624 0000F8A4 */  sh         $t8, 0x0($a3)
    /* CE28 8001C628 4800F9A4 */  sh         $t9, 0x48($a3)
    /* CE2C 8001C62C 6000E3A4 */  sh         $v1, 0x60($a3)
    /* CE30 8001C630 02000C85 */  lh         $t4, 0x2($t0)
    /* CE34 8001C634 02002D85 */  lh         $t5, 0x2($t1)
    /* CE38 8001C638 02004E85 */  lh         $t6, 0x2($t2)
    /* CE3C 8001C63C 02006F85 */  lh         $t7, 0x2($t3)
    /* CE40 8001C640 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* CE44 8001C644 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* CE48 8001C648 43C01800 */  sra        $t8, $t8, 1
    /* CE4C 8001C64C 43C81900 */  sra        $t9, $t9, 1
    /* CE50 8001C650 3200F8A4 */  sh         $t8, 0x32($a3)
    /* CE54 8001C654 1A00F9A4 */  sh         $t9, 0x1A($a3)
    /* CE58 8001C658 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* CE5C 8001C65C 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* CE60 8001C660 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* CE64 8001C664 43C01800 */  sra        $t8, $t8, 1
    /* CE68 8001C668 43C81900 */  sra        $t9, $t9, 1
    /* CE6C 8001C66C 83180300 */  sra        $v1, $v1, 2
    /* CE70 8001C670 0200F8A4 */  sh         $t8, 0x2($a3)
    /* CE74 8001C674 4A00F9A4 */  sh         $t9, 0x4A($a3)
    /* CE78 8001C678 6200E3A4 */  sh         $v1, 0x62($a3)
    /* CE7C 8001C67C 04000C85 */  lh         $t4, 0x4($t0)
    /* CE80 8001C680 04002D85 */  lh         $t5, 0x4($t1)
    /* CE84 8001C684 04004E85 */  lh         $t6, 0x4($t2)
    /* CE88 8001C688 04006F85 */  lh         $t7, 0x4($t3)
    /* CE8C 8001C68C 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* CE90 8001C690 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* CE94 8001C694 43C01800 */  sra        $t8, $t8, 1
    /* CE98 8001C698 43C81900 */  sra        $t9, $t9, 1
    /* CE9C 8001C69C 3400F8A4 */  sh         $t8, 0x34($a3)
    /* CEA0 8001C6A0 1C00F9A4 */  sh         $t9, 0x1C($a3)
    /* CEA4 8001C6A4 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* CEA8 8001C6A8 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* CEAC 8001C6AC 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* CEB0 8001C6B0 43C01800 */  sra        $t8, $t8, 1
    /* CEB4 8001C6B4 43C81900 */  sra        $t9, $t9, 1
    /* CEB8 8001C6B8 83180300 */  sra        $v1, $v1, 2
    /* CEBC 8001C6BC 0400F8A4 */  sh         $t8, 0x4($a3)
    /* CEC0 8001C6C0 4C00F9A4 */  sh         $t9, 0x4C($a3)
    /* CEC4 8001C6C4 6400E3A4 */  sh         $v1, 0x64($a3)
    /* CEC8 8001C6C8 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* CECC 8001C6CC 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* CED0 8001C6D0 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* CED4 8001C6D4 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* CED8 8001C6D8 6000E4C8 */  lwc2       $4, 0x60($a3)
    /* CEDC 8001C6DC 6400E5C8 */  lwc2       $5, 0x64($a3)
    /* CEE0 8001C6E0 08000C91 */  lbu        $t4, 0x8($t0)
    /* CEE4 8001C6E4 3000284A */  rtpt
    /* CEE8 8001C6E8 08002D91 */  lbu        $t5, 0x8($t1)
    /* CEEC 8001C6EC 08004E91 */  lbu        $t6, 0x8($t2)
    /* CEF0 8001C6F0 08006F91 */  lbu        $t7, 0x8($t3)
    /* CEF4 8001C6F4 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* CEF8 8001C6F8 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* CEFC 8001C6FC 43C01800 */  sra        $t8, $t8, 1
    /* CF00 8001C700 43C81900 */  sra        $t9, $t9, 1
    /* CF04 8001C704 3800F8A0 */  sb         $t8, 0x38($a3)
    /* CF08 8001C708 2000F9A0 */  sb         $t9, 0x20($a3)
    /* CF0C 8001C70C 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* CF10 8001C710 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* CF14 8001C714 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* CF18 8001C718 43C01800 */  sra        $t8, $t8, 1
    /* CF1C 8001C71C 43C81900 */  sra        $t9, $t9, 1
    /* CF20 8001C720 83180300 */  sra        $v1, $v1, 2
    /* CF24 8001C724 0800F8A0 */  sb         $t8, 0x8($a3)
    /* CF28 8001C728 5000F9A0 */  sb         $t9, 0x50($a3)
    /* CF2C 8001C72C 6800E3A0 */  sb         $v1, 0x68($a3)
    /* CF30 8001C730 09000C91 */  lbu        $t4, 0x9($t0)
    /* CF34 8001C734 09002D91 */  lbu        $t5, 0x9($t1)
    /* CF38 8001C738 09004E91 */  lbu        $t6, 0x9($t2)
    /* CF3C 8001C73C 09006F91 */  lbu        $t7, 0x9($t3)
    /* CF40 8001C740 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* CF44 8001C744 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* CF48 8001C748 43C01800 */  sra        $t8, $t8, 1
    /* CF4C 8001C74C 43C81900 */  sra        $t9, $t9, 1
    /* CF50 8001C750 3900F8A0 */  sb         $t8, 0x39($a3)
    /* CF54 8001C754 2100F9A0 */  sb         $t9, 0x21($a3)
    /* CF58 8001C758 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* CF5C 8001C75C 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* CF60 8001C760 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* CF64 8001C764 43C01800 */  sra        $t8, $t8, 1
    /* CF68 8001C768 43C81900 */  sra        $t9, $t9, 1
    /* CF6C 8001C76C 83180300 */  sra        $v1, $v1, 2
    /* CF70 8001C770 0900F8A0 */  sb         $t8, 0x9($a3)
    /* CF74 8001C774 5100F9A0 */  sb         $t9, 0x51($a3)
    /* CF78 8001C778 6900E3A0 */  sb         $v1, 0x69($a3)
    /* CF7C 8001C77C 1000ECE8 */  swc2       $12, 0x10($a3)
    /* CF80 8001C780 2800EDE8 */  swc2       $13, 0x28($a3)
    /* CF84 8001C784 7000EEE8 */  swc2       $14, 0x70($a3)
    /* CF88 8001C788 1400F1E8 */  swc2       $17, 0x14($a3)
    /* CF8C 8001C78C 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* CF90 8001C790 7400F3E8 */  swc2       $19, 0x74($a3)
    /* CF94 8001C794 3000E0C8 */  lwc2       $0, 0x30($a3)
    /* CF98 8001C798 3400E1C8 */  lwc2       $1, 0x34($a3)
    /* CF9C 8001C79C 4800E2C8 */  lwc2       $2, 0x48($a3)
    /* CFA0 8001C7A0 4C00E3C8 */  lwc2       $3, 0x4C($a3)
    /* CFA4 8001C7A4 0C000C91 */  lbu        $t4, 0xC($t0)
    /* CFA8 8001C7A8 3000284A */  rtpt
    /* CFAC 8001C7AC 0C002D91 */  lbu        $t5, 0xC($t1)
    /* CFB0 8001C7B0 0C004E91 */  lbu        $t6, 0xC($t2)
    /* CFB4 8001C7B4 0C006F91 */  lbu        $t7, 0xC($t3)
    /* CFB8 8001C7B8 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* CFBC 8001C7BC 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* CFC0 8001C7C0 43C01800 */  sra        $t8, $t8, 1
    /* CFC4 8001C7C4 43C81900 */  sra        $t9, $t9, 1
    /* CFC8 8001C7C8 3C00F8A0 */  sb         $t8, 0x3C($a3)
    /* CFCC 8001C7CC 2400F9A0 */  sb         $t9, 0x24($a3)
    /* CFD0 8001C7D0 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* CFD4 8001C7D4 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* CFD8 8001C7D8 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* CFDC 8001C7DC 43C01800 */  sra        $t8, $t8, 1
    /* CFE0 8001C7E0 43C81900 */  sra        $t9, $t9, 1
    /* CFE4 8001C7E4 83180300 */  sra        $v1, $v1, 2
    /* CFE8 8001C7E8 0C00F8A0 */  sb         $t8, 0xC($a3)
    /* CFEC 8001C7EC 5400F9A0 */  sb         $t9, 0x54($a3)
    /* CFF0 8001C7F0 6C00E3A0 */  sb         $v1, 0x6C($a3)
    /* CFF4 8001C7F4 0D000C91 */  lbu        $t4, 0xD($t0)
    /* CFF8 8001C7F8 0D002D91 */  lbu        $t5, 0xD($t1)
    /* CFFC 8001C7FC 0D004E91 */  lbu        $t6, 0xD($t2)
    /* D000 8001C800 0D006F91 */  lbu        $t7, 0xD($t3)
    /* D004 8001C804 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* D008 8001C808 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* D00C 8001C80C 43C01800 */  sra        $t8, $t8, 1
    /* D010 8001C810 43C81900 */  sra        $t9, $t9, 1
    /* D014 8001C814 3D00F8A0 */  sb         $t8, 0x3D($a3)
    /* D018 8001C818 2500F9A0 */  sb         $t9, 0x25($a3)
    /* D01C 8001C81C 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* D020 8001C820 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* D024 8001C824 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* D028 8001C828 43C01800 */  sra        $t8, $t8, 1
    /* D02C 8001C82C 43C81900 */  sra        $t9, $t9, 1
    /* D030 8001C830 83180300 */  sra        $v1, $v1, 2
    /* D034 8001C834 0D00F8A0 */  sb         $t8, 0xD($a3)
    /* D038 8001C838 5500F9A0 */  sb         $t9, 0x55($a3)
    /* D03C 8001C83C 6D00E3A0 */  sb         $v1, 0x6D($a3)
    /* D040 8001C840 0E000C91 */  lbu        $t4, 0xE($t0)
    /* D044 8001C844 0E002D91 */  lbu        $t5, 0xE($t1)
    /* D048 8001C848 0E004E91 */  lbu        $t6, 0xE($t2)
    /* D04C 8001C84C 0E006F91 */  lbu        $t7, 0xE($t3)
    /* D050 8001C850 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* D054 8001C854 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* D058 8001C858 43C01800 */  sra        $t8, $t8, 1
    /* D05C 8001C85C 43C81900 */  sra        $t9, $t9, 1
    /* D060 8001C860 3E00F8A0 */  sb         $t8, 0x3E($a3)
    /* D064 8001C864 2600F9A0 */  sb         $t9, 0x26($a3)
    /* D068 8001C868 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* D06C 8001C86C 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* D070 8001C870 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* D074 8001C874 43C01800 */  sra        $t8, $t8, 1
    /* D078 8001C878 43C81900 */  sra        $t9, $t9, 1
    /* D07C 8001C87C 83180300 */  sra        $v1, $v1, 2
    /* D080 8001C880 0E00F8A0 */  sb         $t8, 0xE($a3)
    /* D084 8001C884 5600F9A0 */  sb         $t9, 0x56($a3)
    /* D088 8001C888 6E00E3A0 */  sb         $v1, 0x6E($a3)
    /* D08C 8001C88C 4000ECE8 */  swc2       $12, 0x40($a3)
    /* D090 8001C890 5800EDE8 */  swc2       $13, 0x58($a3)
    /* D094 8001C894 4400F1E8 */  swc2       $17, 0x44($a3)
    /* D098 8001C898 5C00F2E8 */  swc2       $18, 0x5C($a3)
    /* D09C 8001C89C 0000AC8C */  lw         $t4, 0x0($a1)
    /* D0A0 8001C8A0 0100C624 */  addiu      $a2, $a2, 0x1
    /* D0A4 8001C8A4 1E008615 */  bne        $t4, $a2, .L8001C920
    /* D0A8 8001C8A8 00000000 */   nop
    /* D0AC 8001C8AC 2118E003 */  addu       $v1, $ra, $zero
    /* D0B0 8001C8B0 7800E88C */  lw         $t0, 0x78($a3)
    /* D0B4 8001C8B4 0000E924 */  addiu      $t1, $a3, 0x0
    /* D0B8 8001C8B8 1800EA24 */  addiu      $t2, $a3, 0x18
    /* D0BC 8001C8BC 6000EB24 */  addiu      $t3, $a3, 0x60
    /* D0C0 8001C8C0 7872000C */  jal        func_8001C9E0
    /* D0C4 8001C8C4 00000000 */   nop
    /* D0C8 8001C8C8 7C00E88C */  lw         $t0, 0x7C($a3)
    /* D0CC 8001C8CC 3000E924 */  addiu      $t1, $a3, 0x30
    /* D0D0 8001C8D0 0000EA24 */  addiu      $t2, $a3, 0x0
    /* D0D4 8001C8D4 6000EB24 */  addiu      $t3, $a3, 0x60
    /* D0D8 8001C8D8 7872000C */  jal        func_8001C9E0
    /* D0DC 8001C8DC 00000000 */   nop
    /* D0E0 8001C8E0 8000E88C */  lw         $t0, 0x80($a3)
    /* D0E4 8001C8E4 1800E924 */  addiu      $t1, $a3, 0x18
    /* D0E8 8001C8E8 4800EA24 */  addiu      $t2, $a3, 0x48
    /* D0EC 8001C8EC 6000EB24 */  addiu      $t3, $a3, 0x60
    /* D0F0 8001C8F0 7872000C */  jal        func_8001C9E0
    /* D0F4 8001C8F4 00000000 */   nop
    /* D0F8 8001C8F8 8400E88C */  lw         $t0, 0x84($a3)
    /* D0FC 8001C8FC 4800E924 */  addiu      $t1, $a3, 0x48
    /* D100 8001C900 3000EA24 */  addiu      $t2, $a3, 0x30
    /* D104 8001C904 6000EB24 */  addiu      $t3, $a3, 0x60
    /* D108 8001C908 7872000C */  jal        func_8001C9E0
    /* D10C 8001C90C 00000000 */   nop
    /* D110 8001C910 21F86000 */  addu       $ra, $v1, $zero
    /* D114 8001C914 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* D118 8001C918 2E000010 */  b          .L8001C9D4
    /* D11C 8001C91C 00000000 */   nop
  .L8001C920:
    /* D120 8001C920 8C00E724 */  addiu      $a3, $a3, 0x8C
    /* D124 8001C924 8800FFAC */  sw         $ra, 0x88($a3)
    /* D128 8001C928 ECFFEC8C */  lw         $t4, -0x14($a3)
    /* D12C 8001C92C 74FFED24 */  addiu      $t5, $a3, -0x8C
    /* D130 8001C930 8CFFEE24 */  addiu      $t6, $a3, -0x74
    /* D134 8001C934 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* D138 8001C938 7800ECAC */  sw         $t4, 0x78($a3)
    /* D13C 8001C93C 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* D140 8001C940 8000EEAC */  sw         $t6, 0x80($a3)
    /* D144 8001C944 8400EFAC */  sw         $t7, 0x84($a3)
    /* D148 8001C948 1F71000C */  jal        func_8001C47C
    /* D14C 8001C94C 00000000 */   nop
    /* D150 8001C950 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* D154 8001C954 A4FFED24 */  addiu      $t5, $a3, -0x5C
    /* D158 8001C958 74FFEE24 */  addiu      $t6, $a3, -0x8C
    /* D15C 8001C95C D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* D160 8001C960 7800ECAC */  sw         $t4, 0x78($a3)
    /* D164 8001C964 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* D168 8001C968 8000EEAC */  sw         $t6, 0x80($a3)
    /* D16C 8001C96C 8400EFAC */  sw         $t7, 0x84($a3)
    /* D170 8001C970 1F71000C */  jal        func_8001C47C
    /* D174 8001C974 00000000 */   nop
    /* D178 8001C978 F4FFEC8C */  lw         $t4, -0xC($a3)
    /* D17C 8001C97C 8CFFED24 */  addiu      $t5, $a3, -0x74
    /* D180 8001C980 BCFFEE24 */  addiu      $t6, $a3, -0x44
    /* D184 8001C984 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* D188 8001C988 7800ECAC */  sw         $t4, 0x78($a3)
    /* D18C 8001C98C 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* D190 8001C990 8000EEAC */  sw         $t6, 0x80($a3)
    /* D194 8001C994 8400EFAC */  sw         $t7, 0x84($a3)
    /* D198 8001C998 1F71000C */  jal        func_8001C47C
    /* D19C 8001C99C 00000000 */   nop
    /* D1A0 8001C9A0 F8FFEC8C */  lw         $t4, -0x8($a3)
    /* D1A4 8001C9A4 BCFFED24 */  addiu      $t5, $a3, -0x44
    /* D1A8 8001C9A8 A4FFEE24 */  addiu      $t6, $a3, -0x5C
    /* D1AC 8001C9AC D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* D1B0 8001C9B0 7800ECAC */  sw         $t4, 0x78($a3)
    /* D1B4 8001C9B4 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* D1B8 8001C9B8 8000EEAC */  sw         $t6, 0x80($a3)
    /* D1BC 8001C9BC 8400EFAC */  sw         $t7, 0x84($a3)
    /* D1C0 8001C9C0 1F71000C */  jal        func_8001C47C
    /* D1C4 8001C9C4 00000000 */   nop
    /* D1C8 8001C9C8 8800FF8C */  lw         $ra, 0x88($a3)
    /* D1CC 8001C9CC 74FFE724 */  addiu      $a3, $a3, -0x8C
    /* D1D0 8001C9D0 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001C9D4:
    /* D1D4 8001C9D4 21108000 */  addu       $v0, $a0, $zero
    /* D1D8 8001C9D8 0800E003 */  jr         $ra
    /* D1DC 8001C9DC 00000000 */   nop
endlabel func_8001C47C

nonmatching func_8001C9E0, 0xAC

glabel func_8001C9E0
    /* D1E0 8001C9E0 0C00AC94 */  lhu        $t4, 0xC($a1)
    /* D1E4 8001C9E4 08000D95 */  lhu        $t5, 0x8($t0)
    /* D1E8 8001C9E8 00640C00 */  sll        $t4, $t4, 16
    /* D1EC 8001C9EC 2168AC01 */  addu       $t5, $t5, $t4
    /* D1F0 8001C9F0 0E00AC94 */  lhu        $t4, 0xE($a1)
    /* D1F4 8001C9F4 08002E95 */  lhu        $t6, 0x8($t1)
    /* D1F8 8001C9F8 00640C00 */  sll        $t4, $t4, 16
    /* D1FC 8001C9FC 2170CC01 */  addu       $t6, $t6, $t4
    /* D200 8001CA00 08004F95 */  lhu        $t7, 0x8($t2)
    /* D204 8001CA04 08007895 */  lhu        $t8, 0x8($t3)
    /* D208 8001CA08 1300AC80 */  lb         $t4, 0x13($a1)
    /* D20C 8001CA0C 0C008DAC */  sw         $t5, 0xC($a0)
    /* D210 8001CA10 18008EAC */  sw         $t6, 0x18($a0)
    /* D214 8001CA14 24008FAC */  sw         $t7, 0x24($a0)
    /* D218 8001CA18 300098AC */  sw         $t8, 0x30($a0)
    /* D21C 8001CA1C 0F000CA1 */  sb         $t4, 0xF($t0)
    /* D220 8001CA20 10000C8D */  lw         $t4, 0x10($t0)
    /* D224 8001CA24 10002D8D */  lw         $t5, 0x10($t1)
    /* D228 8001CA28 10004E8D */  lw         $t6, 0x10($t2)
    /* D22C 8001CA2C 10006F8D */  lw         $t7, 0x10($t3)
    /* D230 8001CA30 08008CAC */  sw         $t4, 0x8($a0)
    /* D234 8001CA34 14008DAC */  sw         $t5, 0x14($a0)
    /* D238 8001CA38 20008EAC */  sw         $t6, 0x20($a0)
    /* D23C 8001CA3C 2C008FAC */  sw         $t7, 0x2C($a0)
    /* D240 8001CA40 1400AC8C */  lw         $t4, 0x14($a1)
    /* D244 8001CA44 00CA0400 */  sll        $t9, $a0, 8
    /* D248 8001CA48 02CA1900 */  srl        $t9, $t9, 8
    /* D24C 8001CA4C 0000988D */  lw         $t8, 0x0($t4)
    /* D250 8001CA50 000099AD */  sw         $t9, 0x0($t4)
    /* D254 8001CA54 000C0E3C */  lui        $t6, (0xC000000 >> 16)
    /* D258 8001CA58 25C00E03 */  or         $t8, $t8, $t6
    /* D25C 8001CA5C 0C000C8D */  lw         $t4, 0xC($t0)
    /* D260 8001CA60 0C002D8D */  lw         $t5, 0xC($t1)
    /* D264 8001CA64 0C004E8D */  lw         $t6, 0xC($t2)
    /* D268 8001CA68 0C006F8D */  lw         $t7, 0xC($t3)
    /* D26C 8001CA6C 04008CAC */  sw         $t4, 0x4($a0)
    /* D270 8001CA70 10008DAC */  sw         $t5, 0x10($a0)
    /* D274 8001CA74 1C008EAC */  sw         $t6, 0x1C($a0)
    /* D278 8001CA78 28008FAC */  sw         $t7, 0x28($a0)
    /* D27C 8001CA7C 000098AC */  sw         $t8, 0x0($a0)
    /* D280 8001CA80 34008424 */  addiu      $a0, $a0, 0x34
    /* D284 8001CA84 0800E003 */  jr         $ra
    /* D288 8001CA88 00000000 */   nop
endlabel func_8001C9E0
    /* D28C 8001CA8C 00000000 */  nop
    /* D290 8001CA90 00000000 */  nop
