.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching func_8001A564, 0x8

glabel func_8001A564
    /* AD64 8001A564 6000A720 */  addi       $a3, $a1, 0x60 /* handwritten instruction */
    /* AD68 8001A568 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001A564

/* Handwritten function */
nonmatching func_8001A56C, 0x318

glabel func_8001A56C
    /* AD6C 8001A56C 4800E88C */  lw         $t0, 0x48($a3)
    /* AD70 8001A570 4C00E98C */  lw         $t1, 0x4C($a3)
    /* AD74 8001A574 5000EA8C */  lw         $t2, 0x50($a3)
    /* AD78 8001A578 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* AD7C 8001A57C 14000C8D */  lw         $t4, 0x14($t0)
    /* AD80 8001A580 14002D8D */  lw         $t5, 0x14($t1)
    /* AD84 8001A584 14004E8D */  lw         $t6, 0x14($t2)
    /* AD88 8001A588 43C01900 */  sra        $t8, $t9, 1
    /* AD8C 8001A58C 2B089801 */  sltu       $at, $t4, $t8
    /* AD90 8001A590 08002010 */  beqz       $at, .L8001A5B4
    /* AD94 8001A594 2B08B801 */   sltu      $at, $t5, $t8
    /* AD98 8001A598 06002010 */  beqz       $at, .L8001A5B4
    /* AD9C 8001A59C 2B08D801 */   sltu      $at, $t6, $t8
    /* ADA0 8001A5A0 04002010 */  beqz       $at, .L8001A5B4
    /* ADA4 8001A5A4 00000000 */   nop
    /* ADA8 8001A5A8 21108000 */  addu       $v0, $a0, $zero
    /* ADAC 8001A5AC 0800E003 */  jr         $ra
    /* ADB0 8001A5B0 00000000 */   nop
  .L8001A5B4:
    /* ADB4 8001A5B4 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* ADB8 8001A5B8 0400A28C */  lw         $v0, 0x4($a1)
    /* ADBC 8001A5BC 0800A38C */  lw         $v1, 0x8($a1)
    /* ADC0 8001A5C0 03CC1900 */  sra        $t9, $t9, 16
    /* ADC4 8001A5C4 42100200 */  srl        $v0, $v0, 1
    /* ADC8 8001A5C8 42180300 */  srl        $v1, $v1, 1
    /* ADCC 8001A5CC 21C02203 */  addu       $t8, $t9, $v0
    /* ADD0 8001A5D0 10000C85 */  lh         $t4, 0x10($t0)
    /* ADD4 8001A5D4 10002D85 */  lh         $t5, 0x10($t1)
    /* ADD8 8001A5D8 10004E85 */  lh         $t6, 0x10($t2)
    /* ADDC 8001A5DC 2A080C03 */  slt        $at, $t8, $t4
    /* ADE0 8001A5E0 08002010 */  beqz       $at, .L8001A604
    /* ADE4 8001A5E4 2A080D03 */   slt       $at, $t8, $t5
    /* ADE8 8001A5E8 06002010 */  beqz       $at, .L8001A604
    /* ADEC 8001A5EC 2A080E03 */   slt       $at, $t8, $t6
    /* ADF0 8001A5F0 04002010 */  beqz       $at, .L8001A604
    /* ADF4 8001A5F4 00000000 */   nop
    /* ADF8 8001A5F8 21108000 */  addu       $v0, $a0, $zero
    /* ADFC 8001A5FC 0800E003 */  jr         $ra
    /* AE00 8001A600 00000000 */   nop
  .L8001A604:
    /* AE04 8001A604 23C02203 */  subu       $t8, $t9, $v0
    /* AE08 8001A608 2A089801 */  slt        $at, $t4, $t8
    /* AE0C 8001A60C 08002010 */  beqz       $at, .L8001A630
    /* AE10 8001A610 2A08B801 */   slt       $at, $t5, $t8
    /* AE14 8001A614 06002010 */  beqz       $at, .L8001A630
    /* AE18 8001A618 2A08D801 */   slt       $at, $t6, $t8
    /* AE1C 8001A61C 04002010 */  beqz       $at, .L8001A630
    /* AE20 8001A620 00000000 */   nop
    /* AE24 8001A624 21108000 */  addu       $v0, $a0, $zero
    /* AE28 8001A628 0800E003 */  jr         $ra
    /* AE2C 8001A62C 00000000 */   nop
  .L8001A630:
    /* AE30 8001A630 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* AE34 8001A634 12000C85 */  lh         $t4, 0x12($t0)
    /* AE38 8001A638 12002D85 */  lh         $t5, 0x12($t1)
    /* AE3C 8001A63C 12004E85 */  lh         $t6, 0x12($t2)
    /* AE40 8001A640 03CC1900 */  sra        $t9, $t9, 16
    /* AE44 8001A644 21C02303 */  addu       $t8, $t9, $v1
    /* AE48 8001A648 2A080C03 */  slt        $at, $t8, $t4
    /* AE4C 8001A64C 08002010 */  beqz       $at, .L8001A670
    /* AE50 8001A650 2A080D03 */   slt       $at, $t8, $t5
    /* AE54 8001A654 06002010 */  beqz       $at, .L8001A670
    /* AE58 8001A658 2A080E03 */   slt       $at, $t8, $t6
    /* AE5C 8001A65C 04002010 */  beqz       $at, .L8001A670
    /* AE60 8001A660 00000000 */   nop
    /* AE64 8001A664 21108000 */  addu       $v0, $a0, $zero
    /* AE68 8001A668 0800E003 */  jr         $ra
    /* AE6C 8001A66C 00000000 */   nop
  .L8001A670:
    /* AE70 8001A670 23C02303 */  subu       $t8, $t9, $v1
    /* AE74 8001A674 2A089801 */  slt        $at, $t4, $t8
    /* AE78 8001A678 08002010 */  beqz       $at, .L8001A69C
    /* AE7C 8001A67C 2A08B801 */   slt       $at, $t5, $t8
    /* AE80 8001A680 06002010 */  beqz       $at, .L8001A69C
    /* AE84 8001A684 2A08D801 */   slt       $at, $t6, $t8
    /* AE88 8001A688 04002010 */  beqz       $at, .L8001A69C
    /* AE8C 8001A68C 00000000 */   nop
    /* AE90 8001A690 21108000 */  addu       $v0, $a0, $zero
    /* AE94 8001A694 0800E003 */  jr         $ra
    /* AE98 8001A698 00000000 */   nop
  .L8001A69C:
    /* AE9C 8001A69C 00000C85 */  lh         $t4, 0x0($t0)
    /* AEA0 8001A6A0 00002D85 */  lh         $t5, 0x0($t1)
    /* AEA4 8001A6A4 00004E85 */  lh         $t6, 0x0($t2)
    /* AEA8 8001A6A8 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* AEAC 8001A6AC 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* AEB0 8001A6B0 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* AEB4 8001A6B4 43780F00 */  sra        $t7, $t7, 1
    /* AEB8 8001A6B8 43C01800 */  sra        $t8, $t8, 1
    /* AEBC 8001A6BC 43C81900 */  sra        $t9, $t9, 1
    /* AEC0 8001A6C0 0000EFA4 */  sh         $t7, 0x0($a3)
    /* AEC4 8001A6C4 1800F8A4 */  sh         $t8, 0x18($a3)
    /* AEC8 8001A6C8 3000F9A4 */  sh         $t9, 0x30($a3)
    /* AECC 8001A6CC 02000C85 */  lh         $t4, 0x2($t0)
    /* AED0 8001A6D0 02002D85 */  lh         $t5, 0x2($t1)
    /* AED4 8001A6D4 02004E85 */  lh         $t6, 0x2($t2)
    /* AED8 8001A6D8 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* AEDC 8001A6DC 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* AEE0 8001A6E0 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* AEE4 8001A6E4 43780F00 */  sra        $t7, $t7, 1
    /* AEE8 8001A6E8 43C01800 */  sra        $t8, $t8, 1
    /* AEEC 8001A6EC 43C81900 */  sra        $t9, $t9, 1
    /* AEF0 8001A6F0 0200EFA4 */  sh         $t7, 0x2($a3)
    /* AEF4 8001A6F4 1A00F8A4 */  sh         $t8, 0x1A($a3)
    /* AEF8 8001A6F8 3200F9A4 */  sh         $t9, 0x32($a3)
    /* AEFC 8001A6FC 04000C85 */  lh         $t4, 0x4($t0)
    /* AF00 8001A700 04002D85 */  lh         $t5, 0x4($t1)
    /* AF04 8001A704 04004E85 */  lh         $t6, 0x4($t2)
    /* AF08 8001A708 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* AF0C 8001A70C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* AF10 8001A710 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* AF14 8001A714 43780F00 */  sra        $t7, $t7, 1
    /* AF18 8001A718 43C01800 */  sra        $t8, $t8, 1
    /* AF1C 8001A71C 43C81900 */  sra        $t9, $t9, 1
    /* AF20 8001A720 0400EFA4 */  sh         $t7, 0x4($a3)
    /* AF24 8001A724 1C00F8A4 */  sh         $t8, 0x1C($a3)
    /* AF28 8001A728 3400F9A4 */  sh         $t9, 0x34($a3)
    /* AF2C 8001A72C 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* AF30 8001A730 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* AF34 8001A734 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* AF38 8001A738 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* AF3C 8001A73C 3000E4C8 */  lwc2       $4, 0x30($a3)
    /* AF40 8001A740 3400E5C8 */  lwc2       $5, 0x34($a3)
    /* AF44 8001A744 00000000 */  nop
    /* AF48 8001A748 3000284A */  rtpt
    /* AF4C 8001A74C 0000AC8C */  lw         $t4, 0x0($a1)
    /* AF50 8001A750 0100C624 */  addiu      $a2, $a2, 0x1
    /* AF54 8001A754 1D008615 */  bne        $t4, $a2, .L8001A7CC
    /* AF58 8001A758 00000000 */   nop
    /* AF5C 8001A75C 2118E003 */  addu       $v1, $ra, $zero
    /* AF60 8001A760 4C00E88C */  lw         $t0, 0x4C($a3)
    /* AF64 8001A764 1800E924 */  addiu      $t1, $a3, 0x18
    /* AF68 8001A768 0000EA24 */  addiu      $t2, $a3, 0x0
    /* AF6C 8001A76C 1000ECE8 */  swc2       $12, 0x10($a3)
    /* AF70 8001A770 2800EDE8 */  swc2       $13, 0x28($a3)
    /* AF74 8001A774 4000EEE8 */  swc2       $14, 0x40($a3)
    /* AF78 8001A778 216A000C */  jal        func_8001A884
    /* AF7C 8001A77C 00000000 */   nop
    /* AF80 8001A780 0000E824 */  addiu      $t0, $a3, 0x0
    /* AF84 8001A784 1800E924 */  addiu      $t1, $a3, 0x18
    /* AF88 8001A788 3000EA24 */  addiu      $t2, $a3, 0x30
    /* AF8C 8001A78C 216A000C */  jal        func_8001A884
    /* AF90 8001A790 00000000 */   nop
    /* AF94 8001A794 4800E88C */  lw         $t0, 0x48($a3)
    /* AF98 8001A798 0000E924 */  addiu      $t1, $a3, 0x0
    /* AF9C 8001A79C 3000EA24 */  addiu      $t2, $a3, 0x30
    /* AFA0 8001A7A0 216A000C */  jal        func_8001A884
    /* AFA4 8001A7A4 00000000 */   nop
    /* AFA8 8001A7A8 5000E88C */  lw         $t0, 0x50($a3)
    /* AFAC 8001A7AC 3000E924 */  addiu      $t1, $a3, 0x30
    /* AFB0 8001A7B0 1800EA24 */  addiu      $t2, $a3, 0x18
    /* AFB4 8001A7B4 216A000C */  jal        func_8001A884
    /* AFB8 8001A7B8 00000000 */   nop
    /* AFBC 8001A7BC 21F86000 */  addu       $ra, $v1, $zero
    /* AFC0 8001A7C0 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* AFC4 8001A7C4 2C000010 */  b          .L8001A878
    /* AFC8 8001A7C8 00000000 */   nop
  .L8001A7CC:
    /* AFCC 8001A7CC 5800E724 */  addiu      $a3, $a3, 0x58
    /* AFD0 8001A7D0 5400FFAC */  sw         $ra, 0x54($a3)
    /* AFD4 8001A7D4 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* AFD8 8001A7D8 A8FFED24 */  addiu      $t5, $a3, -0x58
    /* AFDC 8001A7DC D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* AFE0 8001A7E0 4800ECAC */  sw         $t4, 0x48($a3)
    /* AFE4 8001A7E4 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* AFE8 8001A7E8 5000EEAC */  sw         $t6, 0x50($a3)
    /* AFEC 8001A7EC BCFFF1E8 */  swc2       $17, -0x44($a3)
    /* AFF0 8001A7F0 D4FFF2E8 */  swc2       $18, -0x2C($a3)
    /* AFF4 8001A7F4 ECFFF3E8 */  swc2       $19, -0x14($a3)
    /* AFF8 8001A7F8 B8FFECE8 */  swc2       $12, -0x48($a3)
    /* AFFC 8001A7FC D0FFEDE8 */  swc2       $13, -0x30($a3)
    /* B000 8001A800 E8FFEEE8 */  swc2       $14, -0x18($a3)
    /* B004 8001A804 5B69000C */  jal        func_8001A56C
    /* B008 8001A808 00000000 */   nop
    /* B00C 8001A80C F4FFEC8C */  lw         $t4, -0xC($a3)
    /* B010 8001A810 C0FFED24 */  addiu      $t5, $a3, -0x40
    /* B014 8001A814 A8FFEE24 */  addiu      $t6, $a3, -0x58
    /* B018 8001A818 4800ECAC */  sw         $t4, 0x48($a3)
    /* B01C 8001A81C 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B020 8001A820 5000EEAC */  sw         $t6, 0x50($a3)
    /* B024 8001A824 5B69000C */  jal        func_8001A56C
    /* B028 8001A828 00000000 */   nop
    /* B02C 8001A82C F8FFEC8C */  lw         $t4, -0x8($a3)
    /* B030 8001A830 D8FFED24 */  addiu      $t5, $a3, -0x28
    /* B034 8001A834 C0FFEE24 */  addiu      $t6, $a3, -0x40
    /* B038 8001A838 4800ECAC */  sw         $t4, 0x48($a3)
    /* B03C 8001A83C 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B040 8001A840 5000EEAC */  sw         $t6, 0x50($a3)
    /* B044 8001A844 5B69000C */  jal        func_8001A56C
    /* B048 8001A848 00000000 */   nop
    /* B04C 8001A84C A8FFEC24 */  addiu      $t4, $a3, -0x58
    /* B050 8001A850 C0FFED24 */  addiu      $t5, $a3, -0x40
    /* B054 8001A854 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* B058 8001A858 4800ECAC */  sw         $t4, 0x48($a3)
    /* B05C 8001A85C 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B060 8001A860 5000EEAC */  sw         $t6, 0x50($a3)
    /* B064 8001A864 5B69000C */  jal        func_8001A56C
    /* B068 8001A868 00000000 */   nop
    /* B06C 8001A86C 5400FF8C */  lw         $ra, 0x54($a3)
    /* B070 8001A870 A8FFE724 */  addiu      $a3, $a3, -0x58
    /* B074 8001A874 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001A878:
    /* B078 8001A878 21108000 */  addu       $v0, $a0, $zero
    /* B07C 8001A87C 0800E003 */  jr         $ra
    /* B080 8001A880 00000000 */   nop
endlabel func_8001A56C

nonmatching func_8001A884, 0x4C

glabel func_8001A884
    /* B084 8001A884 1000B88C */  lw         $t8, 0x10($a1)
    /* B088 8001A888 10000C8D */  lw         $t4, 0x10($t0)
    /* B08C 8001A88C 10002D8D */  lw         $t5, 0x10($t1)
    /* B090 8001A890 10004E8D */  lw         $t6, 0x10($t2)
    /* B094 8001A894 08008CAC */  sw         $t4, 0x8($a0)
    /* B098 8001A898 0C008DAC */  sw         $t5, 0xC($a0)
    /* B09C 8001A89C 10008EAC */  sw         $t6, 0x10($a0)
    /* B0A0 8001A8A0 040098AC */  sw         $t8, 0x4($a0)
    /* B0A4 8001A8A4 1400AC8C */  lw         $t4, 0x14($a1)
    /* B0A8 8001A8A8 00CA0400 */  sll        $t9, $a0, 8
    /* B0AC 8001A8AC 02CA1900 */  srl        $t9, $t9, 8
    /* B0B0 8001A8B0 0000988D */  lw         $t8, 0x0($t4)
    /* B0B4 8001A8B4 000099AD */  sw         $t9, 0x0($t4)
    /* B0B8 8001A8B8 00040E3C */  lui        $t6, (0x4000000 >> 16)
    /* B0BC 8001A8BC 25C00E03 */  or         $t8, $t8, $t6
    /* B0C0 8001A8C0 000098AC */  sw         $t8, 0x0($a0)
    /* B0C4 8001A8C4 14008424 */  addiu      $a0, $a0, 0x14
    /* B0C8 8001A8C8 0800E003 */  jr         $ra
    /* B0CC 8001A8CC 00000000 */   nop
endlabel func_8001A884
    /* B0D0 8001A8D0 00000000 */  nop
