.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching rand, 0x28

glabel rand
    /* 39C80 80049480 C641033C */  lui        $v1, (0x41C64E6D >> 16)
    /* 39C84 80049484 6004828F */  lw         $v0, %gp_rel(Small__rand)($gp)
    /* 39C88 80049488 6D4E6334 */  ori        $v1, $v1, (0x41C64E6D & 0xFFFF)
    /* 39C8C 8004948C 18004300 */  mult       $v0, $v1
    /* 39C90 80049490 12100000 */  mflo       $v0
    /* 39C94 80049494 39304224 */  addiu      $v0, $v0, 0x3039
    /* 39C98 80049498 600482AF */  sw         $v0, %gp_rel(Small__rand)($gp)
    /* 39C9C 8004949C 02140200 */  srl        $v0, $v0, 16
    /* 39CA0 800494A0 0800E003 */  jr         $ra
    /* 39CA4 800494A4 FF7F4230 */   andi      $v0, $v0, 0x7FFF
endlabel rand

nonmatching srand, 0xC

glabel srand
    /* 39CA8 800494A8 600484AF */  sw         $a0, %gp_rel(Small__rand)($gp)
    /* 39CAC 800494AC 0800E003 */  jr         $ra
    /* 39CB0 800494B0 00000000 */   nop
endlabel srand
