.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching func_8001BAB4, 0x8

glabel func_8001BAB4
    /* C2B4 8001BAB4 7800A720 */  addi       $a3, $a1, 0x78 /* handwritten instruction */
    /* C2B8 8001BAB8 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001BAB4

/* Handwritten function */
nonmatching func_8001BABC, 0x488

glabel func_8001BABC
    /* C2BC 8001BABC 7800E88C */  lw         $t0, 0x78($a3)
    /* C2C0 8001BAC0 7C00E98C */  lw         $t1, 0x7C($a3)
    /* C2C4 8001BAC4 8000EA8C */  lw         $t2, 0x80($a3)
    /* C2C8 8001BAC8 8400EB8C */  lw         $t3, 0x84($a3)
    /* C2CC 8001BACC 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* C2D0 8001BAD0 14000C8D */  lw         $t4, 0x14($t0)
    /* C2D4 8001BAD4 14002D8D */  lw         $t5, 0x14($t1)
    /* C2D8 8001BAD8 14004E8D */  lw         $t6, 0x14($t2)
    /* C2DC 8001BADC 14006F8D */  lw         $t7, 0x14($t3)
    /* C2E0 8001BAE0 43C01900 */  sra        $t8, $t9, 1
    /* C2E4 8001BAE4 2B089801 */  sltu       $at, $t4, $t8
    /* C2E8 8001BAE8 0A002010 */  beqz       $at, .L8001BB14
    /* C2EC 8001BAEC 2B08B801 */   sltu      $at, $t5, $t8
    /* C2F0 8001BAF0 08002010 */  beqz       $at, .L8001BB14
    /* C2F4 8001BAF4 2B08D801 */   sltu      $at, $t6, $t8
    /* C2F8 8001BAF8 06002010 */  beqz       $at, .L8001BB14
    /* C2FC 8001BAFC 2B08F801 */   sltu      $at, $t7, $t8
    /* C300 8001BB00 04002010 */  beqz       $at, .L8001BB14
    /* C304 8001BB04 00000000 */   nop
    /* C308 8001BB08 21108000 */  addu       $v0, $a0, $zero
    /* C30C 8001BB0C 0800E003 */  jr         $ra
    /* C310 8001BB10 00000000 */   nop
  .L8001BB14:
    /* C314 8001BB14 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* C318 8001BB18 0400A28C */  lw         $v0, 0x4($a1)
    /* C31C 8001BB1C 0800A38C */  lw         $v1, 0x8($a1)
    /* C320 8001BB20 03CC1900 */  sra        $t9, $t9, 16
    /* C324 8001BB24 42100200 */  srl        $v0, $v0, 1
    /* C328 8001BB28 42180300 */  srl        $v1, $v1, 1
    /* C32C 8001BB2C 21C02203 */  addu       $t8, $t9, $v0
    /* C330 8001BB30 10000C85 */  lh         $t4, 0x10($t0)
    /* C334 8001BB34 10002D85 */  lh         $t5, 0x10($t1)
    /* C338 8001BB38 10004E85 */  lh         $t6, 0x10($t2)
    /* C33C 8001BB3C 10006F85 */  lh         $t7, 0x10($t3)
    /* C340 8001BB40 2A080C03 */  slt        $at, $t8, $t4
    /* C344 8001BB44 0A002010 */  beqz       $at, .L8001BB70
    /* C348 8001BB48 2A080D03 */   slt       $at, $t8, $t5
    /* C34C 8001BB4C 08002010 */  beqz       $at, .L8001BB70
    /* C350 8001BB50 2A080E03 */   slt       $at, $t8, $t6
    /* C354 8001BB54 06002010 */  beqz       $at, .L8001BB70
    /* C358 8001BB58 2A080F03 */   slt       $at, $t8, $t7
    /* C35C 8001BB5C 04002010 */  beqz       $at, .L8001BB70
    /* C360 8001BB60 00000000 */   nop
    /* C364 8001BB64 21108000 */  addu       $v0, $a0, $zero
    /* C368 8001BB68 0800E003 */  jr         $ra
    /* C36C 8001BB6C 00000000 */   nop
  .L8001BB70:
    /* C370 8001BB70 23C02203 */  subu       $t8, $t9, $v0
    /* C374 8001BB74 2A089801 */  slt        $at, $t4, $t8
    /* C378 8001BB78 0A002010 */  beqz       $at, .L8001BBA4
    /* C37C 8001BB7C 2A08B801 */   slt       $at, $t5, $t8
    /* C380 8001BB80 08002010 */  beqz       $at, .L8001BBA4
    /* C384 8001BB84 2A08D801 */   slt       $at, $t6, $t8
    /* C388 8001BB88 06002010 */  beqz       $at, .L8001BBA4
    /* C38C 8001BB8C 2A08F801 */   slt       $at, $t7, $t8
    /* C390 8001BB90 04002010 */  beqz       $at, .L8001BBA4
    /* C394 8001BB94 00000000 */   nop
    /* C398 8001BB98 21108000 */  addu       $v0, $a0, $zero
    /* C39C 8001BB9C 0800E003 */  jr         $ra
    /* C3A0 8001BBA0 00000000 */   nop
  .L8001BBA4:
    /* C3A4 8001BBA4 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* C3A8 8001BBA8 12000C85 */  lh         $t4, 0x12($t0)
    /* C3AC 8001BBAC 12002D85 */  lh         $t5, 0x12($t1)
    /* C3B0 8001BBB0 12004E85 */  lh         $t6, 0x12($t2)
    /* C3B4 8001BBB4 12006F85 */  lh         $t7, 0x12($t3)
    /* C3B8 8001BBB8 03CC1900 */  sra        $t9, $t9, 16
    /* C3BC 8001BBBC 21C02303 */  addu       $t8, $t9, $v1
    /* C3C0 8001BBC0 2A080C03 */  slt        $at, $t8, $t4
    /* C3C4 8001BBC4 0A002010 */  beqz       $at, .L8001BBF0
    /* C3C8 8001BBC8 2A080D03 */   slt       $at, $t8, $t5
    /* C3CC 8001BBCC 08002010 */  beqz       $at, .L8001BBF0
    /* C3D0 8001BBD0 2A080E03 */   slt       $at, $t8, $t6
    /* C3D4 8001BBD4 06002010 */  beqz       $at, .L8001BBF0
    /* C3D8 8001BBD8 2A080F03 */   slt       $at, $t8, $t7
    /* C3DC 8001BBDC 04002010 */  beqz       $at, .L8001BBF0
    /* C3E0 8001BBE0 00000000 */   nop
    /* C3E4 8001BBE4 21108000 */  addu       $v0, $a0, $zero
    /* C3E8 8001BBE8 0800E003 */  jr         $ra
    /* C3EC 8001BBEC 00000000 */   nop
  .L8001BBF0:
    /* C3F0 8001BBF0 23C02303 */  subu       $t8, $t9, $v1
    /* C3F4 8001BBF4 2A089801 */  slt        $at, $t4, $t8
    /* C3F8 8001BBF8 0A002010 */  beqz       $at, .L8001BC24
    /* C3FC 8001BBFC 2A08B801 */   slt       $at, $t5, $t8
    /* C400 8001BC00 08002010 */  beqz       $at, .L8001BC24
    /* C404 8001BC04 2A08D801 */   slt       $at, $t6, $t8
    /* C408 8001BC08 06002010 */  beqz       $at, .L8001BC24
    /* C40C 8001BC0C 2A08F801 */   slt       $at, $t7, $t8
    /* C410 8001BC10 04002010 */  beqz       $at, .L8001BC24
    /* C414 8001BC14 00000000 */   nop
    /* C418 8001BC18 21108000 */  addu       $v0, $a0, $zero
    /* C41C 8001BC1C 0800E003 */  jr         $ra
    /* C420 8001BC20 00000000 */   nop
  .L8001BC24:
    /* C424 8001BC24 00000C85 */  lh         $t4, 0x0($t0)
    /* C428 8001BC28 00002D85 */  lh         $t5, 0x0($t1)
    /* C42C 8001BC2C 00004E85 */  lh         $t6, 0x0($t2)
    /* C430 8001BC30 00006F85 */  lh         $t7, 0x0($t3)
    /* C434 8001BC34 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* C438 8001BC38 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* C43C 8001BC3C 43C01800 */  sra        $t8, $t8, 1
    /* C440 8001BC40 43C81900 */  sra        $t9, $t9, 1
    /* C444 8001BC44 3000F8A4 */  sh         $t8, 0x30($a3)
    /* C448 8001BC48 1800F9A4 */  sh         $t9, 0x18($a3)
    /* C44C 8001BC4C 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* C450 8001BC50 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* C454 8001BC54 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* C458 8001BC58 43C01800 */  sra        $t8, $t8, 1
    /* C45C 8001BC5C 43C81900 */  sra        $t9, $t9, 1
    /* C460 8001BC60 83180300 */  sra        $v1, $v1, 2
    /* C464 8001BC64 0000F8A4 */  sh         $t8, 0x0($a3)
    /* C468 8001BC68 4800F9A4 */  sh         $t9, 0x48($a3)
    /* C46C 8001BC6C 6000E3A4 */  sh         $v1, 0x60($a3)
    /* C470 8001BC70 02000C85 */  lh         $t4, 0x2($t0)
    /* C474 8001BC74 02002D85 */  lh         $t5, 0x2($t1)
    /* C478 8001BC78 02004E85 */  lh         $t6, 0x2($t2)
    /* C47C 8001BC7C 02006F85 */  lh         $t7, 0x2($t3)
    /* C480 8001BC80 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* C484 8001BC84 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* C488 8001BC88 43C01800 */  sra        $t8, $t8, 1
    /* C48C 8001BC8C 43C81900 */  sra        $t9, $t9, 1
    /* C490 8001BC90 3200F8A4 */  sh         $t8, 0x32($a3)
    /* C494 8001BC94 1A00F9A4 */  sh         $t9, 0x1A($a3)
    /* C498 8001BC98 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* C49C 8001BC9C 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* C4A0 8001BCA0 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* C4A4 8001BCA4 43C01800 */  sra        $t8, $t8, 1
    /* C4A8 8001BCA8 43C81900 */  sra        $t9, $t9, 1
    /* C4AC 8001BCAC 83180300 */  sra        $v1, $v1, 2
    /* C4B0 8001BCB0 0200F8A4 */  sh         $t8, 0x2($a3)
    /* C4B4 8001BCB4 4A00F9A4 */  sh         $t9, 0x4A($a3)
    /* C4B8 8001BCB8 6200E3A4 */  sh         $v1, 0x62($a3)
    /* C4BC 8001BCBC 04000C85 */  lh         $t4, 0x4($t0)
    /* C4C0 8001BCC0 04002D85 */  lh         $t5, 0x4($t1)
    /* C4C4 8001BCC4 04004E85 */  lh         $t6, 0x4($t2)
    /* C4C8 8001BCC8 04006F85 */  lh         $t7, 0x4($t3)
    /* C4CC 8001BCCC 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* C4D0 8001BCD0 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* C4D4 8001BCD4 43C01800 */  sra        $t8, $t8, 1
    /* C4D8 8001BCD8 43C81900 */  sra        $t9, $t9, 1
    /* C4DC 8001BCDC 3400F8A4 */  sh         $t8, 0x34($a3)
    /* C4E0 8001BCE0 1C00F9A4 */  sh         $t9, 0x1C($a3)
    /* C4E4 8001BCE4 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* C4E8 8001BCE8 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* C4EC 8001BCEC 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* C4F0 8001BCF0 43C01800 */  sra        $t8, $t8, 1
    /* C4F4 8001BCF4 43C81900 */  sra        $t9, $t9, 1
    /* C4F8 8001BCF8 83180300 */  sra        $v1, $v1, 2
    /* C4FC 8001BCFC 0400F8A4 */  sh         $t8, 0x4($a3)
    /* C500 8001BD00 4C00F9A4 */  sh         $t9, 0x4C($a3)
    /* C504 8001BD04 6400E3A4 */  sh         $v1, 0x64($a3)
    /* C508 8001BD08 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* C50C 8001BD0C 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* C510 8001BD10 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* C514 8001BD14 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* C518 8001BD18 6000E4C8 */  lwc2       $4, 0x60($a3)
    /* C51C 8001BD1C 6400E5C8 */  lwc2       $5, 0x64($a3)
    /* C520 8001BD20 08000C91 */  lbu        $t4, 0x8($t0)
    /* C524 8001BD24 3000284A */  rtpt
    /* C528 8001BD28 08002D91 */  lbu        $t5, 0x8($t1)
    /* C52C 8001BD2C 08004E91 */  lbu        $t6, 0x8($t2)
    /* C530 8001BD30 08006F91 */  lbu        $t7, 0x8($t3)
    /* C534 8001BD34 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* C538 8001BD38 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* C53C 8001BD3C 43C01800 */  sra        $t8, $t8, 1
    /* C540 8001BD40 43C81900 */  sra        $t9, $t9, 1
    /* C544 8001BD44 3800F8A0 */  sb         $t8, 0x38($a3)
    /* C548 8001BD48 2000F9A0 */  sb         $t9, 0x20($a3)
    /* C54C 8001BD4C 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* C550 8001BD50 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* C554 8001BD54 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* C558 8001BD58 43C01800 */  sra        $t8, $t8, 1
    /* C55C 8001BD5C 43C81900 */  sra        $t9, $t9, 1
    /* C560 8001BD60 83180300 */  sra        $v1, $v1, 2
    /* C564 8001BD64 0800F8A0 */  sb         $t8, 0x8($a3)
    /* C568 8001BD68 5000F9A0 */  sb         $t9, 0x50($a3)
    /* C56C 8001BD6C 6800E3A0 */  sb         $v1, 0x68($a3)
    /* C570 8001BD70 1000ECE8 */  swc2       $12, 0x10($a3)
    /* C574 8001BD74 2800EDE8 */  swc2       $13, 0x28($a3)
    /* C578 8001BD78 7000EEE8 */  swc2       $14, 0x70($a3)
    /* C57C 8001BD7C 1400F1E8 */  swc2       $17, 0x14($a3)
    /* C580 8001BD80 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* C584 8001BD84 7400F3E8 */  swc2       $19, 0x74($a3)
    /* C588 8001BD88 3000E0C8 */  lwc2       $0, 0x30($a3)
    /* C58C 8001BD8C 3400E1C8 */  lwc2       $1, 0x34($a3)
    /* C590 8001BD90 4800E2C8 */  lwc2       $2, 0x48($a3)
    /* C594 8001BD94 4C00E3C8 */  lwc2       $3, 0x4C($a3)
    /* C598 8001BD98 09000C91 */  lbu        $t4, 0x9($t0)
    /* C59C 8001BD9C 3000284A */  rtpt
    /* C5A0 8001BDA0 09002D91 */  lbu        $t5, 0x9($t1)
    /* C5A4 8001BDA4 09004E91 */  lbu        $t6, 0x9($t2)
    /* C5A8 8001BDA8 09006F91 */  lbu        $t7, 0x9($t3)
    /* C5AC 8001BDAC 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* C5B0 8001BDB0 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* C5B4 8001BDB4 43C01800 */  sra        $t8, $t8, 1
    /* C5B8 8001BDB8 43C81900 */  sra        $t9, $t9, 1
    /* C5BC 8001BDBC 3900F8A0 */  sb         $t8, 0x39($a3)
    /* C5C0 8001BDC0 2100F9A0 */  sb         $t9, 0x21($a3)
    /* C5C4 8001BDC4 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* C5C8 8001BDC8 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* C5CC 8001BDCC 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* C5D0 8001BDD0 43C01800 */  sra        $t8, $t8, 1
    /* C5D4 8001BDD4 43C81900 */  sra        $t9, $t9, 1
    /* C5D8 8001BDD8 83180300 */  sra        $v1, $v1, 2
    /* C5DC 8001BDDC 0900F8A0 */  sb         $t8, 0x9($a3)
    /* C5E0 8001BDE0 5100F9A0 */  sb         $t9, 0x51($a3)
    /* C5E4 8001BDE4 6900E3A0 */  sb         $v1, 0x69($a3)
    /* C5E8 8001BDE8 0000AC8C */  lw         $t4, 0x0($a1)
    /* C5EC 8001BDEC 0100C624 */  addiu      $a2, $a2, 0x1
    /* C5F0 8001BDF0 20008615 */  bne        $t4, $a2, .L8001BE74
    /* C5F4 8001BDF4 00000000 */   nop
    /* C5F8 8001BDF8 2118E003 */  addu       $v1, $ra, $zero
    /* C5FC 8001BDFC 7800E88C */  lw         $t0, 0x78($a3)
    /* C600 8001BE00 0000E924 */  addiu      $t1, $a3, 0x0
    /* C604 8001BE04 1800EA24 */  addiu      $t2, $a3, 0x18
    /* C608 8001BE08 6000EB24 */  addiu      $t3, $a3, 0x60
    /* C60C 8001BE0C 4000ECE8 */  swc2       $12, 0x40($a3)
    /* C610 8001BE10 5800EDE8 */  swc2       $13, 0x58($a3)
    /* C614 8001BE14 D16F000C */  jal        func_8001BF44
    /* C618 8001BE18 00000000 */   nop
    /* C61C 8001BE1C 7C00E88C */  lw         $t0, 0x7C($a3)
    /* C620 8001BE20 3000E924 */  addiu      $t1, $a3, 0x30
    /* C624 8001BE24 0000EA24 */  addiu      $t2, $a3, 0x0
    /* C628 8001BE28 6000EB24 */  addiu      $t3, $a3, 0x60
    /* C62C 8001BE2C D16F000C */  jal        func_8001BF44
    /* C630 8001BE30 00000000 */   nop
    /* C634 8001BE34 8000E88C */  lw         $t0, 0x80($a3)
    /* C638 8001BE38 1800E924 */  addiu      $t1, $a3, 0x18
    /* C63C 8001BE3C 4800EA24 */  addiu      $t2, $a3, 0x48
    /* C640 8001BE40 6000EB24 */  addiu      $t3, $a3, 0x60
    /* C644 8001BE44 D16F000C */  jal        func_8001BF44
    /* C648 8001BE48 00000000 */   nop
    /* C64C 8001BE4C 8400E88C */  lw         $t0, 0x84($a3)
    /* C650 8001BE50 4800E924 */  addiu      $t1, $a3, 0x48
    /* C654 8001BE54 3000EA24 */  addiu      $t2, $a3, 0x30
    /* C658 8001BE58 6000EB24 */  addiu      $t3, $a3, 0x60
    /* C65C 8001BE5C D16F000C */  jal        func_8001BF44
    /* C660 8001BE60 00000000 */   nop
    /* C664 8001BE64 21F86000 */  addu       $ra, $v1, $zero
    /* C668 8001BE68 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* C66C 8001BE6C 32000010 */  b          .L8001BF38
    /* C670 8001BE70 00000000 */   nop
  .L8001BE74:
    /* C674 8001BE74 8C00E724 */  addiu      $a3, $a3, 0x8C
    /* C678 8001BE78 8800FFAC */  sw         $ra, 0x88($a3)
    /* C67C 8001BE7C ECFFEC8C */  lw         $t4, -0x14($a3)
    /* C680 8001BE80 74FFED24 */  addiu      $t5, $a3, -0x8C
    /* C684 8001BE84 8CFFEE24 */  addiu      $t6, $a3, -0x74
    /* C688 8001BE88 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* C68C 8001BE8C 7800ECAC */  sw         $t4, 0x78($a3)
    /* C690 8001BE90 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* C694 8001BE94 8000EEAC */  sw         $t6, 0x80($a3)
    /* C698 8001BE98 8400EFAC */  sw         $t7, 0x84($a3)
    /* C69C 8001BE9C B4FFECE8 */  swc2       $12, -0x4C($a3)
    /* C6A0 8001BEA0 CCFFEDE8 */  swc2       $13, -0x34($a3)
    /* C6A4 8001BEA4 B8FFF1E8 */  swc2       $17, -0x48($a3)
    /* C6A8 8001BEA8 D0FFF2E8 */  swc2       $18, -0x30($a3)
    /* C6AC 8001BEAC AF6E000C */  jal        func_8001BABC
    /* C6B0 8001BEB0 00000000 */   nop
    /* C6B4 8001BEB4 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* C6B8 8001BEB8 A4FFED24 */  addiu      $t5, $a3, -0x5C
    /* C6BC 8001BEBC 74FFEE24 */  addiu      $t6, $a3, -0x8C
    /* C6C0 8001BEC0 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* C6C4 8001BEC4 7800ECAC */  sw         $t4, 0x78($a3)
    /* C6C8 8001BEC8 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* C6CC 8001BECC 8000EEAC */  sw         $t6, 0x80($a3)
    /* C6D0 8001BED0 8400EFAC */  sw         $t7, 0x84($a3)
    /* C6D4 8001BED4 AF6E000C */  jal        func_8001BABC
    /* C6D8 8001BED8 00000000 */   nop
    /* C6DC 8001BEDC F4FFEC8C */  lw         $t4, -0xC($a3)
    /* C6E0 8001BEE0 8CFFED24 */  addiu      $t5, $a3, -0x74
    /* C6E4 8001BEE4 BCFFEE24 */  addiu      $t6, $a3, -0x44
    /* C6E8 8001BEE8 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* C6EC 8001BEEC 7800ECAC */  sw         $t4, 0x78($a3)
    /* C6F0 8001BEF0 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* C6F4 8001BEF4 8000EEAC */  sw         $t6, 0x80($a3)
    /* C6F8 8001BEF8 8400EFAC */  sw         $t7, 0x84($a3)
    /* C6FC 8001BEFC AF6E000C */  jal        func_8001BABC
    /* C700 8001BF00 00000000 */   nop
    /* C704 8001BF04 F8FFEC8C */  lw         $t4, -0x8($a3)
    /* C708 8001BF08 BCFFED24 */  addiu      $t5, $a3, -0x44
    /* C70C 8001BF0C A4FFEE24 */  addiu      $t6, $a3, -0x5C
    /* C710 8001BF10 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* C714 8001BF14 7800ECAC */  sw         $t4, 0x78($a3)
    /* C718 8001BF18 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* C71C 8001BF1C 8000EEAC */  sw         $t6, 0x80($a3)
    /* C720 8001BF20 8400EFAC */  sw         $t7, 0x84($a3)
    /* C724 8001BF24 AF6E000C */  jal        func_8001BABC
    /* C728 8001BF28 00000000 */   nop
    /* C72C 8001BF2C 8800FF8C */  lw         $ra, 0x88($a3)
    /* C730 8001BF30 74FFE724 */  addiu      $a3, $a3, -0x8C
    /* C734 8001BF34 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001BF38:
    /* C738 8001BF38 21108000 */  addu       $v0, $a0, $zero
    /* C73C 8001BF3C 0800E003 */  jr         $ra
    /* C740 8001BF40 00000000 */   nop
endlabel func_8001BABC

nonmatching func_8001BF44, 0x8C

glabel func_8001BF44
    /* C744 8001BF44 0C00AC94 */  lhu        $t4, 0xC($a1)
    /* C748 8001BF48 08000D95 */  lhu        $t5, 0x8($t0)
    /* C74C 8001BF4C 00640C00 */  sll        $t4, $t4, 16
    /* C750 8001BF50 2168AC01 */  addu       $t5, $t5, $t4
    /* C754 8001BF54 0E00AC94 */  lhu        $t4, 0xE($a1)
    /* C758 8001BF58 08002E95 */  lhu        $t6, 0x8($t1)
    /* C75C 8001BF5C 00640C00 */  sll        $t4, $t4, 16
    /* C760 8001BF60 2170CC01 */  addu       $t6, $t6, $t4
    /* C764 8001BF64 08004F95 */  lhu        $t7, 0x8($t2)
    /* C768 8001BF68 08007895 */  lhu        $t8, 0x8($t3)
    /* C76C 8001BF6C 1000AC8C */  lw         $t4, 0x10($a1)
    /* C770 8001BF70 0C008DAC */  sw         $t5, 0xC($a0)
    /* C774 8001BF74 14008EAC */  sw         $t6, 0x14($a0)
    /* C778 8001BF78 1C008FAC */  sw         $t7, 0x1C($a0)
    /* C77C 8001BF7C 240098AC */  sw         $t8, 0x24($a0)
    /* C780 8001BF80 04008CAC */  sw         $t4, 0x4($a0)
    /* C784 8001BF84 10000C8D */  lw         $t4, 0x10($t0)
    /* C788 8001BF88 10002D8D */  lw         $t5, 0x10($t1)
    /* C78C 8001BF8C 10004E8D */  lw         $t6, 0x10($t2)
    /* C790 8001BF90 10006F8D */  lw         $t7, 0x10($t3)
    /* C794 8001BF94 08008CAC */  sw         $t4, 0x8($a0)
    /* C798 8001BF98 10008DAC */  sw         $t5, 0x10($a0)
    /* C79C 8001BF9C 18008EAC */  sw         $t6, 0x18($a0)
    /* C7A0 8001BFA0 20008FAC */  sw         $t7, 0x20($a0)
    /* C7A4 8001BFA4 1400AC8C */  lw         $t4, 0x14($a1)
    /* C7A8 8001BFA8 00CA0400 */  sll        $t9, $a0, 8
    /* C7AC 8001BFAC 02CA1900 */  srl        $t9, $t9, 8
    /* C7B0 8001BFB0 0000988D */  lw         $t8, 0x0($t4)
    /* C7B4 8001BFB4 000099AD */  sw         $t9, 0x0($t4)
    /* C7B8 8001BFB8 00090E3C */  lui        $t6, (0x9000000 >> 16)
    /* C7BC 8001BFBC 25C00E03 */  or         $t8, $t8, $t6
    /* C7C0 8001BFC0 000098AC */  sw         $t8, 0x0($a0)
    /* C7C4 8001BFC4 28008424 */  addiu      $a0, $a0, 0x28
    /* C7C8 8001BFC8 0800E003 */  jr         $ra
    /* C7CC 8001BFCC 00000000 */   nop
endlabel func_8001BF44
    /* C7D0 8001BFD0 00000000 */  nop
