.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching func_8001AD54, 0x8

glabel func_8001AD54
    /* B554 8001AD54 6000A720 */  addi       $a3, $a1, 0x60 /* handwritten instruction */
    /* B558 8001AD58 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001AD54

/* Handwritten function */
nonmatching func_8001AD5C, 0x3A4

glabel func_8001AD5C
    /* B55C 8001AD5C 4800E88C */  lw         $t0, 0x48($a3)
    /* B560 8001AD60 4C00E98C */  lw         $t1, 0x4C($a3)
    /* B564 8001AD64 5000EA8C */  lw         $t2, 0x50($a3)
    /* B568 8001AD68 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* B56C 8001AD6C 14000C8D */  lw         $t4, 0x14($t0)
    /* B570 8001AD70 14002D8D */  lw         $t5, 0x14($t1)
    /* B574 8001AD74 14004E8D */  lw         $t6, 0x14($t2)
    /* B578 8001AD78 43C01900 */  sra        $t8, $t9, 1
    /* B57C 8001AD7C 2B089801 */  sltu       $at, $t4, $t8
    /* B580 8001AD80 08002010 */  beqz       $at, .L8001ADA4
    /* B584 8001AD84 2B08B801 */   sltu      $at, $t5, $t8
    /* B588 8001AD88 06002010 */  beqz       $at, .L8001ADA4
    /* B58C 8001AD8C 2B08D801 */   sltu      $at, $t6, $t8
    /* B590 8001AD90 04002010 */  beqz       $at, .L8001ADA4
    /* B594 8001AD94 00000000 */   nop
    /* B598 8001AD98 21108000 */  addu       $v0, $a0, $zero
    /* B59C 8001AD9C 0800E003 */  jr         $ra
    /* B5A0 8001ADA0 00000000 */   nop
  .L8001ADA4:
    /* B5A4 8001ADA4 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* B5A8 8001ADA8 0400A28C */  lw         $v0, 0x4($a1)
    /* B5AC 8001ADAC 0800A38C */  lw         $v1, 0x8($a1)
    /* B5B0 8001ADB0 03CC1900 */  sra        $t9, $t9, 16
    /* B5B4 8001ADB4 42100200 */  srl        $v0, $v0, 1
    /* B5B8 8001ADB8 42180300 */  srl        $v1, $v1, 1
    /* B5BC 8001ADBC 21C02203 */  addu       $t8, $t9, $v0
    /* B5C0 8001ADC0 10000C85 */  lh         $t4, 0x10($t0)
    /* B5C4 8001ADC4 10002D85 */  lh         $t5, 0x10($t1)
    /* B5C8 8001ADC8 10004E85 */  lh         $t6, 0x10($t2)
    /* B5CC 8001ADCC 2A080C03 */  slt        $at, $t8, $t4
    /* B5D0 8001ADD0 08002010 */  beqz       $at, .L8001ADF4
    /* B5D4 8001ADD4 2A080D03 */   slt       $at, $t8, $t5
    /* B5D8 8001ADD8 06002010 */  beqz       $at, .L8001ADF4
    /* B5DC 8001ADDC 2A080E03 */   slt       $at, $t8, $t6
    /* B5E0 8001ADE0 04002010 */  beqz       $at, .L8001ADF4
    /* B5E4 8001ADE4 00000000 */   nop
    /* B5E8 8001ADE8 21108000 */  addu       $v0, $a0, $zero
    /* B5EC 8001ADEC 0800E003 */  jr         $ra
    /* B5F0 8001ADF0 00000000 */   nop
  .L8001ADF4:
    /* B5F4 8001ADF4 23C02203 */  subu       $t8, $t9, $v0
    /* B5F8 8001ADF8 2A089801 */  slt        $at, $t4, $t8
    /* B5FC 8001ADFC 08002010 */  beqz       $at, .L8001AE20
    /* B600 8001AE00 2A08B801 */   slt       $at, $t5, $t8
    /* B604 8001AE04 06002010 */  beqz       $at, .L8001AE20
    /* B608 8001AE08 2A08D801 */   slt       $at, $t6, $t8
    /* B60C 8001AE0C 04002010 */  beqz       $at, .L8001AE20
    /* B610 8001AE10 00000000 */   nop
    /* B614 8001AE14 21108000 */  addu       $v0, $a0, $zero
    /* B618 8001AE18 0800E003 */  jr         $ra
    /* B61C 8001AE1C 00000000 */   nop
  .L8001AE20:
    /* B620 8001AE20 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* B624 8001AE24 12000C85 */  lh         $t4, 0x12($t0)
    /* B628 8001AE28 12002D85 */  lh         $t5, 0x12($t1)
    /* B62C 8001AE2C 12004E85 */  lh         $t6, 0x12($t2)
    /* B630 8001AE30 03CC1900 */  sra        $t9, $t9, 16
    /* B634 8001AE34 21C02303 */  addu       $t8, $t9, $v1
    /* B638 8001AE38 2A080C03 */  slt        $at, $t8, $t4
    /* B63C 8001AE3C 08002010 */  beqz       $at, .L8001AE60
    /* B640 8001AE40 2A080D03 */   slt       $at, $t8, $t5
    /* B644 8001AE44 06002010 */  beqz       $at, .L8001AE60
    /* B648 8001AE48 2A080E03 */   slt       $at, $t8, $t6
    /* B64C 8001AE4C 04002010 */  beqz       $at, .L8001AE60
    /* B650 8001AE50 00000000 */   nop
    /* B654 8001AE54 21108000 */  addu       $v0, $a0, $zero
    /* B658 8001AE58 0800E003 */  jr         $ra
    /* B65C 8001AE5C 00000000 */   nop
  .L8001AE60:
    /* B660 8001AE60 23C02303 */  subu       $t8, $t9, $v1
    /* B664 8001AE64 2A089801 */  slt        $at, $t4, $t8
    /* B668 8001AE68 08002010 */  beqz       $at, .L8001AE8C
    /* B66C 8001AE6C 2A08B801 */   slt       $at, $t5, $t8
    /* B670 8001AE70 06002010 */  beqz       $at, .L8001AE8C
    /* B674 8001AE74 2A08D801 */   slt       $at, $t6, $t8
    /* B678 8001AE78 04002010 */  beqz       $at, .L8001AE8C
    /* B67C 8001AE7C 00000000 */   nop
    /* B680 8001AE80 21108000 */  addu       $v0, $a0, $zero
    /* B684 8001AE84 0800E003 */  jr         $ra
    /* B688 8001AE88 00000000 */   nop
  .L8001AE8C:
    /* B68C 8001AE8C 00000C85 */  lh         $t4, 0x0($t0)
    /* B690 8001AE90 00002D85 */  lh         $t5, 0x0($t1)
    /* B694 8001AE94 00004E85 */  lh         $t6, 0x0($t2)
    /* B698 8001AE98 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* B69C 8001AE9C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* B6A0 8001AEA0 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* B6A4 8001AEA4 43780F00 */  sra        $t7, $t7, 1
    /* B6A8 8001AEA8 43C01800 */  sra        $t8, $t8, 1
    /* B6AC 8001AEAC 43C81900 */  sra        $t9, $t9, 1
    /* B6B0 8001AEB0 0000EFA4 */  sh         $t7, 0x0($a3)
    /* B6B4 8001AEB4 1800F8A4 */  sh         $t8, 0x18($a3)
    /* B6B8 8001AEB8 3000F9A4 */  sh         $t9, 0x30($a3)
    /* B6BC 8001AEBC 02000C85 */  lh         $t4, 0x2($t0)
    /* B6C0 8001AEC0 02002D85 */  lh         $t5, 0x2($t1)
    /* B6C4 8001AEC4 02004E85 */  lh         $t6, 0x2($t2)
    /* B6C8 8001AEC8 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* B6CC 8001AECC 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* B6D0 8001AED0 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* B6D4 8001AED4 43780F00 */  sra        $t7, $t7, 1
    /* B6D8 8001AED8 43C01800 */  sra        $t8, $t8, 1
    /* B6DC 8001AEDC 43C81900 */  sra        $t9, $t9, 1
    /* B6E0 8001AEE0 0200EFA4 */  sh         $t7, 0x2($a3)
    /* B6E4 8001AEE4 1A00F8A4 */  sh         $t8, 0x1A($a3)
    /* B6E8 8001AEE8 3200F9A4 */  sh         $t9, 0x32($a3)
    /* B6EC 8001AEEC 04000C85 */  lh         $t4, 0x4($t0)
    /* B6F0 8001AEF0 04002D85 */  lh         $t5, 0x4($t1)
    /* B6F4 8001AEF4 04004E85 */  lh         $t6, 0x4($t2)
    /* B6F8 8001AEF8 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* B6FC 8001AEFC 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* B700 8001AF00 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* B704 8001AF04 43780F00 */  sra        $t7, $t7, 1
    /* B708 8001AF08 43C01800 */  sra        $t8, $t8, 1
    /* B70C 8001AF0C 43C81900 */  sra        $t9, $t9, 1
    /* B710 8001AF10 0400EFA4 */  sh         $t7, 0x4($a3)
    /* B714 8001AF14 1C00F8A4 */  sh         $t8, 0x1C($a3)
    /* B718 8001AF18 3400F9A4 */  sh         $t9, 0x34($a3)
    /* B71C 8001AF1C 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* B720 8001AF20 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* B724 8001AF24 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* B728 8001AF28 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* B72C 8001AF2C 3000E4C8 */  lwc2       $4, 0x30($a3)
    /* B730 8001AF30 3400E5C8 */  lwc2       $5, 0x34($a3)
    /* B734 8001AF34 0C000C91 */  lbu        $t4, 0xC($t0)
    /* B738 8001AF38 0C002D91 */  lbu        $t5, 0xC($t1)
    /* B73C 8001AF3C 0C004E91 */  lbu        $t6, 0xC($t2)
    /* B740 8001AF40 3000284A */  rtpt
    /* B744 8001AF44 21788D01 */  addu       $t7, $t4, $t5
    /* B748 8001AF48 21C0AE01 */  addu       $t8, $t5, $t6
    /* B74C 8001AF4C 21C8CC01 */  addu       $t9, $t6, $t4
    /* B750 8001AF50 42780F00 */  srl        $t7, $t7, 1
    /* B754 8001AF54 42C01800 */  srl        $t8, $t8, 1
    /* B758 8001AF58 42C81900 */  srl        $t9, $t9, 1
    /* B75C 8001AF5C 0C00EFA0 */  sb         $t7, 0xC($a3)
    /* B760 8001AF60 2400F8A0 */  sb         $t8, 0x24($a3)
    /* B764 8001AF64 3C00F9A0 */  sb         $t9, 0x3C($a3)
    /* B768 8001AF68 0D000C91 */  lbu        $t4, 0xD($t0)
    /* B76C 8001AF6C 0D002D91 */  lbu        $t5, 0xD($t1)
    /* B770 8001AF70 0D004E91 */  lbu        $t6, 0xD($t2)
    /* B774 8001AF74 21788D01 */  addu       $t7, $t4, $t5
    /* B778 8001AF78 21C0AE01 */  addu       $t8, $t5, $t6
    /* B77C 8001AF7C 21C8CC01 */  addu       $t9, $t6, $t4
    /* B780 8001AF80 42780F00 */  srl        $t7, $t7, 1
    /* B784 8001AF84 42C01800 */  srl        $t8, $t8, 1
    /* B788 8001AF88 42C81900 */  srl        $t9, $t9, 1
    /* B78C 8001AF8C 0D00EFA0 */  sb         $t7, 0xD($a3)
    /* B790 8001AF90 2500F8A0 */  sb         $t8, 0x25($a3)
    /* B794 8001AF94 3D00F9A0 */  sb         $t9, 0x3D($a3)
    /* B798 8001AF98 0E000C91 */  lbu        $t4, 0xE($t0)
    /* B79C 8001AF9C 0E002D91 */  lbu        $t5, 0xE($t1)
    /* B7A0 8001AFA0 0E004E91 */  lbu        $t6, 0xE($t2)
    /* B7A4 8001AFA4 21788D01 */  addu       $t7, $t4, $t5
    /* B7A8 8001AFA8 21C0AE01 */  addu       $t8, $t5, $t6
    /* B7AC 8001AFAC 21C8CC01 */  addu       $t9, $t6, $t4
    /* B7B0 8001AFB0 42780F00 */  srl        $t7, $t7, 1
    /* B7B4 8001AFB4 42C01800 */  srl        $t8, $t8, 1
    /* B7B8 8001AFB8 42C81900 */  srl        $t9, $t9, 1
    /* B7BC 8001AFBC 0E00EFA0 */  sb         $t7, 0xE($a3)
    /* B7C0 8001AFC0 2600F8A0 */  sb         $t8, 0x26($a3)
    /* B7C4 8001AFC4 3E00F9A0 */  sb         $t9, 0x3E($a3)
    /* B7C8 8001AFC8 0000AC8C */  lw         $t4, 0x0($a1)
    /* B7CC 8001AFCC 0100C624 */  addiu      $a2, $a2, 0x1
    /* B7D0 8001AFD0 1D008615 */  bne        $t4, $a2, .L8001B048
    /* B7D4 8001AFD4 00000000 */   nop
    /* B7D8 8001AFD8 1000ECE8 */  swc2       $12, 0x10($a3)
    /* B7DC 8001AFDC 2800EDE8 */  swc2       $13, 0x28($a3)
    /* B7E0 8001AFE0 4000EEE8 */  swc2       $14, 0x40($a3)
    /* B7E4 8001AFE4 2118E003 */  addu       $v1, $ra, $zero
    /* B7E8 8001AFE8 4C00E88C */  lw         $t0, 0x4C($a3)
    /* B7EC 8001AFEC 1800E924 */  addiu      $t1, $a3, 0x18
    /* B7F0 8001AFF0 0000EA24 */  addiu      $t2, $a3, 0x0
    /* B7F4 8001AFF4 406C000C */  jal        func_8001B100
    /* B7F8 8001AFF8 00000000 */   nop
    /* B7FC 8001AFFC 0000E824 */  addiu      $t0, $a3, 0x0
    /* B800 8001B000 1800E924 */  addiu      $t1, $a3, 0x18
    /* B804 8001B004 3000EA24 */  addiu      $t2, $a3, 0x30
    /* B808 8001B008 406C000C */  jal        func_8001B100
    /* B80C 8001B00C 00000000 */   nop
    /* B810 8001B010 4800E88C */  lw         $t0, 0x48($a3)
    /* B814 8001B014 0000E924 */  addiu      $t1, $a3, 0x0
    /* B818 8001B018 3000EA24 */  addiu      $t2, $a3, 0x30
    /* B81C 8001B01C 406C000C */  jal        func_8001B100
    /* B820 8001B020 00000000 */   nop
    /* B824 8001B024 5000E88C */  lw         $t0, 0x50($a3)
    /* B828 8001B028 3000E924 */  addiu      $t1, $a3, 0x30
    /* B82C 8001B02C 1800EA24 */  addiu      $t2, $a3, 0x18
    /* B830 8001B030 406C000C */  jal        func_8001B100
    /* B834 8001B034 00000000 */   nop
    /* B838 8001B038 21F86000 */  addu       $ra, $v1, $zero
    /* B83C 8001B03C FFFFC624 */  addiu      $a2, $a2, -0x1
    /* B840 8001B040 2C000010 */  b          .L8001B0F4
    /* B844 8001B044 00000000 */   nop
  .L8001B048:
    /* B848 8001B048 1400F1E8 */  swc2       $17, 0x14($a3)
    /* B84C 8001B04C 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* B850 8001B050 4400F3E8 */  swc2       $19, 0x44($a3)
    /* B854 8001B054 1000ECE8 */  swc2       $12, 0x10($a3)
    /* B858 8001B058 2800EDE8 */  swc2       $13, 0x28($a3)
    /* B85C 8001B05C 4000EEE8 */  swc2       $14, 0x40($a3)
    /* B860 8001B060 5800E724 */  addiu      $a3, $a3, 0x58
    /* B864 8001B064 5400FFAC */  sw         $ra, 0x54($a3)
    /* B868 8001B068 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* B86C 8001B06C A8FFED24 */  addiu      $t5, $a3, -0x58
    /* B870 8001B070 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* B874 8001B074 4800ECAC */  sw         $t4, 0x48($a3)
    /* B878 8001B078 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B87C 8001B07C 5000EEAC */  sw         $t6, 0x50($a3)
    /* B880 8001B080 576B000C */  jal        func_8001AD5C
    /* B884 8001B084 00000000 */   nop
    /* B888 8001B088 F4FFEC8C */  lw         $t4, -0xC($a3)
    /* B88C 8001B08C C0FFED24 */  addiu      $t5, $a3, -0x40
    /* B890 8001B090 A8FFEE24 */  addiu      $t6, $a3, -0x58
    /* B894 8001B094 4800ECAC */  sw         $t4, 0x48($a3)
    /* B898 8001B098 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B89C 8001B09C 5000EEAC */  sw         $t6, 0x50($a3)
    /* B8A0 8001B0A0 576B000C */  jal        func_8001AD5C
    /* B8A4 8001B0A4 00000000 */   nop
    /* B8A8 8001B0A8 F8FFEC8C */  lw         $t4, -0x8($a3)
    /* B8AC 8001B0AC D8FFED24 */  addiu      $t5, $a3, -0x28
    /* B8B0 8001B0B0 C0FFEE24 */  addiu      $t6, $a3, -0x40
    /* B8B4 8001B0B4 4800ECAC */  sw         $t4, 0x48($a3)
    /* B8B8 8001B0B8 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B8BC 8001B0BC 5000EEAC */  sw         $t6, 0x50($a3)
    /* B8C0 8001B0C0 576B000C */  jal        func_8001AD5C
    /* B8C4 8001B0C4 00000000 */   nop
    /* B8C8 8001B0C8 A8FFEC24 */  addiu      $t4, $a3, -0x58
    /* B8CC 8001B0CC C0FFED24 */  addiu      $t5, $a3, -0x40
    /* B8D0 8001B0D0 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* B8D4 8001B0D4 4800ECAC */  sw         $t4, 0x48($a3)
    /* B8D8 8001B0D8 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* B8DC 8001B0DC 5000EEAC */  sw         $t6, 0x50($a3)
    /* B8E0 8001B0E0 576B000C */  jal        func_8001AD5C
    /* B8E4 8001B0E4 00000000 */   nop
    /* B8E8 8001B0E8 5400FF8C */  lw         $ra, 0x54($a3)
    /* B8EC 8001B0EC A8FFE724 */  addiu      $a3, $a3, -0x58
    /* B8F0 8001B0F0 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001B0F4:
    /* B8F4 8001B0F4 21108000 */  addu       $v0, $a0, $zero
    /* B8F8 8001B0F8 0800E003 */  jr         $ra
    /* B8FC 8001B0FC 00000000 */   nop
endlabel func_8001AD5C

nonmatching func_8001B100, 0x64

glabel func_8001B100
    /* B900 8001B100 1300B880 */  lb         $t8, 0x13($a1)
    /* B904 8001B104 10000C8D */  lw         $t4, 0x10($t0)
    /* B908 8001B108 0F0018A1 */  sb         $t8, 0xF($t0)
    /* B90C 8001B10C 10002D8D */  lw         $t5, 0x10($t1)
    /* B910 8001B110 10004E8D */  lw         $t6, 0x10($t2)
    /* B914 8001B114 08008CAC */  sw         $t4, 0x8($a0)
    /* B918 8001B118 10008DAC */  sw         $t5, 0x10($a0)
    /* B91C 8001B11C 18008EAC */  sw         $t6, 0x18($a0)
    /* B920 8001B120 1400AC8C */  lw         $t4, 0x14($a1)
    /* B924 8001B124 006A0400 */  sll        $t5, $a0, 8
    /* B928 8001B128 026A0D00 */  srl        $t5, $t5, 8
    /* B92C 8001B12C 00008F8D */  lw         $t7, 0x0($t4)
    /* B930 8001B130 00008DAD */  sw         $t5, 0x0($t4)
    /* B934 8001B134 00060E3C */  lui        $t6, (0x6000000 >> 16)
    /* B938 8001B138 2578EE01 */  or         $t7, $t7, $t6
    /* B93C 8001B13C 0C000C8D */  lw         $t4, 0xC($t0)
    /* B940 8001B140 0C002D8D */  lw         $t5, 0xC($t1)
    /* B944 8001B144 0C004E8D */  lw         $t6, 0xC($t2)
    /* B948 8001B148 04008CAC */  sw         $t4, 0x4($a0)
    /* B94C 8001B14C 0C008DAC */  sw         $t5, 0xC($a0)
    /* B950 8001B150 14008EAC */  sw         $t6, 0x14($a0)
    /* B954 8001B154 00008FAC */  sw         $t7, 0x0($a0)
    /* B958 8001B158 1C008424 */  addiu      $a0, $a0, 0x1C
    /* B95C 8001B15C 0800E003 */  jr         $ra
    /* B960 8001B160 00000000 */   nop
endlabel func_8001B100

/* Handwritten function */
nonmatching func_8001B164, 0x8

glabel func_8001B164
    /* B964 8001B164 7800A720 */  addi       $a3, $a1, 0x78 /* handwritten instruction */
    /* B968 8001B168 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001B164

/* Handwritten function */
nonmatching func_8001B16C, 0x4D4

glabel func_8001B16C
    /* B96C 8001B16C 7800E88C */  lw         $t0, 0x78($a3)
    /* B970 8001B170 7C00E98C */  lw         $t1, 0x7C($a3)
    /* B974 8001B174 8000EA8C */  lw         $t2, 0x80($a3)
    /* B978 8001B178 8400EB8C */  lw         $t3, 0x84($a3)
    /* B97C 8001B17C 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* B980 8001B180 14000C8D */  lw         $t4, 0x14($t0)
    /* B984 8001B184 14002D8D */  lw         $t5, 0x14($t1)
    /* B988 8001B188 14004E8D */  lw         $t6, 0x14($t2)
    /* B98C 8001B18C 14006F8D */  lw         $t7, 0x14($t3)
    /* B990 8001B190 43C01900 */  sra        $t8, $t9, 1
    /* B994 8001B194 2B089801 */  sltu       $at, $t4, $t8
    /* B998 8001B198 0A002010 */  beqz       $at, .L8001B1C4
    /* B99C 8001B19C 2B08B801 */   sltu      $at, $t5, $t8
    /* B9A0 8001B1A0 08002010 */  beqz       $at, .L8001B1C4
    /* B9A4 8001B1A4 2B08D801 */   sltu      $at, $t6, $t8
    /* B9A8 8001B1A8 06002010 */  beqz       $at, .L8001B1C4
    /* B9AC 8001B1AC 2B08F801 */   sltu      $at, $t7, $t8
    /* B9B0 8001B1B0 04002010 */  beqz       $at, .L8001B1C4
    /* B9B4 8001B1B4 00000000 */   nop
    /* B9B8 8001B1B8 21108000 */  addu       $v0, $a0, $zero
    /* B9BC 8001B1BC 0800E003 */  jr         $ra
    /* B9C0 8001B1C0 00000000 */   nop
  .L8001B1C4:
    /* B9C4 8001B1C4 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* B9C8 8001B1C8 0400A28C */  lw         $v0, 0x4($a1)
    /* B9CC 8001B1CC 0800A38C */  lw         $v1, 0x8($a1)
    /* B9D0 8001B1D0 03CC1900 */  sra        $t9, $t9, 16
    /* B9D4 8001B1D4 42100200 */  srl        $v0, $v0, 1
    /* B9D8 8001B1D8 42180300 */  srl        $v1, $v1, 1
    /* B9DC 8001B1DC 21C02203 */  addu       $t8, $t9, $v0
    /* B9E0 8001B1E0 10000C85 */  lh         $t4, 0x10($t0)
    /* B9E4 8001B1E4 10002D85 */  lh         $t5, 0x10($t1)
    /* B9E8 8001B1E8 10004E85 */  lh         $t6, 0x10($t2)
    /* B9EC 8001B1EC 10006F85 */  lh         $t7, 0x10($t3)
    /* B9F0 8001B1F0 2A080C03 */  slt        $at, $t8, $t4
    /* B9F4 8001B1F4 0A002010 */  beqz       $at, .L8001B220
    /* B9F8 8001B1F8 2A080D03 */   slt       $at, $t8, $t5
    /* B9FC 8001B1FC 08002010 */  beqz       $at, .L8001B220
    /* BA00 8001B200 2A080E03 */   slt       $at, $t8, $t6
    /* BA04 8001B204 06002010 */  beqz       $at, .L8001B220
    /* BA08 8001B208 2A080F03 */   slt       $at, $t8, $t7
    /* BA0C 8001B20C 04002010 */  beqz       $at, .L8001B220
    /* BA10 8001B210 00000000 */   nop
    /* BA14 8001B214 21108000 */  addu       $v0, $a0, $zero
    /* BA18 8001B218 0800E003 */  jr         $ra
    /* BA1C 8001B21C 00000000 */   nop
  .L8001B220:
    /* BA20 8001B220 23C02203 */  subu       $t8, $t9, $v0
    /* BA24 8001B224 2A089801 */  slt        $at, $t4, $t8
    /* BA28 8001B228 0A002010 */  beqz       $at, .L8001B254
    /* BA2C 8001B22C 2A08B801 */   slt       $at, $t5, $t8
    /* BA30 8001B230 08002010 */  beqz       $at, .L8001B254
    /* BA34 8001B234 2A08D801 */   slt       $at, $t6, $t8
    /* BA38 8001B238 06002010 */  beqz       $at, .L8001B254
    /* BA3C 8001B23C 2A08F801 */   slt       $at, $t7, $t8
    /* BA40 8001B240 04002010 */  beqz       $at, .L8001B254
    /* BA44 8001B244 00000000 */   nop
    /* BA48 8001B248 21108000 */  addu       $v0, $a0, $zero
    /* BA4C 8001B24C 0800E003 */  jr         $ra
    /* BA50 8001B250 00000000 */   nop
  .L8001B254:
    /* BA54 8001B254 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* BA58 8001B258 12000C85 */  lh         $t4, 0x12($t0)
    /* BA5C 8001B25C 12002D85 */  lh         $t5, 0x12($t1)
    /* BA60 8001B260 12004E85 */  lh         $t6, 0x12($t2)
    /* BA64 8001B264 12006F85 */  lh         $t7, 0x12($t3)
    /* BA68 8001B268 03CC1900 */  sra        $t9, $t9, 16
    /* BA6C 8001B26C 21C02303 */  addu       $t8, $t9, $v1
    /* BA70 8001B270 2A080C03 */  slt        $at, $t8, $t4
    /* BA74 8001B274 0A002010 */  beqz       $at, .L8001B2A0
    /* BA78 8001B278 2A080D03 */   slt       $at, $t8, $t5
    /* BA7C 8001B27C 08002010 */  beqz       $at, .L8001B2A0
    /* BA80 8001B280 2A080E03 */   slt       $at, $t8, $t6
    /* BA84 8001B284 06002010 */  beqz       $at, .L8001B2A0
    /* BA88 8001B288 2A080F03 */   slt       $at, $t8, $t7
    /* BA8C 8001B28C 04002010 */  beqz       $at, .L8001B2A0
    /* BA90 8001B290 00000000 */   nop
    /* BA94 8001B294 21108000 */  addu       $v0, $a0, $zero
    /* BA98 8001B298 0800E003 */  jr         $ra
    /* BA9C 8001B29C 00000000 */   nop
  .L8001B2A0:
    /* BAA0 8001B2A0 23C02303 */  subu       $t8, $t9, $v1
    /* BAA4 8001B2A4 2A089801 */  slt        $at, $t4, $t8
    /* BAA8 8001B2A8 0A002010 */  beqz       $at, .L8001B2D4
    /* BAAC 8001B2AC 2A08B801 */   slt       $at, $t5, $t8
    /* BAB0 8001B2B0 08002010 */  beqz       $at, .L8001B2D4
    /* BAB4 8001B2B4 2A08D801 */   slt       $at, $t6, $t8
    /* BAB8 8001B2B8 06002010 */  beqz       $at, .L8001B2D4
    /* BABC 8001B2BC 2A08F801 */   slt       $at, $t7, $t8
    /* BAC0 8001B2C0 04002010 */  beqz       $at, .L8001B2D4
    /* BAC4 8001B2C4 00000000 */   nop
    /* BAC8 8001B2C8 21108000 */  addu       $v0, $a0, $zero
    /* BACC 8001B2CC 0800E003 */  jr         $ra
    /* BAD0 8001B2D0 00000000 */   nop
  .L8001B2D4:
    /* BAD4 8001B2D4 00000C85 */  lh         $t4, 0x0($t0)
    /* BAD8 8001B2D8 00002D85 */  lh         $t5, 0x0($t1)
    /* BADC 8001B2DC 00004E85 */  lh         $t6, 0x0($t2)
    /* BAE0 8001B2E0 00006F85 */  lh         $t7, 0x0($t3)
    /* BAE4 8001B2E4 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* BAE8 8001B2E8 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* BAEC 8001B2EC 43C01800 */  sra        $t8, $t8, 1
    /* BAF0 8001B2F0 43C81900 */  sra        $t9, $t9, 1
    /* BAF4 8001B2F4 3000F8A4 */  sh         $t8, 0x30($a3)
    /* BAF8 8001B2F8 1800F9A4 */  sh         $t9, 0x18($a3)
    /* BAFC 8001B2FC 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* BB00 8001B300 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* BB04 8001B304 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* BB08 8001B308 43C01800 */  sra        $t8, $t8, 1
    /* BB0C 8001B30C 43C81900 */  sra        $t9, $t9, 1
    /* BB10 8001B310 83180300 */  sra        $v1, $v1, 2
    /* BB14 8001B314 0000F8A4 */  sh         $t8, 0x0($a3)
    /* BB18 8001B318 4800F9A4 */  sh         $t9, 0x48($a3)
    /* BB1C 8001B31C 6000E3A4 */  sh         $v1, 0x60($a3)
    /* BB20 8001B320 02000C85 */  lh         $t4, 0x2($t0)
    /* BB24 8001B324 02002D85 */  lh         $t5, 0x2($t1)
    /* BB28 8001B328 02004E85 */  lh         $t6, 0x2($t2)
    /* BB2C 8001B32C 02006F85 */  lh         $t7, 0x2($t3)
    /* BB30 8001B330 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* BB34 8001B334 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* BB38 8001B338 43C01800 */  sra        $t8, $t8, 1
    /* BB3C 8001B33C 43C81900 */  sra        $t9, $t9, 1
    /* BB40 8001B340 3200F8A4 */  sh         $t8, 0x32($a3)
    /* BB44 8001B344 1A00F9A4 */  sh         $t9, 0x1A($a3)
    /* BB48 8001B348 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* BB4C 8001B34C 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* BB50 8001B350 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* BB54 8001B354 43C01800 */  sra        $t8, $t8, 1
    /* BB58 8001B358 43C81900 */  sra        $t9, $t9, 1
    /* BB5C 8001B35C 83180300 */  sra        $v1, $v1, 2
    /* BB60 8001B360 0200F8A4 */  sh         $t8, 0x2($a3)
    /* BB64 8001B364 4A00F9A4 */  sh         $t9, 0x4A($a3)
    /* BB68 8001B368 6200E3A4 */  sh         $v1, 0x62($a3)
    /* BB6C 8001B36C 04000C85 */  lh         $t4, 0x4($t0)
    /* BB70 8001B370 04002D85 */  lh         $t5, 0x4($t1)
    /* BB74 8001B374 04004E85 */  lh         $t6, 0x4($t2)
    /* BB78 8001B378 04006F85 */  lh         $t7, 0x4($t3)
    /* BB7C 8001B37C 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* BB80 8001B380 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* BB84 8001B384 43C01800 */  sra        $t8, $t8, 1
    /* BB88 8001B388 43C81900 */  sra        $t9, $t9, 1
    /* BB8C 8001B38C 3400F8A4 */  sh         $t8, 0x34($a3)
    /* BB90 8001B390 1C00F9A4 */  sh         $t9, 0x1C($a3)
    /* BB94 8001B394 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* BB98 8001B398 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* BB9C 8001B39C 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* BBA0 8001B3A0 43C01800 */  sra        $t8, $t8, 1
    /* BBA4 8001B3A4 43C81900 */  sra        $t9, $t9, 1
    /* BBA8 8001B3A8 83180300 */  sra        $v1, $v1, 2
    /* BBAC 8001B3AC 0400F8A4 */  sh         $t8, 0x4($a3)
    /* BBB0 8001B3B0 4C00F9A4 */  sh         $t9, 0x4C($a3)
    /* BBB4 8001B3B4 6400E3A4 */  sh         $v1, 0x64($a3)
    /* BBB8 8001B3B8 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* BBBC 8001B3BC 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* BBC0 8001B3C0 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* BBC4 8001B3C4 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* BBC8 8001B3C8 6000E4C8 */  lwc2       $4, 0x60($a3)
    /* BBCC 8001B3CC 6400E5C8 */  lwc2       $5, 0x64($a3)
    /* BBD0 8001B3D0 0C000C91 */  lbu        $t4, 0xC($t0)
    /* BBD4 8001B3D4 3000284A */  rtpt
    /* BBD8 8001B3D8 0C002D91 */  lbu        $t5, 0xC($t1)
    /* BBDC 8001B3DC 0C004E91 */  lbu        $t6, 0xC($t2)
    /* BBE0 8001B3E0 0C006F91 */  lbu        $t7, 0xC($t3)
    /* BBE4 8001B3E4 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* BBE8 8001B3E8 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* BBEC 8001B3EC 43C01800 */  sra        $t8, $t8, 1
    /* BBF0 8001B3F0 43C81900 */  sra        $t9, $t9, 1
    /* BBF4 8001B3F4 3C00F8A0 */  sb         $t8, 0x3C($a3)
    /* BBF8 8001B3F8 2400F9A0 */  sb         $t9, 0x24($a3)
    /* BBFC 8001B3FC 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* BC00 8001B400 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* BC04 8001B404 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* BC08 8001B408 43C01800 */  sra        $t8, $t8, 1
    /* BC0C 8001B40C 43C81900 */  sra        $t9, $t9, 1
    /* BC10 8001B410 83180300 */  sra        $v1, $v1, 2
    /* BC14 8001B414 0C00F8A0 */  sb         $t8, 0xC($a3)
    /* BC18 8001B418 5400F9A0 */  sb         $t9, 0x54($a3)
    /* BC1C 8001B41C 6C00E3A0 */  sb         $v1, 0x6C($a3)
    /* BC20 8001B420 0D000C91 */  lbu        $t4, 0xD($t0)
    /* BC24 8001B424 0D002D91 */  lbu        $t5, 0xD($t1)
    /* BC28 8001B428 0D004E91 */  lbu        $t6, 0xD($t2)
    /* BC2C 8001B42C 0D006F91 */  lbu        $t7, 0xD($t3)
    /* BC30 8001B430 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* BC34 8001B434 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* BC38 8001B438 43C01800 */  sra        $t8, $t8, 1
    /* BC3C 8001B43C 43C81900 */  sra        $t9, $t9, 1
    /* BC40 8001B440 3D00F8A0 */  sb         $t8, 0x3D($a3)
    /* BC44 8001B444 2500F9A0 */  sb         $t9, 0x25($a3)
    /* BC48 8001B448 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* BC4C 8001B44C 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* BC50 8001B450 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* BC54 8001B454 43C01800 */  sra        $t8, $t8, 1
    /* BC58 8001B458 43C81900 */  sra        $t9, $t9, 1
    /* BC5C 8001B45C 83180300 */  sra        $v1, $v1, 2
    /* BC60 8001B460 0D00F8A0 */  sb         $t8, 0xD($a3)
    /* BC64 8001B464 5500F9A0 */  sb         $t9, 0x55($a3)
    /* BC68 8001B468 6D00E3A0 */  sb         $v1, 0x6D($a3)
    /* BC6C 8001B46C 1000ECE8 */  swc2       $12, 0x10($a3)
    /* BC70 8001B470 2800EDE8 */  swc2       $13, 0x28($a3)
    /* BC74 8001B474 7000EEE8 */  swc2       $14, 0x70($a3)
    /* BC78 8001B478 1400F1E8 */  swc2       $17, 0x14($a3)
    /* BC7C 8001B47C 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* BC80 8001B480 7400F3E8 */  swc2       $19, 0x74($a3)
    /* BC84 8001B484 3000E0C8 */  lwc2       $0, 0x30($a3)
    /* BC88 8001B488 3400E1C8 */  lwc2       $1, 0x34($a3)
    /* BC8C 8001B48C 4800E2C8 */  lwc2       $2, 0x48($a3)
    /* BC90 8001B490 4C00E3C8 */  lwc2       $3, 0x4C($a3)
    /* BC94 8001B494 0E000C91 */  lbu        $t4, 0xE($t0)
    /* BC98 8001B498 3000284A */  rtpt
    /* BC9C 8001B49C 0E002D91 */  lbu        $t5, 0xE($t1)
    /* BCA0 8001B4A0 0E004E91 */  lbu        $t6, 0xE($t2)
    /* BCA4 8001B4A4 0E006F91 */  lbu        $t7, 0xE($t3)
    /* BCA8 8001B4A8 20C88E01 */  add        $t9, $t4, $t6 /* handwritten instruction */
    /* BCAC 8001B4AC 20C0ED01 */  add        $t8, $t7, $t5 /* handwritten instruction */
    /* BCB0 8001B4B0 43C01800 */  sra        $t8, $t8, 1
    /* BCB4 8001B4B4 43C81900 */  sra        $t9, $t9, 1
    /* BCB8 8001B4B8 3E00F8A0 */  sb         $t8, 0x3E($a3)
    /* BCBC 8001B4BC 2600F9A0 */  sb         $t9, 0x26($a3)
    /* BCC0 8001B4C0 20C08D01 */  add        $t8, $t4, $t5 /* handwritten instruction */
    /* BCC4 8001B4C4 20C8EE01 */  add        $t9, $t7, $t6 /* handwritten instruction */
    /* BCC8 8001B4C8 20181903 */  add        $v1, $t8, $t9 /* handwritten instruction */
    /* BCCC 8001B4CC 43C01800 */  sra        $t8, $t8, 1
    /* BCD0 8001B4D0 43C81900 */  sra        $t9, $t9, 1
    /* BCD4 8001B4D4 83180300 */  sra        $v1, $v1, 2
    /* BCD8 8001B4D8 0E00F8A0 */  sb         $t8, 0xE($a3)
    /* BCDC 8001B4DC 5600F9A0 */  sb         $t9, 0x56($a3)
    /* BCE0 8001B4E0 6E00E3A0 */  sb         $v1, 0x6E($a3)
    /* BCE4 8001B4E4 0000AC8C */  lw         $t4, 0x0($a1)
    /* BCE8 8001B4E8 0100C624 */  addiu      $a2, $a2, 0x1
    /* BCEC 8001B4EC 20008615 */  bne        $t4, $a2, .L8001B570
    /* BCF0 8001B4F0 00000000 */   nop
    /* BCF4 8001B4F4 2118E003 */  addu       $v1, $ra, $zero
    /* BCF8 8001B4F8 7800E88C */  lw         $t0, 0x78($a3)
    /* BCFC 8001B4FC 0000E924 */  addiu      $t1, $a3, 0x0
    /* BD00 8001B500 1800EA24 */  addiu      $t2, $a3, 0x18
    /* BD04 8001B504 6000EB24 */  addiu      $t3, $a3, 0x60
    /* BD08 8001B508 4000ECE8 */  swc2       $12, 0x40($a3)
    /* BD0C 8001B50C 5800EDE8 */  swc2       $13, 0x58($a3)
    /* BD10 8001B510 906D000C */  jal        func_8001B640
    /* BD14 8001B514 00000000 */   nop
    /* BD18 8001B518 7C00E88C */  lw         $t0, 0x7C($a3)
    /* BD1C 8001B51C 3000E924 */  addiu      $t1, $a3, 0x30
    /* BD20 8001B520 0000EA24 */  addiu      $t2, $a3, 0x0
    /* BD24 8001B524 6000EB24 */  addiu      $t3, $a3, 0x60
    /* BD28 8001B528 906D000C */  jal        func_8001B640
    /* BD2C 8001B52C 00000000 */   nop
    /* BD30 8001B530 8000E88C */  lw         $t0, 0x80($a3)
    /* BD34 8001B534 1800E924 */  addiu      $t1, $a3, 0x18
    /* BD38 8001B538 4800EA24 */  addiu      $t2, $a3, 0x48
    /* BD3C 8001B53C 6000EB24 */  addiu      $t3, $a3, 0x60
    /* BD40 8001B540 906D000C */  jal        func_8001B640
    /* BD44 8001B544 00000000 */   nop
    /* BD48 8001B548 8400E88C */  lw         $t0, 0x84($a3)
    /* BD4C 8001B54C 4800E924 */  addiu      $t1, $a3, 0x48
    /* BD50 8001B550 3000EA24 */  addiu      $t2, $a3, 0x30
    /* BD54 8001B554 6000EB24 */  addiu      $t3, $a3, 0x60
    /* BD58 8001B558 906D000C */  jal        func_8001B640
    /* BD5C 8001B55C 00000000 */   nop
    /* BD60 8001B560 21F86000 */  addu       $ra, $v1, $zero
    /* BD64 8001B564 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* BD68 8001B568 32000010 */  b          .L8001B634
    /* BD6C 8001B56C 00000000 */   nop
  .L8001B570:
    /* BD70 8001B570 8C00E724 */  addiu      $a3, $a3, 0x8C
    /* BD74 8001B574 8800FFAC */  sw         $ra, 0x88($a3)
    /* BD78 8001B578 ECFFEC8C */  lw         $t4, -0x14($a3)
    /* BD7C 8001B57C 74FFED24 */  addiu      $t5, $a3, -0x8C
    /* BD80 8001B580 8CFFEE24 */  addiu      $t6, $a3, -0x74
    /* BD84 8001B584 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* BD88 8001B588 7800ECAC */  sw         $t4, 0x78($a3)
    /* BD8C 8001B58C 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* BD90 8001B590 8000EEAC */  sw         $t6, 0x80($a3)
    /* BD94 8001B594 8400EFAC */  sw         $t7, 0x84($a3)
    /* BD98 8001B598 B4FFECE8 */  swc2       $12, -0x4C($a3)
    /* BD9C 8001B59C CCFFEDE8 */  swc2       $13, -0x34($a3)
    /* BDA0 8001B5A0 B8FFF1E8 */  swc2       $17, -0x48($a3)
    /* BDA4 8001B5A4 D0FFF2E8 */  swc2       $18, -0x30($a3)
    /* BDA8 8001B5A8 5B6C000C */  jal        func_8001B16C
    /* BDAC 8001B5AC 00000000 */   nop
    /* BDB0 8001B5B0 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* BDB4 8001B5B4 A4FFED24 */  addiu      $t5, $a3, -0x5C
    /* BDB8 8001B5B8 74FFEE24 */  addiu      $t6, $a3, -0x8C
    /* BDBC 8001B5BC D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* BDC0 8001B5C0 7800ECAC */  sw         $t4, 0x78($a3)
    /* BDC4 8001B5C4 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* BDC8 8001B5C8 8000EEAC */  sw         $t6, 0x80($a3)
    /* BDCC 8001B5CC 8400EFAC */  sw         $t7, 0x84($a3)
    /* BDD0 8001B5D0 5B6C000C */  jal        func_8001B16C
    /* BDD4 8001B5D4 00000000 */   nop
    /* BDD8 8001B5D8 F4FFEC8C */  lw         $t4, -0xC($a3)
    /* BDDC 8001B5DC 8CFFED24 */  addiu      $t5, $a3, -0x74
    /* BDE0 8001B5E0 BCFFEE24 */  addiu      $t6, $a3, -0x44
    /* BDE4 8001B5E4 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* BDE8 8001B5E8 7800ECAC */  sw         $t4, 0x78($a3)
    /* BDEC 8001B5EC 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* BDF0 8001B5F0 8000EEAC */  sw         $t6, 0x80($a3)
    /* BDF4 8001B5F4 8400EFAC */  sw         $t7, 0x84($a3)
    /* BDF8 8001B5F8 5B6C000C */  jal        func_8001B16C
    /* BDFC 8001B5FC 00000000 */   nop
    /* BE00 8001B600 F8FFEC8C */  lw         $t4, -0x8($a3)
    /* BE04 8001B604 BCFFED24 */  addiu      $t5, $a3, -0x44
    /* BE08 8001B608 A4FFEE24 */  addiu      $t6, $a3, -0x5C
    /* BE0C 8001B60C D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* BE10 8001B610 7800ECAC */  sw         $t4, 0x78($a3)
    /* BE14 8001B614 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* BE18 8001B618 8000EEAC */  sw         $t6, 0x80($a3)
    /* BE1C 8001B61C 8400EFAC */  sw         $t7, 0x84($a3)
    /* BE20 8001B620 5B6C000C */  jal        func_8001B16C
    /* BE24 8001B624 00000000 */   nop
    /* BE28 8001B628 8800FF8C */  lw         $ra, 0x88($a3)
    /* BE2C 8001B62C 74FFE724 */  addiu      $a3, $a3, -0x8C
    /* BE30 8001B630 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001B634:
    /* BE34 8001B634 21108000 */  addu       $v0, $a0, $zero
    /* BE38 8001B638 0800E003 */  jr         $ra
    /* BE3C 8001B63C 00000000 */   nop
endlabel func_8001B16C

nonmatching func_8001B640, 0x74

glabel func_8001B640
    /* BE40 8001B640 1300B880 */  lb         $t8, 0x13($a1)
    /* BE44 8001B644 10000C8D */  lw         $t4, 0x10($t0)
    /* BE48 8001B648 10002D8D */  lw         $t5, 0x10($t1)
    /* BE4C 8001B64C 10004E8D */  lw         $t6, 0x10($t2)
    /* BE50 8001B650 10006F8D */  lw         $t7, 0x10($t3)
    /* BE54 8001B654 0F0018A1 */  sb         $t8, 0xF($t0)
    /* BE58 8001B658 08008CAC */  sw         $t4, 0x8($a0)
    /* BE5C 8001B65C 10008DAC */  sw         $t5, 0x10($a0)
    /* BE60 8001B660 18008EAC */  sw         $t6, 0x18($a0)
    /* BE64 8001B664 20008FAC */  sw         $t7, 0x20($a0)
    /* BE68 8001B668 1400AC8C */  lw         $t4, 0x14($a1)
    /* BE6C 8001B66C 00CA0400 */  sll        $t9, $a0, 8
    /* BE70 8001B670 02CA1900 */  srl        $t9, $t9, 8
    /* BE74 8001B674 0000988D */  lw         $t8, 0x0($t4)
    /* BE78 8001B678 000099AD */  sw         $t9, 0x0($t4)
    /* BE7C 8001B67C 00080E3C */  lui        $t6, (0x8000000 >> 16)
    /* BE80 8001B680 25C00E03 */  or         $t8, $t8, $t6
    /* BE84 8001B684 0C000C8D */  lw         $t4, 0xC($t0)
    /* BE88 8001B688 0C002D8D */  lw         $t5, 0xC($t1)
    /* BE8C 8001B68C 0C004E8D */  lw         $t6, 0xC($t2)
    /* BE90 8001B690 0C006F8D */  lw         $t7, 0xC($t3)
    /* BE94 8001B694 04008CAC */  sw         $t4, 0x4($a0)
    /* BE98 8001B698 0C008DAC */  sw         $t5, 0xC($a0)
    /* BE9C 8001B69C 14008EAC */  sw         $t6, 0x14($a0)
    /* BEA0 8001B6A0 1C008FAC */  sw         $t7, 0x1C($a0)
    /* BEA4 8001B6A4 000098AC */  sw         $t8, 0x0($a0)
    /* BEA8 8001B6A8 24008424 */  addiu      $a0, $a0, 0x24
    /* BEAC 8001B6AC 0800E003 */  jr         $ra
    /* BEB0 8001B6B0 00000000 */   nop
endlabel func_8001B640

/* Handwritten function */
nonmatching func_8001B6B4, 0x8

glabel func_8001B6B4
    /* BEB4 8001B6B4 6000A720 */  addi       $a3, $a1, 0x60 /* handwritten instruction */
    /* BEB8 8001B6B8 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001B6B4

/* Handwritten function */
nonmatching func_8001B6BC, 0x374

glabel func_8001B6BC
    /* BEBC 8001B6BC 4800E88C */  lw         $t0, 0x48($a3)
    /* BEC0 8001B6C0 4C00E98C */  lw         $t1, 0x4C($a3)
    /* BEC4 8001B6C4 5000EA8C */  lw         $t2, 0x50($a3)
    /* BEC8 8001B6C8 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* BECC 8001B6CC 14000C8D */  lw         $t4, 0x14($t0)
    /* BED0 8001B6D0 14002D8D */  lw         $t5, 0x14($t1)
    /* BED4 8001B6D4 14004E8D */  lw         $t6, 0x14($t2)
    /* BED8 8001B6D8 43C01900 */  sra        $t8, $t9, 1
    /* BEDC 8001B6DC 2B089801 */  sltu       $at, $t4, $t8
    /* BEE0 8001B6E0 08002010 */  beqz       $at, .L8001B704
    /* BEE4 8001B6E4 2B08B801 */   sltu      $at, $t5, $t8
    /* BEE8 8001B6E8 06002010 */  beqz       $at, .L8001B704
    /* BEEC 8001B6EC 2B08D801 */   sltu      $at, $t6, $t8
    /* BEF0 8001B6F0 04002010 */  beqz       $at, .L8001B704
    /* BEF4 8001B6F4 00000000 */   nop
    /* BEF8 8001B6F8 21108000 */  addu       $v0, $a0, $zero
    /* BEFC 8001B6FC 0800E003 */  jr         $ra
    /* BF00 8001B700 00000000 */   nop
  .L8001B704:
    /* BF04 8001B704 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* BF08 8001B708 0400A28C */  lw         $v0, 0x4($a1)
    /* BF0C 8001B70C 0800A38C */  lw         $v1, 0x8($a1)
    /* BF10 8001B710 03CC1900 */  sra        $t9, $t9, 16
    /* BF14 8001B714 42100200 */  srl        $v0, $v0, 1
    /* BF18 8001B718 42180300 */  srl        $v1, $v1, 1
    /* BF1C 8001B71C 21C02203 */  addu       $t8, $t9, $v0
    /* BF20 8001B720 10000C85 */  lh         $t4, 0x10($t0)
    /* BF24 8001B724 10002D85 */  lh         $t5, 0x10($t1)
    /* BF28 8001B728 10004E85 */  lh         $t6, 0x10($t2)
    /* BF2C 8001B72C 2A080C03 */  slt        $at, $t8, $t4
    /* BF30 8001B730 08002010 */  beqz       $at, .L8001B754
    /* BF34 8001B734 2A080D03 */   slt       $at, $t8, $t5
    /* BF38 8001B738 06002010 */  beqz       $at, .L8001B754
    /* BF3C 8001B73C 2A080E03 */   slt       $at, $t8, $t6
    /* BF40 8001B740 04002010 */  beqz       $at, .L8001B754
    /* BF44 8001B744 00000000 */   nop
    /* BF48 8001B748 21108000 */  addu       $v0, $a0, $zero
    /* BF4C 8001B74C 0800E003 */  jr         $ra
    /* BF50 8001B750 00000000 */   nop
  .L8001B754:
    /* BF54 8001B754 23C02203 */  subu       $t8, $t9, $v0
    /* BF58 8001B758 2A089801 */  slt        $at, $t4, $t8
    /* BF5C 8001B75C 08002010 */  beqz       $at, .L8001B780
    /* BF60 8001B760 2A08B801 */   slt       $at, $t5, $t8
    /* BF64 8001B764 06002010 */  beqz       $at, .L8001B780
    /* BF68 8001B768 2A08D801 */   slt       $at, $t6, $t8
    /* BF6C 8001B76C 04002010 */  beqz       $at, .L8001B780
    /* BF70 8001B770 00000000 */   nop
    /* BF74 8001B774 21108000 */  addu       $v0, $a0, $zero
    /* BF78 8001B778 0800E003 */  jr         $ra
    /* BF7C 8001B77C 00000000 */   nop
  .L8001B780:
    /* BF80 8001B780 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* BF84 8001B784 12000C85 */  lh         $t4, 0x12($t0)
    /* BF88 8001B788 12002D85 */  lh         $t5, 0x12($t1)
    /* BF8C 8001B78C 12004E85 */  lh         $t6, 0x12($t2)
    /* BF90 8001B790 03CC1900 */  sra        $t9, $t9, 16
    /* BF94 8001B794 21C02303 */  addu       $t8, $t9, $v1
    /* BF98 8001B798 2A080C03 */  slt        $at, $t8, $t4
    /* BF9C 8001B79C 08002010 */  beqz       $at, .L8001B7C0
    /* BFA0 8001B7A0 2A080D03 */   slt       $at, $t8, $t5
    /* BFA4 8001B7A4 06002010 */  beqz       $at, .L8001B7C0
    /* BFA8 8001B7A8 2A080E03 */   slt       $at, $t8, $t6
    /* BFAC 8001B7AC 04002010 */  beqz       $at, .L8001B7C0
    /* BFB0 8001B7B0 00000000 */   nop
    /* BFB4 8001B7B4 21108000 */  addu       $v0, $a0, $zero
    /* BFB8 8001B7B8 0800E003 */  jr         $ra
    /* BFBC 8001B7BC 00000000 */   nop
  .L8001B7C0:
    /* BFC0 8001B7C0 23C02303 */  subu       $t8, $t9, $v1
    /* BFC4 8001B7C4 2A089801 */  slt        $at, $t4, $t8
    /* BFC8 8001B7C8 08002010 */  beqz       $at, .L8001B7EC
    /* BFCC 8001B7CC 2A08B801 */   slt       $at, $t5, $t8
    /* BFD0 8001B7D0 06002010 */  beqz       $at, .L8001B7EC
    /* BFD4 8001B7D4 2A08D801 */   slt       $at, $t6, $t8
    /* BFD8 8001B7D8 04002010 */  beqz       $at, .L8001B7EC
    /* BFDC 8001B7DC 00000000 */   nop
    /* BFE0 8001B7E0 21108000 */  addu       $v0, $a0, $zero
    /* BFE4 8001B7E4 0800E003 */  jr         $ra
    /* BFE8 8001B7E8 00000000 */   nop
  .L8001B7EC:
    /* BFEC 8001B7EC 00000C85 */  lh         $t4, 0x0($t0)
    /* BFF0 8001B7F0 00002D85 */  lh         $t5, 0x0($t1)
    /* BFF4 8001B7F4 00004E85 */  lh         $t6, 0x0($t2)
    /* BFF8 8001B7F8 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* BFFC 8001B7FC 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* C000 8001B800 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* C004 8001B804 43780F00 */  sra        $t7, $t7, 1
    /* C008 8001B808 43C01800 */  sra        $t8, $t8, 1
    /* C00C 8001B80C 43C81900 */  sra        $t9, $t9, 1
    /* C010 8001B810 0000EFA4 */  sh         $t7, 0x0($a3)
    /* C014 8001B814 1800F8A4 */  sh         $t8, 0x18($a3)
    /* C018 8001B818 3000F9A4 */  sh         $t9, 0x30($a3)
    /* C01C 8001B81C 02000C85 */  lh         $t4, 0x2($t0)
    /* C020 8001B820 02002D85 */  lh         $t5, 0x2($t1)
    /* C024 8001B824 02004E85 */  lh         $t6, 0x2($t2)
    /* C028 8001B828 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* C02C 8001B82C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* C030 8001B830 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* C034 8001B834 43780F00 */  sra        $t7, $t7, 1
    /* C038 8001B838 43C01800 */  sra        $t8, $t8, 1
    /* C03C 8001B83C 43C81900 */  sra        $t9, $t9, 1
    /* C040 8001B840 0200EFA4 */  sh         $t7, 0x2($a3)
    /* C044 8001B844 1A00F8A4 */  sh         $t8, 0x1A($a3)
    /* C048 8001B848 3200F9A4 */  sh         $t9, 0x32($a3)
    /* C04C 8001B84C 04000C85 */  lh         $t4, 0x4($t0)
    /* C050 8001B850 04002D85 */  lh         $t5, 0x4($t1)
    /* C054 8001B854 04004E85 */  lh         $t6, 0x4($t2)
    /* C058 8001B858 20788D01 */  add        $t7, $t4, $t5 /* handwritten instruction */
    /* C05C 8001B85C 20C0AE01 */  add        $t8, $t5, $t6 /* handwritten instruction */
    /* C060 8001B860 20C8CC01 */  add        $t9, $t6, $t4 /* handwritten instruction */
    /* C064 8001B864 43780F00 */  sra        $t7, $t7, 1
    /* C068 8001B868 43C01800 */  sra        $t8, $t8, 1
    /* C06C 8001B86C 43C81900 */  sra        $t9, $t9, 1
    /* C070 8001B870 0400EFA4 */  sh         $t7, 0x4($a3)
    /* C074 8001B874 1C00F8A4 */  sh         $t8, 0x1C($a3)
    /* C078 8001B878 3400F9A4 */  sh         $t9, 0x34($a3)
    /* C07C 8001B87C 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* C080 8001B880 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* C084 8001B884 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* C088 8001B888 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* C08C 8001B88C 3000E4C8 */  lwc2       $4, 0x30($a3)
    /* C090 8001B890 3400E5C8 */  lwc2       $5, 0x34($a3)
    /* C094 8001B894 08000C91 */  lbu        $t4, 0x8($t0)
    /* C098 8001B898 3000284A */  rtpt
    /* C09C 8001B89C 08002D91 */  lbu        $t5, 0x8($t1)
    /* C0A0 8001B8A0 08004E91 */  lbu        $t6, 0x8($t2)
    /* C0A4 8001B8A4 21788D01 */  addu       $t7, $t4, $t5
    /* C0A8 8001B8A8 21C0AE01 */  addu       $t8, $t5, $t6
    /* C0AC 8001B8AC 21C8CC01 */  addu       $t9, $t6, $t4
    /* C0B0 8001B8B0 42780F00 */  srl        $t7, $t7, 1
    /* C0B4 8001B8B4 42C01800 */  srl        $t8, $t8, 1
    /* C0B8 8001B8B8 42C81900 */  srl        $t9, $t9, 1
    /* C0BC 8001B8BC 0800EFA0 */  sb         $t7, 0x8($a3)
    /* C0C0 8001B8C0 2000F8A0 */  sb         $t8, 0x20($a3)
    /* C0C4 8001B8C4 3800F9A0 */  sb         $t9, 0x38($a3)
    /* C0C8 8001B8C8 09000C91 */  lbu        $t4, 0x9($t0)
    /* C0CC 8001B8CC 09002D91 */  lbu        $t5, 0x9($t1)
    /* C0D0 8001B8D0 09004E91 */  lbu        $t6, 0x9($t2)
    /* C0D4 8001B8D4 21788D01 */  addu       $t7, $t4, $t5
    /* C0D8 8001B8D8 21C0AE01 */  addu       $t8, $t5, $t6
    /* C0DC 8001B8DC 21C8CC01 */  addu       $t9, $t6, $t4
    /* C0E0 8001B8E0 42780F00 */  srl        $t7, $t7, 1
    /* C0E4 8001B8E4 42C01800 */  srl        $t8, $t8, 1
    /* C0E8 8001B8E8 42C81900 */  srl        $t9, $t9, 1
    /* C0EC 8001B8EC 0900EFA0 */  sb         $t7, 0x9($a3)
    /* C0F0 8001B8F0 2100F8A0 */  sb         $t8, 0x21($a3)
    /* C0F4 8001B8F4 3900F9A0 */  sb         $t9, 0x39($a3)
    /* C0F8 8001B8F8 0000AC8C */  lw         $t4, 0x0($a1)
    /* C0FC 8001B8FC 0100C624 */  addiu      $a2, $a2, 0x1
    /* C100 8001B900 1D008615 */  bne        $t4, $a2, .L8001B978
    /* C104 8001B904 00000000 */   nop
    /* C108 8001B908 1000ECE8 */  swc2       $12, 0x10($a3)
    /* C10C 8001B90C 2800EDE8 */  swc2       $13, 0x28($a3)
    /* C110 8001B910 4000EEE8 */  swc2       $14, 0x40($a3)
    /* C114 8001B914 2118E003 */  addu       $v1, $ra, $zero
    /* C118 8001B918 4C00E88C */  lw         $t0, 0x4C($a3)
    /* C11C 8001B91C 1800E924 */  addiu      $t1, $a3, 0x18
    /* C120 8001B920 0000EA24 */  addiu      $t2, $a3, 0x0
    /* C124 8001B924 8C6E000C */  jal        func_8001BA30
    /* C128 8001B928 00000000 */   nop
    /* C12C 8001B92C 0000E824 */  addiu      $t0, $a3, 0x0
    /* C130 8001B930 1800E924 */  addiu      $t1, $a3, 0x18
    /* C134 8001B934 3000EA24 */  addiu      $t2, $a3, 0x30
    /* C138 8001B938 8C6E000C */  jal        func_8001BA30
    /* C13C 8001B93C 00000000 */   nop
    /* C140 8001B940 4800E88C */  lw         $t0, 0x48($a3)
    /* C144 8001B944 0000E924 */  addiu      $t1, $a3, 0x0
    /* C148 8001B948 3000EA24 */  addiu      $t2, $a3, 0x30
    /* C14C 8001B94C 8C6E000C */  jal        func_8001BA30
    /* C150 8001B950 00000000 */   nop
    /* C154 8001B954 5000E88C */  lw         $t0, 0x50($a3)
    /* C158 8001B958 3000E924 */  addiu      $t1, $a3, 0x30
    /* C15C 8001B95C 1800EA24 */  addiu      $t2, $a3, 0x18
    /* C160 8001B960 8C6E000C */  jal        func_8001BA30
    /* C164 8001B964 00000000 */   nop
    /* C168 8001B968 21F86000 */  addu       $ra, $v1, $zero
    /* C16C 8001B96C FFFFC624 */  addiu      $a2, $a2, -0x1
    /* C170 8001B970 2C000010 */  b          .L8001BA24
    /* C174 8001B974 00000000 */   nop
  .L8001B978:
    /* C178 8001B978 1400F1E8 */  swc2       $17, 0x14($a3)
    /* C17C 8001B97C 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* C180 8001B980 4400F3E8 */  swc2       $19, 0x44($a3)
    /* C184 8001B984 1000ECE8 */  swc2       $12, 0x10($a3)
    /* C188 8001B988 2800EDE8 */  swc2       $13, 0x28($a3)
    /* C18C 8001B98C 4000EEE8 */  swc2       $14, 0x40($a3)
    /* C190 8001B990 5800E724 */  addiu      $a3, $a3, 0x58
    /* C194 8001B994 5400FFAC */  sw         $ra, 0x54($a3)
    /* C198 8001B998 F0FFEC8C */  lw         $t4, -0x10($a3)
    /* C19C 8001B99C A8FFED24 */  addiu      $t5, $a3, -0x58
    /* C1A0 8001B9A0 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* C1A4 8001B9A4 4800ECAC */  sw         $t4, 0x48($a3)
    /* C1A8 8001B9A8 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* C1AC 8001B9AC 5000EEAC */  sw         $t6, 0x50($a3)
    /* C1B0 8001B9B0 AF6D000C */  jal        func_8001B6BC
    /* C1B4 8001B9B4 00000000 */   nop
    /* C1B8 8001B9B8 F4FFEC8C */  lw         $t4, -0xC($a3)
    /* C1BC 8001B9BC C0FFED24 */  addiu      $t5, $a3, -0x40
    /* C1C0 8001B9C0 A8FFEE24 */  addiu      $t6, $a3, -0x58
    /* C1C4 8001B9C4 4800ECAC */  sw         $t4, 0x48($a3)
    /* C1C8 8001B9C8 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* C1CC 8001B9CC 5000EEAC */  sw         $t6, 0x50($a3)
    /* C1D0 8001B9D0 AF6D000C */  jal        func_8001B6BC
    /* C1D4 8001B9D4 00000000 */   nop
    /* C1D8 8001B9D8 F8FFEC8C */  lw         $t4, -0x8($a3)
    /* C1DC 8001B9DC D8FFED24 */  addiu      $t5, $a3, -0x28
    /* C1E0 8001B9E0 C0FFEE24 */  addiu      $t6, $a3, -0x40
    /* C1E4 8001B9E4 4800ECAC */  sw         $t4, 0x48($a3)
    /* C1E8 8001B9E8 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* C1EC 8001B9EC 5000EEAC */  sw         $t6, 0x50($a3)
    /* C1F0 8001B9F0 AF6D000C */  jal        func_8001B6BC
    /* C1F4 8001B9F4 00000000 */   nop
    /* C1F8 8001B9F8 A8FFEC24 */  addiu      $t4, $a3, -0x58
    /* C1FC 8001B9FC C0FFED24 */  addiu      $t5, $a3, -0x40
    /* C200 8001BA00 D8FFEE24 */  addiu      $t6, $a3, -0x28
    /* C204 8001BA04 4800ECAC */  sw         $t4, 0x48($a3)
    /* C208 8001BA08 4C00EDAC */  sw         $t5, 0x4C($a3)
    /* C20C 8001BA0C 5000EEAC */  sw         $t6, 0x50($a3)
    /* C210 8001BA10 AF6D000C */  jal        func_8001B6BC
    /* C214 8001BA14 00000000 */   nop
    /* C218 8001BA18 5400FF8C */  lw         $ra, 0x54($a3)
    /* C21C 8001BA1C A8FFE724 */  addiu      $a3, $a3, -0x58
    /* C220 8001BA20 FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001BA24:
    /* C224 8001BA24 21108000 */  addu       $v0, $a0, $zero
    /* C228 8001BA28 0800E003 */  jr         $ra
    /* C22C 8001BA2C 00000000 */   nop
endlabel func_8001B6BC

nonmatching func_8001BA30, 0x7C

glabel func_8001BA30
    /* C230 8001BA30 0C00AC94 */  lhu        $t4, 0xC($a1)
    /* C234 8001BA34 08000D95 */  lhu        $t5, 0x8($t0)
    /* C238 8001BA38 00640C00 */  sll        $t4, $t4, 16
    /* C23C 8001BA3C 2168AC01 */  addu       $t5, $t5, $t4
    /* C240 8001BA40 0E00AC94 */  lhu        $t4, 0xE($a1)
    /* C244 8001BA44 08002E95 */  lhu        $t6, 0x8($t1)
    /* C248 8001BA48 00640C00 */  sll        $t4, $t4, 16
    /* C24C 8001BA4C 2170CC01 */  addu       $t6, $t6, $t4
    /* C250 8001BA50 08004F95 */  lhu        $t7, 0x8($t2)
    /* C254 8001BA54 1000AC8C */  lw         $t4, 0x10($a1)
    /* C258 8001BA58 0C008DAC */  sw         $t5, 0xC($a0)
    /* C25C 8001BA5C 14008EAC */  sw         $t6, 0x14($a0)
    /* C260 8001BA60 1C008FAC */  sw         $t7, 0x1C($a0)
    /* C264 8001BA64 04008CAC */  sw         $t4, 0x4($a0)
    /* C268 8001BA68 10000C8D */  lw         $t4, 0x10($t0)
    /* C26C 8001BA6C 10002D8D */  lw         $t5, 0x10($t1)
    /* C270 8001BA70 10004E8D */  lw         $t6, 0x10($t2)
    /* C274 8001BA74 08008CAC */  sw         $t4, 0x8($a0)
    /* C278 8001BA78 10008DAC */  sw         $t5, 0x10($a0)
    /* C27C 8001BA7C 18008EAC */  sw         $t6, 0x18($a0)
    /* C280 8001BA80 1400AC8C */  lw         $t4, 0x14($a1)
    /* C284 8001BA84 00CA0400 */  sll        $t9, $a0, 8
    /* C288 8001BA88 02CA1900 */  srl        $t9, $t9, 8
    /* C28C 8001BA8C 0000988D */  lw         $t8, 0x0($t4)
    /* C290 8001BA90 000099AD */  sw         $t9, 0x0($t4)
    /* C294 8001BA94 00070E3C */  lui        $t6, (0x7000000 >> 16)
    /* C298 8001BA98 25C00E03 */  or         $t8, $t8, $t6
    /* C29C 8001BA9C 000098AC */  sw         $t8, 0x0($a0)
    /* C2A0 8001BAA0 20008424 */  addiu      $a0, $a0, 0x20
    /* C2A4 8001BAA4 0800E003 */  jr         $ra
    /* C2A8 8001BAA8 00000000 */   nop
endlabel func_8001BA30
    /* C2AC 8001BAAC 00000000 */  nop
    /* C2B0 8001BAB0 00000000 */  nop
