.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

/* Handwritten function */
nonmatching func_8001A8D4, 0x8

glabel func_8001A8D4
    /* B0D4 8001A8D4 7800A720 */  addi       $a3, $a1, 0x78 /* handwritten instruction */
    /* B0D8 8001A8D8 00000624 */  addiu      $a2, $zero, 0x0
endlabel func_8001A8D4

/* Handwritten function */
nonmatching func_8001A8DC, 0x420

glabel func_8001A8DC
    /* B0DC 8001A8DC 7800E88C */  lw         $t0, 0x78($a3)
    /* B0E0 8001A8E0 7C00E98C */  lw         $t1, 0x7C($a3)
    /* B0E4 8001A8E4 8000EA8C */  lw         $t2, 0x80($a3)
    /* B0E8 8001A8E8 8400EB8C */  lw         $t3, 0x84($a3)
    /* B0EC 8001A8EC 00D05948 */  cfc2       $t9, $26 /* handwritten instruction */
    /* B0F0 8001A8F0 14000C8D */  lw         $t4, 0x14($t0)
    /* B0F4 8001A8F4 14002D8D */  lw         $t5, 0x14($t1)
    /* B0F8 8001A8F8 14004E8D */  lw         $t6, 0x14($t2)
    /* B0FC 8001A8FC 14006F8D */  lw         $t7, 0x14($t3)
    /* B100 8001A900 43C01900 */  sra        $t8, $t9, 1
    /* B104 8001A904 2B089801 */  sltu       $at, $t4, $t8
    /* B108 8001A908 0A002010 */  beqz       $at, .L8001A934
    /* B10C 8001A90C 2B08B801 */   sltu      $at, $t5, $t8
    /* B110 8001A910 08002010 */  beqz       $at, .L8001A934
    /* B114 8001A914 2B08D801 */   sltu      $at, $t6, $t8
    /* B118 8001A918 06002010 */  beqz       $at, .L8001A934
    /* B11C 8001A91C 2B08F801 */   sltu      $at, $t7, $t8
    /* B120 8001A920 04002010 */  beqz       $at, .L8001A934
    /* B124 8001A924 00000000 */   nop
    /* B128 8001A928 21108000 */  addu       $v0, $a0, $zero
    /* B12C 8001A92C 0800E003 */  jr         $ra
    /* B130 8001A930 00000000 */   nop
  .L8001A934:
    /* B134 8001A934 00C05948 */  cfc2       $t9, $24 /* handwritten instruction */
    /* B138 8001A938 0400A28C */  lw         $v0, 0x4($a1)
    /* B13C 8001A93C 0800A38C */  lw         $v1, 0x8($a1)
    /* B140 8001A940 03CC1900 */  sra        $t9, $t9, 16
    /* B144 8001A944 42100200 */  srl        $v0, $v0, 1
    /* B148 8001A948 42180300 */  srl        $v1, $v1, 1
    /* B14C 8001A94C 21C02203 */  addu       $t8, $t9, $v0
    /* B150 8001A950 10000C85 */  lh         $t4, 0x10($t0)
    /* B154 8001A954 10002D85 */  lh         $t5, 0x10($t1)
    /* B158 8001A958 10004E85 */  lh         $t6, 0x10($t2)
    /* B15C 8001A95C 10006F85 */  lh         $t7, 0x10($t3)
    /* B160 8001A960 2A080C03 */  slt        $at, $t8, $t4
    /* B164 8001A964 0A002010 */  beqz       $at, .L8001A990
    /* B168 8001A968 2A080D03 */   slt       $at, $t8, $t5
    /* B16C 8001A96C 08002010 */  beqz       $at, .L8001A990
    /* B170 8001A970 2A080E03 */   slt       $at, $t8, $t6
    /* B174 8001A974 06002010 */  beqz       $at, .L8001A990
    /* B178 8001A978 2A080F03 */   slt       $at, $t8, $t7
    /* B17C 8001A97C 04002010 */  beqz       $at, .L8001A990
    /* B180 8001A980 00000000 */   nop
    /* B184 8001A984 21108000 */  addu       $v0, $a0, $zero
    /* B188 8001A988 0800E003 */  jr         $ra
    /* B18C 8001A98C 00000000 */   nop
  .L8001A990:
    /* B190 8001A990 23C02203 */  subu       $t8, $t9, $v0
    /* B194 8001A994 2A089801 */  slt        $at, $t4, $t8
    /* B198 8001A998 0A002010 */  beqz       $at, .L8001A9C4
    /* B19C 8001A99C 2A08B801 */   slt       $at, $t5, $t8
    /* B1A0 8001A9A0 08002010 */  beqz       $at, .L8001A9C4
    /* B1A4 8001A9A4 2A08D801 */   slt       $at, $t6, $t8
    /* B1A8 8001A9A8 06002010 */  beqz       $at, .L8001A9C4
    /* B1AC 8001A9AC 2A08F801 */   slt       $at, $t7, $t8
    /* B1B0 8001A9B0 04002010 */  beqz       $at, .L8001A9C4
    /* B1B4 8001A9B4 00000000 */   nop
    /* B1B8 8001A9B8 21108000 */  addu       $v0, $a0, $zero
    /* B1BC 8001A9BC 0800E003 */  jr         $ra
    /* B1C0 8001A9C0 00000000 */   nop
  .L8001A9C4:
    /* B1C4 8001A9C4 00C85948 */  cfc2       $t9, $25 /* handwritten instruction */
    /* B1C8 8001A9C8 12000C85 */  lh         $t4, 0x12($t0)
    /* B1CC 8001A9CC 12002D85 */  lh         $t5, 0x12($t1)
    /* B1D0 8001A9D0 12004E85 */  lh         $t6, 0x12($t2)
    /* B1D4 8001A9D4 12006F85 */  lh         $t7, 0x12($t3)
    /* B1D8 8001A9D8 03CC1900 */  sra        $t9, $t9, 16
    /* B1DC 8001A9DC 21C02303 */  addu       $t8, $t9, $v1
    /* B1E0 8001A9E0 2A080C03 */  slt        $at, $t8, $t4
    /* B1E4 8001A9E4 0A002010 */  beqz       $at, .L8001AA10
    /* B1E8 8001A9E8 2A080D03 */   slt       $at, $t8, $t5
    /* B1EC 8001A9EC 08002010 */  beqz       $at, .L8001AA10
    /* B1F0 8001A9F0 2A080E03 */   slt       $at, $t8, $t6
    /* B1F4 8001A9F4 06002010 */  beqz       $at, .L8001AA10
    /* B1F8 8001A9F8 2A080F03 */   slt       $at, $t8, $t7
    /* B1FC 8001A9FC 04002010 */  beqz       $at, .L8001AA10
    /* B200 8001AA00 00000000 */   nop
    /* B204 8001AA04 21108000 */  addu       $v0, $a0, $zero
    /* B208 8001AA08 0800E003 */  jr         $ra
    /* B20C 8001AA0C 00000000 */   nop
  .L8001AA10:
    /* B210 8001AA10 23C02303 */  subu       $t8, $t9, $v1
    /* B214 8001AA14 2A089801 */  slt        $at, $t4, $t8
    /* B218 8001AA18 0A002010 */  beqz       $at, .L8001AA44
    /* B21C 8001AA1C 2A08B801 */   slt       $at, $t5, $t8
    /* B220 8001AA20 08002010 */  beqz       $at, .L8001AA44
    /* B224 8001AA24 2A08D801 */   slt       $at, $t6, $t8
    /* B228 8001AA28 06002010 */  beqz       $at, .L8001AA44
    /* B22C 8001AA2C 2A08F801 */   slt       $at, $t7, $t8
    /* B230 8001AA30 04002010 */  beqz       $at, .L8001AA44
    /* B234 8001AA34 00000000 */   nop
    /* B238 8001AA38 21108000 */  addu       $v0, $a0, $zero
    /* B23C 8001AA3C 0800E003 */  jr         $ra
    /* B240 8001AA40 00000000 */   nop
  .L8001AA44:
    /* B244 8001AA44 00000C85 */  lh         $t4, 0x0($t0)
    /* B248 8001AA48 02000D85 */  lh         $t5, 0x2($t0)
    /* B24C 8001AA4C 04000E85 */  lh         $t6, 0x4($t0)
    /* B250 8001AA50 00002F85 */  lh         $t7, 0x0($t1)
    /* B254 8001AA54 02003885 */  lh         $t8, 0x2($t1)
    /* B258 8001AA58 04003985 */  lh         $t9, 0x4($t1)
    /* B25C 8001AA5C 20108F01 */  add        $v0, $t4, $t7 /* handwritten instruction */
    /* B260 8001AA60 43100200 */  sra        $v0, $v0, 1
    /* B264 8001AA64 0000E2A4 */  sh         $v0, 0x0($a3)
    /* B268 8001AA68 2010B801 */  add        $v0, $t5, $t8 /* handwritten instruction */
    /* B26C 8001AA6C 43100200 */  sra        $v0, $v0, 1
    /* B270 8001AA70 0200E2A4 */  sh         $v0, 0x2($a3)
    /* B274 8001AA74 2010D901 */  add        $v0, $t6, $t9 /* handwritten instruction */
    /* B278 8001AA78 43100200 */  sra        $v0, $v0, 1
    /* B27C 8001AA7C 0400E2A4 */  sh         $v0, 0x4($a3)
    /* B280 8001AA80 00004F85 */  lh         $t7, 0x0($t2)
    /* B284 8001AA84 02005885 */  lh         $t8, 0x2($t2)
    /* B288 8001AA88 04005985 */  lh         $t9, 0x4($t2)
    /* B28C 8001AA8C 20108F01 */  add        $v0, $t4, $t7 /* handwritten instruction */
    /* B290 8001AA90 43100200 */  sra        $v0, $v0, 1
    /* B294 8001AA94 1800E2A4 */  sh         $v0, 0x18($a3)
    /* B298 8001AA98 2010B801 */  add        $v0, $t5, $t8 /* handwritten instruction */
    /* B29C 8001AA9C 43100200 */  sra        $v0, $v0, 1
    /* B2A0 8001AAA0 1A00E2A4 */  sh         $v0, 0x1A($a3)
    /* B2A4 8001AAA4 2010D901 */  add        $v0, $t6, $t9 /* handwritten instruction */
    /* B2A8 8001AAA8 43100200 */  sra        $v0, $v0, 1
    /* B2AC 8001AAAC 1C00E2A4 */  sh         $v0, 0x1C($a3)
    /* B2B0 8001AAB0 0000E0C8 */  lwc2       $0, 0x0($a3)
    /* B2B4 8001AAB4 0400E1C8 */  lwc2       $1, 0x4($a3)
    /* B2B8 8001AAB8 1800E2C8 */  lwc2       $2, 0x18($a3)
    /* B2BC 8001AABC 1C00E3C8 */  lwc2       $3, 0x1C($a3)
    /* B2C0 8001AAC0 00000000 */  nop
    /* B2C4 8001AAC4 3000284A */  rtpt
    /* B2C8 8001AAC8 00006C85 */  lh         $t4, 0x0($t3)
    /* B2CC 8001AACC 02006D85 */  lh         $t5, 0x2($t3)
    /* B2D0 8001AAD0 04006E85 */  lh         $t6, 0x4($t3)
    /* B2D4 8001AAD4 20108F01 */  add        $v0, $t4, $t7 /* handwritten instruction */
    /* B2D8 8001AAD8 43100200 */  sra        $v0, $v0, 1
    /* B2DC 8001AADC 4800E2A4 */  sh         $v0, 0x48($a3)
    /* B2E0 8001AAE0 2010B801 */  add        $v0, $t5, $t8 /* handwritten instruction */
    /* B2E4 8001AAE4 43100200 */  sra        $v0, $v0, 1
    /* B2E8 8001AAE8 4A00E2A4 */  sh         $v0, 0x4A($a3)
    /* B2EC 8001AAEC 2010D901 */  add        $v0, $t6, $t9 /* handwritten instruction */
    /* B2F0 8001AAF0 43100200 */  sra        $v0, $v0, 1
    /* B2F4 8001AAF4 4C00E2A4 */  sh         $v0, 0x4C($a3)
    /* B2F8 8001AAF8 00002F85 */  lh         $t7, 0x0($t1)
    /* B2FC 8001AAFC 02003885 */  lh         $t8, 0x2($t1)
    /* B300 8001AB00 04003985 */  lh         $t9, 0x4($t1)
    /* B304 8001AB04 20108F01 */  add        $v0, $t4, $t7 /* handwritten instruction */
    /* B308 8001AB08 43100200 */  sra        $v0, $v0, 1
    /* B30C 8001AB0C 3000E2A4 */  sh         $v0, 0x30($a3)
    /* B310 8001AB10 2010B801 */  add        $v0, $t5, $t8 /* handwritten instruction */
    /* B314 8001AB14 43100200 */  sra        $v0, $v0, 1
    /* B318 8001AB18 3200E2A4 */  sh         $v0, 0x32($a3)
    /* B31C 8001AB1C 2010D901 */  add        $v0, $t6, $t9 /* handwritten instruction */
    /* B320 8001AB20 43100200 */  sra        $v0, $v0, 1
    /* B324 8001AB24 3400E2A4 */  sh         $v0, 0x34($a3)
    /* B328 8001AB28 0000EC84 */  lh         $t4, 0x0($a3)
    /* B32C 8001AB2C 0200ED84 */  lh         $t5, 0x2($a3)
    /* B330 8001AB30 0400EE84 */  lh         $t6, 0x4($a3)
    /* B334 8001AB34 4800EF84 */  lh         $t7, 0x48($a3)
    /* B338 8001AB38 4A00F884 */  lh         $t8, 0x4A($a3)
    /* B33C 8001AB3C 4C00F984 */  lh         $t9, 0x4C($a3)
    /* B340 8001AB40 20108F01 */  add        $v0, $t4, $t7 /* handwritten instruction */
    /* B344 8001AB44 43100200 */  sra        $v0, $v0, 1
    /* B348 8001AB48 6000E2A4 */  sh         $v0, 0x60($a3)
    /* B34C 8001AB4C 2010B801 */  add        $v0, $t5, $t8 /* handwritten instruction */
    /* B350 8001AB50 43100200 */  sra        $v0, $v0, 1
    /* B354 8001AB54 6200E2A4 */  sh         $v0, 0x62($a3)
    /* B358 8001AB58 2010D901 */  add        $v0, $t6, $t9 /* handwritten instruction */
    /* B35C 8001AB5C 43100200 */  sra        $v0, $v0, 1
    /* B360 8001AB60 6400E2A4 */  sh         $v0, 0x64($a3)
    /* B364 8001AB64 1000ECE8 */  swc2       $12, 0x10($a3)
    /* B368 8001AB68 2800EDE8 */  swc2       $13, 0x28($a3)
    /* B36C 8001AB6C 1400F1E8 */  swc2       $17, 0x14($a3)
    /* B370 8001AB70 2C00F2E8 */  swc2       $18, 0x2C($a3)
    /* B374 8001AB74 3000E0C8 */  lwc2       $0, 0x30($a3)
    /* B378 8001AB78 3400E1C8 */  lwc2       $1, 0x34($a3)
    /* B37C 8001AB7C 4800E2C8 */  lwc2       $2, 0x48($a3)
    /* B380 8001AB80 4C00E3C8 */  lwc2       $3, 0x4C($a3)
    /* B384 8001AB84 6000E4C8 */  lwc2       $4, 0x60($a3)
    /* B388 8001AB88 6400E5C8 */  lwc2       $5, 0x64($a3)
    /* B38C 8001AB8C 00000000 */  nop
    /* B390 8001AB90 3000284A */  rtpt
    /* B394 8001AB94 0000AC8C */  lw         $t4, 0x0($a1)
    /* B398 8001AB98 0100C624 */  addiu      $a2, $a2, 0x1
    /* B39C 8001AB9C 21008615 */  bne        $t4, $a2, .L8001AC24
    /* B3A0 8001ABA0 00000000 */   nop
    /* B3A4 8001ABA4 2118E003 */  addu       $v1, $ra, $zero
    /* B3A8 8001ABA8 7800E88C */  lw         $t0, 0x78($a3)
    /* B3AC 8001ABAC 0000E924 */  addiu      $t1, $a3, 0x0
    /* B3B0 8001ABB0 1800EA24 */  addiu      $t2, $a3, 0x18
    /* B3B4 8001ABB4 6000EB24 */  addiu      $t3, $a3, 0x60
    /* B3B8 8001ABB8 4000ECE8 */  swc2       $12, 0x40($a3)
    /* B3BC 8001ABBC 5800EDE8 */  swc2       $13, 0x58($a3)
    /* B3C0 8001ABC0 7000EEE8 */  swc2       $14, 0x70($a3)
    /* B3C4 8001ABC4 3F6B000C */  jal        func_8001ACFC
    /* B3C8 8001ABC8 00000000 */   nop
    /* B3CC 8001ABCC 7C00E88C */  lw         $t0, 0x7C($a3)
    /* B3D0 8001ABD0 3000E924 */  addiu      $t1, $a3, 0x30
    /* B3D4 8001ABD4 0000EA24 */  addiu      $t2, $a3, 0x0
    /* B3D8 8001ABD8 6000EB24 */  addiu      $t3, $a3, 0x60
    /* B3DC 8001ABDC 3F6B000C */  jal        func_8001ACFC
    /* B3E0 8001ABE0 00000000 */   nop
    /* B3E4 8001ABE4 8000E88C */  lw         $t0, 0x80($a3)
    /* B3E8 8001ABE8 1800E924 */  addiu      $t1, $a3, 0x18
    /* B3EC 8001ABEC 4800EA24 */  addiu      $t2, $a3, 0x48
    /* B3F0 8001ABF0 6000EB24 */  addiu      $t3, $a3, 0x60
    /* B3F4 8001ABF4 3F6B000C */  jal        func_8001ACFC
    /* B3F8 8001ABF8 00000000 */   nop
    /* B3FC 8001ABFC 8400E88C */  lw         $t0, 0x84($a3)
    /* B400 8001AC00 4800E924 */  addiu      $t1, $a3, 0x48
    /* B404 8001AC04 3000EA24 */  addiu      $t2, $a3, 0x30
    /* B408 8001AC08 6000EB24 */  addiu      $t3, $a3, 0x60
    /* B40C 8001AC0C 3F6B000C */  jal        func_8001ACFC
    /* B410 8001AC10 00000000 */   nop
    /* B414 8001AC14 21F86000 */  addu       $ra, $v1, $zero
    /* B418 8001AC18 FFFFC624 */  addiu      $a2, $a2, -0x1
    /* B41C 8001AC1C 34000010 */  b          .L8001ACF0
    /* B420 8001AC20 00000000 */   nop
  .L8001AC24:
    /* B424 8001AC24 8C00E724 */  addiu      $a3, $a3, 0x8C
    /* B428 8001AC28 8800FFAC */  sw         $ra, 0x88($a3)
    /* B42C 8001AC2C ECFFEC8C */  lw         $t4, -0x14($a3)
    /* B430 8001AC30 74FFED24 */  addiu      $t5, $a3, -0x8C
    /* B434 8001AC34 8CFFEE24 */  addiu      $t6, $a3, -0x74
    /* B438 8001AC38 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* B43C 8001AC3C 7800ECAC */  sw         $t4, 0x78($a3)
    /* B440 8001AC40 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* B444 8001AC44 8000EEAC */  sw         $t6, 0x80($a3)
    /* B448 8001AC48 8400EFAC */  sw         $t7, 0x84($a3)
    /* B44C 8001AC4C B4FFECE8 */  swc2       $12, -0x4C($a3)
    /* B450 8001AC50 CCFFEDE8 */  swc2       $13, -0x34($a3)
    /* B454 8001AC54 E4FFEEE8 */  swc2       $14, -0x1C($a3)
    /* B458 8001AC58 B8FFF1E8 */  swc2       $17, -0x48($a3)
    /* B45C 8001AC5C D0FFF2E8 */  swc2       $18, -0x30($a3)
    /* B460 8001AC60 E8FFF3E8 */  swc2       $19, -0x18($a3)
    /* B464 8001AC64 376A000C */  jal        func_8001A8DC
    /* B468 8001AC68 00000000 */   nop
    /* B46C 8001AC6C F0FFEC8C */  lw         $t4, -0x10($a3)
    /* B470 8001AC70 A4FFED24 */  addiu      $t5, $a3, -0x5C
    /* B474 8001AC74 74FFEE24 */  addiu      $t6, $a3, -0x8C
    /* B478 8001AC78 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* B47C 8001AC7C 7800ECAC */  sw         $t4, 0x78($a3)
    /* B480 8001AC80 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* B484 8001AC84 8000EEAC */  sw         $t6, 0x80($a3)
    /* B488 8001AC88 8400EFAC */  sw         $t7, 0x84($a3)
    /* B48C 8001AC8C 376A000C */  jal        func_8001A8DC
    /* B490 8001AC90 00000000 */   nop
    /* B494 8001AC94 F4FFEC8C */  lw         $t4, -0xC($a3)
    /* B498 8001AC98 8CFFED24 */  addiu      $t5, $a3, -0x74
    /* B49C 8001AC9C BCFFEE24 */  addiu      $t6, $a3, -0x44
    /* B4A0 8001ACA0 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* B4A4 8001ACA4 7800ECAC */  sw         $t4, 0x78($a3)
    /* B4A8 8001ACA8 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* B4AC 8001ACAC 8000EEAC */  sw         $t6, 0x80($a3)
    /* B4B0 8001ACB0 8400EFAC */  sw         $t7, 0x84($a3)
    /* B4B4 8001ACB4 376A000C */  jal        func_8001A8DC
    /* B4B8 8001ACB8 00000000 */   nop
    /* B4BC 8001ACBC F8FFEC8C */  lw         $t4, -0x8($a3)
    /* B4C0 8001ACC0 BCFFED24 */  addiu      $t5, $a3, -0x44
    /* B4C4 8001ACC4 A4FFEE24 */  addiu      $t6, $a3, -0x5C
    /* B4C8 8001ACC8 D4FFEF24 */  addiu      $t7, $a3, -0x2C
    /* B4CC 8001ACCC 7800ECAC */  sw         $t4, 0x78($a3)
    /* B4D0 8001ACD0 7C00EDAC */  sw         $t5, 0x7C($a3)
    /* B4D4 8001ACD4 8000EEAC */  sw         $t6, 0x80($a3)
    /* B4D8 8001ACD8 8400EFAC */  sw         $t7, 0x84($a3)
    /* B4DC 8001ACDC 376A000C */  jal        func_8001A8DC
    /* B4E0 8001ACE0 00000000 */   nop
    /* B4E4 8001ACE4 8800FF8C */  lw         $ra, 0x88($a3)
    /* B4E8 8001ACE8 74FFE724 */  addiu      $a3, $a3, -0x8C
    /* B4EC 8001ACEC FFFFC624 */  addiu      $a2, $a2, -0x1
  .L8001ACF0:
    /* B4F0 8001ACF0 21108000 */  addu       $v0, $a0, $zero
    /* B4F4 8001ACF4 0800E003 */  jr         $ra
    /* B4F8 8001ACF8 00000000 */   nop
endlabel func_8001A8DC

nonmatching func_8001ACFC, 0x54

glabel func_8001ACFC
    /* B4FC 8001ACFC 1000B88C */  lw         $t8, 0x10($a1)
    /* B500 8001AD00 10000C8D */  lw         $t4, 0x10($t0)
    /* B504 8001AD04 10002D8D */  lw         $t5, 0x10($t1)
    /* B508 8001AD08 10004E8D */  lw         $t6, 0x10($t2)
    /* B50C 8001AD0C 10006F8D */  lw         $t7, 0x10($t3)
    /* B510 8001AD10 040098AC */  sw         $t8, 0x4($a0)
    /* B514 8001AD14 08008CAC */  sw         $t4, 0x8($a0)
    /* B518 8001AD18 0C008DAC */  sw         $t5, 0xC($a0)
    /* B51C 8001AD1C 10008EAC */  sw         $t6, 0x10($a0)
    /* B520 8001AD20 14008FAC */  sw         $t7, 0x14($a0)
    /* B524 8001AD24 1400AC8C */  lw         $t4, 0x14($a1)
    /* B528 8001AD28 00CA0400 */  sll        $t9, $a0, 8
    /* B52C 8001AD2C 02CA1900 */  srl        $t9, $t9, 8
    /* B530 8001AD30 0000988D */  lw         $t8, 0x0($t4)
    /* B534 8001AD34 000099AD */  sw         $t9, 0x0($t4)
    /* B538 8001AD38 00050E3C */  lui        $t6, (0x5000000 >> 16)
    /* B53C 8001AD3C 25C00E03 */  or         $t8, $t8, $t6
    /* B540 8001AD40 000098AC */  sw         $t8, 0x0($a0)
    /* B544 8001AD44 18008424 */  addiu      $a0, $a0, 0x18
    /* B548 8001AD48 0800E003 */  jr         $ra
    /* B54C 8001AD4C 00000000 */   nop
endlabel func_8001ACFC
    /* B550 8001AD50 00000000 */  nop
