.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.41.0 */

nonmatching func_80025EAC, 0x50

glabel func_80025EAC
    /* 166AC 80025EAC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 166B0 80025EB0 FFFF0224 */  addiu      $v0, $zero, -0x1
    /* 166B4 80025EB4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 166B8 80025EB8 0980013C */  lui        $at, %hi(D_8008E984)
    /* 166BC 80025EBC 84E924AC */  sw         $a0, %lo(D_8008E984)($at)
    /* 166C0 80025EC0 0980013C */  lui        $at, %hi(D_8008B3C8)
    /* 166C4 80025EC4 C8B322AC */  sw         $v0, %lo(D_8008B3C8)($at)
    /* 166C8 80025EC8 4493000C */  jal        func_80024D10
    /* 166CC 80025ECC 00000000 */   nop
    /* 166D0 80025ED0 0020043C */  lui        $a0, (0x20000001 >> 16)
    /* 166D4 80025ED4 0980053C */  lui        $a1, %hi(D_8008B3C8)
    /* 166D8 80025ED8 C8B3A524 */  addiu      $a1, $a1, %lo(D_8008B3C8)
    /* 166DC 80025EDC DB97000C */  jal        func_80025F6C
    /* 166E0 80025EE0 01008434 */   ori       $a0, $a0, (0x20000001 & 0xFFFF)
    /* 166E4 80025EE4 0D95000C */  jal        func_80025434
    /* 166E8 80025EE8 21200000 */   addu      $a0, $zero, $zero
    /* 166EC 80025EEC 1000BF8F */  lw         $ra, 0x10($sp)
    /* 166F0 80025EF0 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 166F4 80025EF4 0800E003 */  jr         $ra
    /* 166F8 80025EF8 00000000 */   nop
endlabel func_80025EAC

nonmatching PadRead, 0x30

glabel PadRead
    /* 166FC 80025EFC E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 16700 80025F00 1000BFAF */  sw         $ra, 0x10($sp)
    /* 16704 80025F04 D397000C */  jal        func_80025F4C
    /* 16708 80025F08 00000000 */   nop
    /* 1670C 80025F0C 0980023C */  lui        $v0, %hi(D_8008B3C8)
    /* 16710 80025F10 C8B3428C */  lw         $v0, %lo(D_8008B3C8)($v0)
    /* 16714 80025F14 00000000 */  nop
    /* 16718 80025F18 27100200 */  nor        $v0, $zero, $v0
    /* 1671C 80025F1C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 16720 80025F20 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 16724 80025F24 0800E003 */  jr         $ra
    /* 16728 80025F28 00000000 */   nop
endlabel PadRead

nonmatching PadShutdownAll, 0x20

glabel PadShutdownAll
    /* 1672C 80025F2C E8FFBD27 */  addiu      $sp, $sp, -0x18
    /* 16730 80025F30 1000BFAF */  sw         $ra, 0x10($sp)
    /* 16734 80025F34 D797000C */  jal        func_80025F5C
    /* 16738 80025F38 00000000 */   nop
    /* 1673C 80025F3C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 16740 80025F40 1800BD27 */  addiu      $sp, $sp, 0x18
    /* 16744 80025F44 0800E003 */  jr         $ra
    /* 16748 80025F48 00000000 */   nop
endlabel PadShutdownAll

nonmatching func_80025F4C, 0xC

glabel func_80025F4C
    /* 1674C 80025F4C B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 16750 80025F50 08004001 */  jr         $t2
    /* 16754 80025F54 16000924 */   addiu     $t1, $zero, 0x16
endlabel func_80025F4C
    /* 16758 80025F58 00000000 */  nop

nonmatching func_80025F5C, 0xC

glabel func_80025F5C
    /* 1675C 80025F5C B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 16760 80025F60 08004001 */  jr         $t2
    /* 16764 80025F64 14000924 */   addiu     $t1, $zero, 0x14
endlabel func_80025F5C
    /* 16768 80025F68 00000000 */  nop

nonmatching func_80025F6C, 0xC

glabel func_80025F6C
    /* 1676C 80025F6C B0000A24 */  addiu      $t2, $zero, 0xB0
    /* 16770 80025F70 08004001 */  jr         $t2
    /* 16774 80025F74 15000924 */   addiu     $t1, $zero, 0x15
endlabel func_80025F6C
    /* 16778 80025F78 00000000 */  nop
