#ifndef OBJECT_H
#define OBJECT_H

#include "types.h"

typedef struct Object {
    struct Object *unk0;
    struct Object *unk1;
    struct Object *unk2;
    struct Object *unk3;
    struct Object *unk4;
    struct Object *unk5;
    struct Object *unk6;
    struct Object *unk7;
    struct Object *unk8;
    struct Object *unk9;
    struct Object *unkA;
    struct Object *unkB;
    struct Object *unkC;
    struct Object *unkD;
    struct Object *unkE;
    struct Object *unkF;
    struct Object *unk10;
    struct Object *unk11;
    struct Object *unk12;
    struct Object *unk13;
    struct Object *unk14;
    struct Object *unk15;
    struct Object *unk16;
    struct Object *unk17;
    struct Object *unk18;
    struct Object *unk19;
    struct Object *unk1A;
    struct Object *unk1B;
    struct Object *unk1C;
    struct Object *unk1E;
    struct Object *unk1F;
    struct Object *unk20;
    struct Object *unk22;
    struct Object *unk23;
    struct Object *unk24;
    struct Object *unk26;
    struct Object *unk27;
    struct Object *unk28;
    struct Object *unk29;
    struct Object *unk2A;
    struct Object *unk2B;
    struct Object *unk2C;
    struct Object *unk2E;
    u8 _pad2F[1];
    struct Object *unk30;
    struct Object *unk32;
    u8 _pad33[1];
    struct Object *unk34;
    struct Object *unk35;
    struct Object *unk36;
    u8 _pad37[1];
    struct Object *unk38;
    struct Object *unk3C;
    struct Object *unk3E;
    u8 _pad3F[1];
    struct Object *unk40;
    struct Object *unk42;
    u8 _pad43[1];
    struct Object *unk44;
    struct Object *unk46;
    u8 _pad47[1];
    struct Object *unk48;
    struct Object *unk4A;
    u8 _pad4B[1];
    struct Object *unk4C;
    struct Object *unk4E;
    u8 _pad4F[1];
    struct Object *unk50;
    struct Object *unk54;
    struct Object *unk58;
    struct Object *unk59;
    struct Object *unk5A;
    struct Object *unk5B;
    struct Object *unk5C;
    struct Object *unk5D;
    u8 _pad5E[2];
    struct Object *unk60;
    struct Object *unk62;
    u8 _pad63[1];
    struct Object *unk64;
    struct Object *unk65;
    struct Object *unk66;
    u8 _pad67[1];
    struct Object *unk68;
    struct Object *unk6C;
    struct Object *unk6E;
    u8 _pad6F[1];
    struct Object *unk70;
    struct Object *unk72;
    u8 _pad73[1];
    struct Object *unk74;
    struct Object *unk76;
    u8 _pad77[1];
    struct Object *unk78;
    struct Object *unk7A;
    u8 _pad7B[1];
    struct Object *unk7C;
    struct Object *unk7E;
    u8 _pad7F[1];
    struct Object *unk80;
    struct Object *unk84;
    struct Object *unk88;
    struct Object *unk8C;
    struct Object *unk90;
    struct Object *unk91;
    struct Object *unk92;
    u8 _pad93[1];
    struct Object *unk94;
    struct Object *unk96;
    u8 _pad97[1];
    struct Object *unk98;
    struct Object *unk9C;
    struct Object *unkA0;
    struct Object *unkA4;
    struct Object *unkA8;
    struct Object *unkA9;
    struct Object *unkAA;
    struct Object *unkAB;
    struct Object *unkAC;
    struct Object *unkB0;
    struct Object *unkB4;
    struct Object *unkB8;
    struct Object *unkBC;
    struct Object *unkC0;
    struct Object *unkC4;
    struct Object *unkC8;
    struct Object *unkCC;
    struct Object *unkD0;
    struct Object *unkD4;
    struct Object *unkD8;
    struct Object *unkDC;
    struct Object *unkE0;
    struct Object *unkE4;
    struct Object *unkE8;
    struct Object *unkEC;
    struct Object *unkF0;
    struct Object *unkF4;
    struct Object *unkF8;
    struct Object *unkFC;
    struct Object *unk100;
    struct Object *unk104;
    struct Object *unk108;
    struct Object *unk10C;
    struct Object *unk110;
    struct Object *unk114;
    struct Object *unk118;
    struct Object *unk11C;
    struct Object *unk120;
    struct Object *unk124;
    struct Object *unk128;
    struct Object *unk12C;
    struct Object *unk130;
    struct Object *unk134;
    struct Object *unk138;
    struct Object *unk13C;
    struct Object *unk140;
    struct Object *unk144;
    struct Object *unk148;
    struct Object *unk14C;
    struct Object *unk150;
    struct Object *unk154;
    struct Object *unk158;
    struct Object *unk15C;
    struct Object *unk160;
    struct Object *unk164;
    struct Object *unk168;
    struct Object *unk16C;
    struct Object *unk170;
    struct Object *unk174;
    struct Object *unk178;
    struct Object *unk17C;
    struct Object *unk180;
    struct Object *unk182;
    u8 _pad183[1];
    struct Object *unk184;
    struct Object *unk188;
    struct Object *unk18A;
    u8 _pad18B[1];
    struct Object *unk18C;
    struct Object *unk18E;
    u8 _pad18F[1];
    struct Object *unk190;
    struct Object *unk191;
    u8 _pad192[2];
    struct Object *unk194;
    struct Object *unk196;
    u8 _pad197[1];
    struct Object *unk198;
    struct Object *unk19A;
    u8 _pad19B[1];
    struct Object *unk19C;
    struct Object *unk1A0;
    u32 _pad1A4;
    struct Object *unk1A8;
    struct Object *unk1AA;
    u8 _pad1AB[1];
    struct Object *unk1AC;
    struct Object *unk1B0;
    struct Object *unk1B2;
    u8 _pad1B3[1];
    struct Object *unk1B4;
    struct Object *unk1B8;
    struct Object *unk1BA;
    u8 _pad1BB[1];
    struct Object *unk1BC;
    u32 _pad1C0;
    struct Object *unk1C4;
    struct Object *unk1C8;
    struct Object *unk1CC;
    struct Object *unk1D0;
    struct Object *unk1D4;
    struct Object *unk1D8;
    struct Object *unk1DC;
    struct Object *unk1E0;
    struct Object *unk1E4;
    struct Object *unk1E8;
    u8 _pad1EC[8];
    struct Object *unk1F4;
    struct Object *unk1F8;
    u32 _pad1FC;
    struct Object *unk200;
    u8 _pad204[16];
    struct Object *unk214;
    struct Object *unk218;
    struct Object *unk21C;
    struct Object *unk220;
    struct Object *unk224;
    struct Object *unk228;
    u8 _pad22C[16];
    struct Object *unk23C;
    struct Object *unk240;
    u8 _pad244[176];
    struct Object *unk2F4;
    u8 _pad2F8[367];
    struct Object *unk467;
    u32 _pad468;
    struct Object *unk46C;
    u8 _pad470[1036];
    struct Object *unk87C;
    u32 _pad880;
    struct Object *unk884;
    struct Object *unk888;
    u8 _pad88C[132];
    struct Object *unk910;
    struct Object *unk914;
    u8 _pad918[12];
    struct Object *unk924;
} Object;

#endif